### ISSUE TITLE
Override the Main in test doesn't work well with Android LiveData

### ISSUE THREAD

**Issue by giangpham96** [Kotlin/kotlinx.coroutines#1011]
I have an Android ViewModel subclass as below
```
class ASimpleViewModel : ViewModel(), CoroutineScope {
    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Main + Job()

    private val job = Job()

    private val mutableLiveData: MutableLiveData<AClass> = MutableLiveData()

    init {
        mutableLiveData.value = AClass.Init
    }
...
}
```
and a simple test
```
class ASimpleViewModelTest {
    private val viewModel = ASimpleViewModel()
    private val mainThreadSurrogate = newSingleThreadContext("UI thread")

    @Before
    fun setUp() {
        Dispatchers.setMain(mainThreadSurrogate)
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain() // reset main dispatcher to the original Main dispatcher
        mainThreadSurrogate.close()
    }
    @Test
    fun `should start in Init state`() {
        assertThat(viewModel.viewStates.value).isEqualTo(AClass.Init)
    }
}
```

However, I got this error when running the test
```
java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.os.Looper.getMainLooper(Looper.java)
	at androidx.arch.core.executor.DefaultTaskExecutor.isMainThread(DefaultTaskExecutor.java:74)
	at androidx.arch.core.executor.ArchTaskExecutor.isMainThread(ArchTaskExecutor.java:116)
	at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:442)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:286)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
	at leo.me.la.presentation.ASimpleViewModel.<init>(ASimpleViewModel.kt:31)
	at leo.me.la.presentation.ASimpleViewModelTest.setUp(ASimpleViewModelTest.kt:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

```
The line which is causing crash is the init block inside `ASimpleViewModel`. Looks like it require a "real" UI Thread, and overriding Main doesn't help. Is there any suggestion to work around this?

**Comment by giangpham96** [comment]
Never mind, having `InstantTaskExecutorRule` inside the Test class helps

**Comment by gusoliveira21** [comment]
@giangpham96  Your test above helped me solve the problem I was having, thanks
