### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlinx/coroutines/experimental/CommonPool

### ISSUE THREAD

**Issue by artem-bakuta** [Kotlin/kotlinx.coroutines#1026]
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:166)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:349)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:299)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:127)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:247)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:18)
	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:52)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:17)
	at com.fashion.ApplicationKt.main(Application.kt:34)
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/experimental/CommonPool
	at com.github.pgutkowski.kgraphql.schema.dsl.SchemaConfigurationDSL.<init>(SchemaConfigurationDSL.kt:16)
	at com.github.pgutkowski.kgraphql.schema.dsl.SchemaBuilder.<init>(SchemaBuilder.kt:18)
	at com.github.pgutkowski.kgraphql.KGraphQL$Companion.schema(KGraphQL.kt:8)
	at db.graphql.AppSchema.<init>(AppSchema.kt:11)
	at com.fashion.ApplicationKt.module(Application.kt:61)
	at com.fashion.ApplicationKt.module$default(Application.kt:38)
	... 18 more
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.experimental.CommonPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

```
Hi, i'm trying to use coroutines syntax in ktor using graph api, and always get this error.
Error at invoking this: 
import com.github.pgutkowski.kgraphql.KGraphQL

val schema = KGraphQL.schema {
}

any suggestions ? Thx )

**Comment by qwwdfsad** [comment]
It looks like you are using too old version of `KGraphQL` that depend on experimental coroutines (pre-1.0.0).
Could you please update `KGraphQL` to the latest version and report if that helped?

**Comment by artem-bakuta** [comment]
It's really helped thx !!!
