### ISSUE TITLE
Stacktrace seems to be missing any indication of user code

### ISSUE THREAD

**Issue by oshai** [Kotlin/kotlinx.coroutines#1109]
See the following example that uses retrofit:
```kotlin
import com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory
import kotlinx.coroutines.Deferred
import okhttp3.OkHttpClient
import okhttp3.ResponseBody
import retrofit2.Retrofit
import retrofit2.http.GET


suspend fun main() {
    createService("http://www.google.com/", MyService::class.java)
        .run()
        .await()
}

fun <T> createService(baseUrl: String, clazz: Class<T>): T {
    val httpClient = OkHttpClient.Builder().build()
    val retrofit = Retrofit.Builder().baseUrl(baseUrl)
        //for coroutines deferred
        .addCallAdapterFactory(CoroutineCallAdapterFactory())
        .client(httpClient).build()
    return retrofit.create(clazz)
}

interface MyService {

    @GET("blabla")
    fun run(): Deferred<ResponseBody>
}

```

The exception that is thrown is the following:
```
Exception in thread "main" retrofit2.HttpException: HTTP 404 Not Found
	at com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:104)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I am not 100% sure if this is coroutines issue or retrofit integration, but I wish to see somehow a stacktrace with my code, I tried also to enable debug `-ea` but didn't see any effect.

**Comment by qwwdfsad** [comment]
This is expected behaviour, see [`debugging.md`](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md):
>If the exception class implements CopyableThrowable, CopyableThrowable.createCopy is used.
If the exception class has class-specific fields not inherited from Throwable, the exception is not copied.

`HttpException` has class-specific fields and does not implement `CopyableThrowable`, so it is not copied.

**Comment by oshai** [comment]
Is there any way to workaround that from my side?

**Comment by qwwdfsad** [comment]
Alas, no

**Comment by oshai** [comment]
ok. After checking the code of `CoroutineCallAdapterFactory` I will try to create a PR there.
