### ISSUE TITLE
data class become null in unit test

### ISSUE THREAD

**Issue by selmanon** [Kotlin/kotlinx.coroutines#1119]
I'm trying to migrate an RxJava based sample project to coroutines. The migration was to easy but actually I'm facing a problem while trying to migrate unit test. 

The UT code that rise this issue is :

    @Test
    fun fetchCars_Error() = runBlocking  {
        doReturn(Throwable("")).`when`(repository)
            .loadCars("X", "Y")
        carsPresenter.fetchCars("XX", "YY")
        verify(view, times(1)).hideLoadingProgress()
        verify(view, times(1)).showCarsError(ArgumentMatchers.anyString())
    }

The exception rised by this code is : 
> Exception in thread "main @coroutine#2" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.android.cars.DefaultCarsPresenter.doOnCarsSuccess, parameter success
	at com.android.cars.DefaultCarsPresenter.doOnCarsSuccess(DefaultCarsPresenter.kt)
	at com.android.cars.DefaultCarsPresenter$fetchCars$1.invokeSuspend(DefaultCarsPresenter.kt:43)

with CarsRepository.loadCars defined as follow :

    override suspend fun loadCars(departure: String, arrival: String): ApiCars =
        remoteDataSource.loadTrips(departure, arrival)

And DefaultCarsPresenter.fetchCars defined as follow : 

    override fun fetchCars(departure: String, arrival: String) {
        job = CoroutineScope(coroutineContext).launch {
            var apiCars = ApiCars()
            try {
                apiCars = carsRepository.loadCars(departure, arrival)
            } catch (e: Exception) {
                doOnCarsError(e)
            }
            doOnCarsSuccess(apiTrips) // line 43
        }
    }

The complete stack trace :

>Exception in thread "main @coroutine#2" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.android.cars.DefaultCarsPresenter.doOnCarsSuccess, parameter success
	at com.android.cars.DefaultCarsPresenter.doOnCarsSuccess(DefaultCarsPresenter.kt)
	at com.android.cars.DefaultCarsPresenter$fetchCars$1.invokeSuspend(DefaultCarsPresenter.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:447)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.android.cars.DefaultCarsPresenter.fetchCars(DefaultCarsPresenter.kt:36)
	at com.android.cars.DefaultCarsPresenterTest$fetchCars_Error$1.invokeSuspend(DefaultCarsPresenterTest.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.android.cars.DefaultCarsPresenterTest.fetchCars_Error(DefaultCarsPresenterTest.kt:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:78)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:84)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:53)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Wanted but not invoked:
view.hideLoadingProgress();
-> at com.android.cars.DefaultCarsPresenterTest$fetchCars_Error$1.invokeSuspend(DefaultCarsPresenterTest.kt:48)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
view.hideLoadingProgress();
-> at com.android.cars.DefaultCarsPresenterTest$fetchCars_Error$1.invokeSuspend(DefaultCarsPresenterTest.kt:48)
Actually, there were zero interactions with this mock.

	at com.android.cars.DefaultCarsPresenterTest$fetchCars_Error$1.invokeSuspend(DefaultCarsPresenterTest.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.android.cars.DefaultCarsPresenterTest.fetchCars_Error(DefaultCarsPresenterTest.kt:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:78)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:84)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:53)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

[MockitoHint] DefaultCarsPresenterTest.fetchCars_Error (see javadoc for MockitoHint):
[MockitoHint] 1. Unused... -> at com.android.cars.DefaultCarsPresenterTest$fetchCars_Error$1.invokeSuspend(DefaultCarsPresenterTest.kt:44)
[MockitoHint]  ...args ok? -> at com.android.cars.DefaultCarsPresenter$fetchCars$1.invokeSuspend(DefaultCarsPresenter.kt:39)

PS. The same unit test code is working with RxJava.

**Comment by qwwdfsad** [comment]
It looks like you are using an old version of Mockito.
Non-experimental coroutines work only with Mockito [since version 2.23](https://stackoverflow.com/questions/53098975/mocked-suspend-function-returns-null-in-mockito/53101077#53101077)
Could you please update your Mockito version and see if the problem is resolved?

**Comment by selmanon** [comment]
@qwwdfsad Indeed I was using Mockito version 2.13 problem gone after updating to version 2.23.
Thanks!
