### ISSUE TITLE
Coroutines crash when call block.invoke(this) - Fatal exception in coroutines machinery for DispatchedContinuation

### ISSUE THREAD

**Issue by kdk96** [Kotlin/kotlinx.coroutines#1150]
Kotlin `1.3.31`, Coroutines `1.2.1`
I have the crash when I use following inline extension function:

```
inline fun CoroutineScope.launch(crossinline block: suspend CoroutineScope.() -> Unit) {
    launch {
        block.invoke(this)
    }
}
```

But it does not occur with similar inline functions

```
inline fun CoroutineScope.launch(crossinline block: suspend CoroutineScope.() -> Unit) {
    launch {
        block(this)
    }
}

inline fun CoroutineScope.launch(crossinline block: suspend CoroutineScope.() -> Unit) {
    launch {
        block()
    }
}
```
or just extension function

```
fun CoroutineScope.launch(block: suspend CoroutineScope.() -> Unit) {
    launch {
        block.invoke(this)
    }
}
```

Crash log:

```
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@45fe3ee3, Continuation at MainKt$main$1$invokeSuspend$$inlined$launchK$1@75a1cd57]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(Dispatched.kt:275)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:246)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.kt:88)
	at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:110)
	at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:104)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.main(Main.kt:8)
	at MainKt.main(Main.kt)
Caused by: java.lang.IllegalStateException: Job StandaloneCoroutine{Completed}@3b764bce is already complete or completing, but is being completed with CompletedExceptionally[kotlinx.coroutines.JobCancellationException: StandaloneCoroutine has completed normally; job=StandaloneCoroutine{Completed}@3b764bce]
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:765)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:324)
	... 11 more
Caused by: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine has completed normally; job=StandaloneCoroutine{Completed}@3b764bce
```

code sample

```
fun main() {
    runBlocking {
        launch {
            delay(200)
            println("hello")
        }
    }
}
```

What is the difference between block(), block(this) and block.invoke(this)

**Comment by qwwdfsad** [comment]
It is a bug in a `crossinline` machinery in the compiler, filed https://youtrack.jetbrains.com/issue/KT-31269, please keep track on this issue there

>What is the difference between block(), block(this) and block.invoke(this)

There should be no difference at all.
