### ISSUE TITLE
Exception java.lang.VerifyError: Call to wrong <init> method. Reason: Type '$lambda$2' (constant pool 2) is not assignable to '$lambda$1' (constant pool 98)

### ISSUE THREAD

**Issue by dhorman** [Kotlin/kotlinx.coroutines#1175]
Simple code with coroutines produces VerifyError exception

```kotlin
package com.example.app

import kotlinx.coroutines.*
import kotlinx.coroutines.reactive.collect
import kotlinx.coroutines.reactor.flux
import reactor.core.publisher.Flux

fun subscribeTo(channel: Int): Flux<String> = GlobalScope.flux {
    Flux.just(Flux.never<String>()).collect { messages ->
        try {
            messages.collect { }
        } finally {
            withContext(NonCancellable) {
                println("$channel")
            }
        }
    }
}

fun main(args: Array<String>) {
    runBlocking {
        val x = subscribeTo(1).subscribe()
        delay(2000)
        x.dispose()
        delay(2000)
    }
}
```

Stacktrace

```
Exception in thread "DefaultDispatcher-worker-1" java.lang.VerifyError: Call to wrong <init> method
Exception Details:
  Location:
    com/example/app/MainKt$subscribeTo$1$invokeSuspend$$inlined$collect$lambda$2.create(Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Lkotlin/coroutines/Continuation; @15: invokespecial
  Reason:
    Type 'com/example/app/MainKt$subscribeTo$1$invokeSuspend$$inlined$collect$lambda$2' (constant pool 2) is not assignable to 'com/example/app/MainKt$subscribeTo$1$invokeSuspend$$inlined$collect$lambda$1' (constant pool 98)
  Bytecode:
    0000000: 2c12 58b8 005e bb00 0259 2c2a b400 16b7
    0000010: 0062 4e2b c000 6457 2d2b c000 64b5 002c
    0000020: 2d3a 0419 04b0                         

	at com.example.app.MainKt$subscribeTo$1.invokeSuspend(Main.kt:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:324)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Dependencies

```
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactive:1.2.1")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:1.2.1")
implementation("io.projectreactor:reactor-core:3.2.8.RELEASE")
```

**Comment by qwwdfsad** [comment]
Thanks for the report.
It is a bug in the Kotlin compiler, I will minimize it and report to youtrack to keep track on

**Comment by qwwdfsad** [comment]
Please keep track under [KT-31423](https://youtrack.jetbrains.com/issue/KT-31423)

**Comment by dhorman** [comment]
@qwwdfsad, Thanks Seva!
