### ISSUE TITLE
Building channel producers example code causes exception randomly

### ISSUE THREAD

**Issue by kengura** [Kotlin/kotlinx.coroutines#122]
Sometimes there is exception while running  [building channel producers example code](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/src/test/kotlin/guide/example-channel-03.kt) 

```
fun produceSquares() = produce<Int>(CommonPool) {
    for (x in 1..5) send(x * x)
}

fun main(args: Array<String>) = runBlocking<Unit> {
    val squares = produceSquares()
    squares.consumeEach { println(it) }
    println("Done!")
}
```

This happens not always, approximately once per 5-10 runs.

Exception:

```
1
Exception in thread "main" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Boolean
	at TestKt$main$1.doResume(Test.kt:13)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:225)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142)
	at TestKt.main(Test.kt:8)
```

or

```
1
4
9
16
25
Exception in thread "kotlinx.coroutines.DefaultExecutor" Exception in thread "main" java.lang.IllegalStateException: Already resumed, but got exception java.util.concurrent.CancellationException: Job was cancelled
	at kotlinx.coroutines.experimental.AbstractCoroutine.resumeWithException(AbstractCoroutine.kt:61)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:59)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:119)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:54)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CancellationException: Job was cancelled
	at kotlinx.coroutines.experimental.JobSupport$CompletedExceptionally.getException(Job.kt:903)
	at kotlinx.coroutines.experimental.CancellableContinuationImpl.afterCompletion(CancellableContinuation.kt:208)
	at kotlinx.coroutines.experimental.JobSupport.completeUpdateState(Job.kt:563)
	at kotlinx.coroutines.experimental.JobSupport.updateState(Job.kt:514)
	at kotlinx.coroutines.experimental.JobSupport.updateStateCancelled(Job.kt:778)
	at kotlinx.coroutines.experimental.JobSupport.makeCancelled(Job.kt:784)
	at kotlinx.coroutines.experimental.JobSupport.cancel(Job.kt:773)
	at kotlinx.coroutines.experimental.JobSupport.onParentCancellation(Job.kt:473)
	at kotlinx.coroutines.experimental.JobSupport$ParentOnCancellation.invokeOnce(Job.kt:461)
	at kotlinx.coroutines.experimental.JobCancellationNode.invoke(Job.kt:1088)
	at kotlinx.coroutines.experimental.JobSupport.completeUpdateState(Job.kt:552)
	at kotlinx.coroutines.experimental.JobSupport.updateState(Job.kt:514)
	at kotlinx.coroutines.experimental.AbstractCoroutine.resumeWithException(AbstractCoroutine.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:225)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142)
	at TestKt.main(Test.kt:8)
java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Boolean
	at TestKt$main$1.doResume(Test.kt:13)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:225)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142)
	at TestKt.main(Test.kt:8)
```

**Comment by elizarov** [comment]
Can you, please, share some details on your environment: what version of `kotlinx.coroutines` you are using, what JVM version, what OS & architecture you are running it. It does not reproduce for me on a few machines you've tried.

**Comment by kengura** [comment]
Today i can't reproduce an issue. Have no idea what has changed.

My settings, just in case:

build.gradle

```
buildscript {
    ext.kotlin_version = '1.1.4'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
    compile 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.18'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

iMac, OS X El Capitan 10.11.6

**Comment by elizarov** [comment]
Closing as non-reproduceable
