### ISSUE TITLE
Proguard changes program flow of coroutines

### ISSUE THREAD

**Issue by awenger** [Kotlin/kotlinx.coroutines#1288]
While trying to reproduce #1035 I found a similar or related problem:
```kt
private val actor = setupActor()

private fun trigger() {
    runBlocking { actor.send(jobId++) }
}

private fun setupActor(): SendChannel<Int> {
    return GlobalScope.actor {
        for (msg in channel) {
            val successful = call()
            Log.d(LOG_TAG, "success: $successful")
        }
    }
}

private suspend fun call() = try {
    coroutineScope {
        val result1 = async { retrieve() }
        val result2 = async { retrieve() }
        listOf(result1, result2).awaitAll()
        Log.d(LOG_TAG, "all successful retrieved")
        true
    }
} catch (ex: IOException) {
    Log.e(LOG_TAG, "caught ${ex.message}")
    false
}

@Throws(IOException::class)
private suspend fun retrieve() {
    delay(100)
    Log.d(LOG_TAG, "waited for 100ms, throwing IOException")
    throw IOException("could not contact server")
}
```
Depending if proguard minification is enabled or not, the execution flow of the sample coroutines changes. Without minification the Exceptions are properly handled.
```
D/Main: waited for 100ms, throwing IOException
E/Main: caught could not contact server
D/Main: success: false
```
With minification enabled the exception is no longer handled and just disappeared.
```
D/Main: waited for 100ms, throwing IOException
D/Main: waited for 100ms, throwing IOException
D/Main: all successful retrieved
D/Main: success: true
```
I uploaded a project that demonstrates the problem here: https://github.com/awenger/coroutinesobfuscationcrash

**Comment by qwwdfsad** [comment]
Good job pinning it down to minification! It's definitely a ProGuard bug as consecutive `result1.await()` will return `Unit`, while it clearly should not.
Could you please report it to [Google bug tracker](https://issuetracker.google.com/issues/new)?

**Comment by qwwdfsad** [comment]
Another data point, changing `retrieve` to have a return type:
```
 @Throws(IOException::class)
private suspend fun retrieve(): Int {
  delay(100)
  Log.d(LOG_TAG, "waited for 100ms, throwing IOException")
  throw IOException("could not contact server")
  return 1
}
```
will start triggering CCE:
```
java.lang.ClassCastException: a.g$b cannot be cast to java.lang.Boolean
        at com.github.awenger.coroutinesobfuscationcrash.MainActivity$f.a(Unknown Source)
        at a.b.b.a.a.b(Unknown Source)
        at kotlinx.coroutines.b.o.a(Unknown Source)
        at kotlinx.coroutines.bl.b(Unknown Source)
```

**Comment by awenger** [comment]
Great, that is a much simpler way to trigger the ClassCastException, that I was trying to reproduce for #1035. I already reported the problems directly to guardsquare.

**Comment by qwwdfsad** [comment]
Thanks! Then I'll close this one.
