### ISSUE TITLE
Exception stackrace recovery place to top invalid line number

### ISSUE THREAD

**Issue by evgzakharov** [Kotlin/kotlinx.coroutines#1342]
Seems that stacktrace recovery place to top invalid line number. Minimal reproduce code:
```
class SimpleTest {
    suspend fun testInvoke(action: suspend () -> Unit) {
        action()
    }

    @Test
    fun first() = runBlocking {
        testInvoke {
            returnResult()
                ?: throw RuntimeException("fail") // line 15
        }
    }

    @Test
    fun second() = runBlocking {
        testInvoke {  // line 21
            returnResult() ?: throw RuntimeException("fail")  // line 22
        }
    }

    suspend fun returnResult(): Boolean? {
        return null
    }
}
```
If run `first` test, you will see error:
```
java.lang.RuntimeException: fail
	at co.fun.games.warstrike.tester.SimpleTest$first$1$1.invokeSuspend(SimpleTest.kt:15)
	at co.fun.games.warstrike.tester.SimpleTest$first$1$1.invoke(SimpleTest.kt)
	at co.fun.games.warstrike.tester.SimpleTest.testInvoke(SimpleTest.kt:8)
	at co.fun.games.warstrike.tester.SimpleTest$first$1.invokeSuspend(SimpleTest.kt:13)
        ...
```
All looks as excepted, but if you run `second` method, exception will be:
```
java.lang.RuntimeException: fail
	at co.fun.games.warstrike.tester.SimpleTest$second$1$1.invokeSuspend(SimpleTest.kt:21)
	at co.fun.games.warstrike.tester.SimpleTest$second$1$1.invoke(SimpleTest.kt)
	at co.fun.games.warstrike.tester.SimpleTest.testInvoke(SimpleTest.kt:8)
	at co.fun.games.warstrike.tester.SimpleTest$second$1.invokeSuspend(SimpleTest.kt:21)
        ...
```
there it points to 21 line, but expected to be pointed to 22 line

**Comment by qwwdfsad** [comment]
Thanks for the report with a reproducer!
It is actually not a `kotlinx.coroutines` issue, but a compiler one. Stacktrace recovery only kicks in when exception crosses coroutine boundary, e.g. is thrown through `withContext` or `await` call.

I've filled https://youtrack.jetbrains.com/issue/KT-32689

**Comment by evgzakharov** [comment]
Thanks for fast response and for creating an issue!
