### ISSUE TITLE
Provided example test for withTimeout fails

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1390]
I just copied the following into my IDE from the [README.md](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-test#testing-launch-or-async-with-delay)

```kotlin
@Test(expected = TimeoutCancellationException::class)
fun testFooWithTimeout() = runBlockingTest {
    val uncompleted = CompletableDeferred<Unit>() // this Deferred<Foo> will never complete
    foo(uncompleted)
    advanceTimeBy(1_000) // advance time, which will cause the timeout to throw an exception
    // ...
}

fun CoroutineScope.foo(resultDeferred: Deferred<Unit>) {
    launch {
        withTimeout(1_000) {
            resultDeferred.await() // await() will suspend forever waiting for uncompleted
            // ...
        }
    }
}
```

I expected the test to pass, but it failed with the following exception:

```kotlin
java.lang.AssertionError: Expected exception: kotlinx.coroutines.TimeoutCancellationException

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

`advanceTimeBy(..)` does cause the timeout exception to be thrown, but `runBlockingTest` may be swallowing it.

**Comment by elizarov** [comment]
cc @objcode

**Comment by douo** [comment]
Same Issue.  @elizarov @objcode 
pass:
```
    @Test(expected = Exception::class)
    fun throwException() = runBlockingTest {
        launch {
            throw Exception()
        }
    }
```

pass 
```
    @Test(expected = TimeoutCancellationException::class)
    fun throwTimeoutCancellationExceptionDirectly() = runBlockingTest {
            withTimeout(-1) {}
    }
```

failed:
```
   @Test(expected = TimeoutCancellationException::class)
    fun throwTimeoutCancellationException() = runBlockingTest {
        launch {
            withTimeout(-1) {}
        }
    }

```

**Comment by dkhalanskyjb** [comment]
The docs are faulty here. Not much can be done on the test module's side here to make the test pass as it is, unfortunately: this issue can be replicated easily with `runBlocking` as well and is purely an interplay between `launch` and `withTimeout`, where the parent job doesn't cancel upon its child's failure if the exception is a `CancellationException`, which `TimeoutCancellationException` is: https://github.com/Kotlin/kotlinx.coroutines/issues/1374.
