### ISSUE TITLE
Spring 5.2 and OAuth2 Security - Integration with the kotlin coroutines, but at runtime I always have NPE.

### ISSUE THREAD

**Issue by gurk0001** [Kotlin/kotlinx.coroutines#1398]
```
  @RestController
  class SomeController() {

      val webClient = WebClient.builder()
        .baseUrl("https://www.google.com")
        .build()

      @GetMapping
      suspend fun get(): String? {
          return webClient
              .get()
              .awaitExchange()
              .awaitBody()
      }
  }
```
with Dependencies

```dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation(group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.3.0-RC")
    implementation(group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = "1.3.0-RC")
implementation(group = "org.springframework.boot", name = "spring-cloud-starter-oauth2", version = "2.1.3.RELEASE")
    implementation(group = "org.springframework.boot", name = "spring-boot-starter-webflux", version = "2.2.0.M4")
}
```

and NPE on .awaitExchange ():

```
kotlin.KotlinNullPointerException: null
    at kotlin.coroutines.jvm.internal.ContinuationImpl.getContext(ContinuationImpl.kt:105) ~[kotlin-stdlib-1.3.40.jar:1.3.40-release-123 (1.3.40)]
    at kotlin.coroutines.jvm.internal.ContinuationImpl.<init>(ContinuationImpl.kt:102) ~[kotlin-stdlib-1.3.40.jar:1.3.40-release-123 (1.3.40)]
    at org.springframework.web.reactive.function.client.WebClientExtensionsKt$awaitExchange$1.<init>(WebClientExtensions.kt) ~[spring-webflux-5.2.0.M3.jar:5.2.0.M3]
    at org.springframework.web.reactive.function.client.WebClientExtensionsKt.awaitExchange(WebClientExtensions.kt) ~[spring-webflux-5.2.0.M3.jar:5.2.0.M3]
    at com.test.SomeController.get$suspendImpl(SomeController.kt:22) ~[classes/:na]
    at com.test.SomeController.get(SomeController.kt) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
    at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:146) ~[spring-webflux-5.2.0.M3.jar:5.2.0.M3]
    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) [reactor-core-3.3.0.M2.jar:3.3.0.M2]
    at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1575) ~[reactor-core-3.3.0.M2.jar:3.3.0.M2]
...
```

**Comment by gurk0001** [comment]
For your information, same code works find without adding OAUTH2 security module 
```
implementation(group = "org.springframework.boot", name = "spring-cloud-starter-oauth2", version = "2.1.3.RELEASE")
```

**Comment by SeekDaSky** [comment]
I don't think this is the correct place to post your issue as this is likely to be a problem in the oauth spring module.

try the Spring github page, they will probably be of more assistance.

**Comment by gurk0001** [comment]
sure thank you.
