### ISSUE TITLE
Build failed with inline function : 1.5.0

### ISSUE THREAD

**Issue by botesan** [Kotlin/kotlinx.coroutines#1467]
I got a build failed.
I used this command line: 
> konanc.bat -opt test.kt

test.kt is:
```
interface SequenceInt {
    fun iterator(): IntIterator
}
inline fun SequenceInt.forEach(operation: (Int) -> Unit) {
    val iterator = iterator()
    while(iterator.hasNext()) {
        operation(iterator.nextInt())
    }
}
fun main(args: Array<String>) {
    val s = object : SequenceInt {
        override fun iterator() = object : IntIterator() {
            var value = 0
            override fun hasNext() = value < 10
            override fun nextInt() = value++
        }
    }
    s.forEach { println(it) }
}
```
Error is:
> error: compilation failed: null
> 
>  * Source files: test.kt
>  * Compiler version info: Konan: 1.3.50 / Kotlin: 1.3.50
>  * Output kind: PROGRAM
> 
> exception: kotlin.KotlinNullPointerException
>         at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$InstantiationsSearcher.processVirtualCall(Devirtualization.kt:285)
>         at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$InstantiationsSearcher.dfs(Devirtualization.kt:408)
>         at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$InstantiationsSearcher.search(Devirtualization.kt:260)
>         at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis.analyze(Devirtualization.kt:558)
>         at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization.run(Devirtualization.kt:1186)
>         at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$devirtualizationPhase$1.invoke(BitcodePhases.kt:74)
>         at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$devirtualizationPhase$1.invoke(BitcodePhases.kt)
>         at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:57)
>         at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:55)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
>         at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
>         at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
>         at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
>         at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
>         at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
>         at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
>         at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
>         at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
>         at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
>         at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
>         at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
>         at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
>         at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
>         at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
>         at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
>         at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
>         at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
>         at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
>         at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
>         at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:223)
>         at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:220)
>         at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:26)
>         at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:21)
>         at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:222)
>         at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
>         at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)

Delete 'inline', build successed.
```
interface SequenceInt {
    fun iterator(): IntIterator
}
/*inline*/ fun SequenceInt.forEach(operation: (Int) -> Unit) {
    val iterator = iterator()
    while(iterator.hasNext()) {
        operation(iterator.nextInt())
    }
}
fun main(args: Array<String>) {
    val s = object : SequenceInt {
        override fun iterator() = object : IntIterator() {
            var value = 0
            override fun hasNext() = value < 10
            override fun nextInt() = value++
        }
    }
    s.forEach { println(it) }
}
```

**Comment by botesan** [comment]
Sorry, I miss post.
This issue is kotlin/Native.
