### ISSUE TITLE
 Module with the Main dispatcher is missing with version 1.3.1

### ISSUE THREAD

**Issue by SteinerOk** [Kotlin/kotlinx.coroutines#1509]
After update coroutines from version 1.3.0 to 1.3.1 got this error:
If it matter - Android 9.0, without ProGuard

```
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
 at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:90)
 at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:71)
 at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:420)
 at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
 at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
 at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
 at kotlinx.coroutines.BuildersKtBuilders_commonKt.launch(Builders.common.kt:54)
 at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
 at kotlinx.coroutines.BuildersKtBuilders_commonKt.launch$default(Builders.common.kt:47)
 at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
 at ru.omnidesk.android.app.ui.launcher.LauncherViewModel.prepareEnvironment(LauncherViewModel.kt:82)
 at ru.omnidesk.android.app.ui.launcher.LauncherViewModel.defineLaunchDestination(LauncherViewModel.kt:64)
 at ru.omnidesk.android.app.ui.launcher.LauncherActivity.handleIntentExtras(LauncherActivity.kt:108)
 at ru.omnidesk.android.app.ui.launcher.LauncherActivity.onCreate(LauncherActivity.kt:63)
 at android.app.Activity.performCreate(Activity.java:7224)
 at android.app.Activity.performCreate(Activity.java:7213)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6806)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by elizarov** [comment]
This is very strange, since there are no changes, as far as I can see, between `1.3.0` and `1.3.1` that might have this effect. Can you publish some test project that demonstrates this problem, please.

**Comment by elizarov** [comment]
I've verified the test project that is included in `kotlinx.coroutines` (version `1.3.1`) by building and running it in Android emulator (Pixel 2 API 28):
 ✅ Gradle `5.1.1`, AGP `3.4.1`
 ✅ Gradle `5.4.1`, AGP `3.5.0`

**Comment by elizarov** [comment]
What AGP version and minification/proguard/R8 settings are you using?

**Comment by Virgiel** [comment]
I had the same issue after upgrading but doing a "clean project" task resolved it.

**Comment by SteinerOk** [comment]
@elizarov It is so curiously. I use:
Gradle - 5.6
AGP - 3.5
Proguard/R8 - disabled:
           android.enableR8=false
           minifyEnabled false
           shrinkResources false
           useProguard false

**Comment by elizarov** [comment]
@SteinerOk I've tried the project with these settings. The only problem I see in build log is this one:
```
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
```
Otherwise, it builds and runs normally, so there's something else. Can you share the project files that would reproduce the problem?

**Comment by SteinerOk** [comment]
@elizarov This is very strange, but really cleaning up the project and the build cache, invalidating in Android Studio, the removal of the application from the device helped solve the problem

**Comment by pvegh** [comment]
I'm just having this also suddenly, after upgrading from 1.3.0 to 1.3.1

**Comment by rontho** [comment]
> I'm just having this also suddenly, after upgrading from 1.3.0 to 1.3.1

Same for me. Is anyone is able to understand why it is happening and how to solve it ?
