### ISSUE TITLE
ListenableFutureTest.testFutureCompletedWithNullAsDeferred hangs

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1510]
```
"Test worker" #11 prio=5 os_prio=0 tid=0x0000000014252000 nid=0xafc waiting on condition [0x00000000148fc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f8882240> (a kotlinx.coroutines.BlockingCoroutine)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:82)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.TestBase.runTest(TestBase.kt:188)
	at kotlinx.coroutines.TestBase.runTest$default(TestBase.kt:182)
	at kotlinx.coroutines.guava.ListenableFutureTest.testFutureCompletedWithNullAsDeferred(ListenableFutureTest.kt:439)
```

**Comment by qwwdfsad** [comment]
```
Sep 13, 2019 11:55:30 AM com.google.common.util.concurrent.AbstractFuture executeListener
[11:55:32][:kotlinx-coroutines-guava:test]     SEVERE: RuntimeException while executing runnable CallbackListener{kotlinx.coroutines.guava.ListenableFutureKt$asDeferred$5@71da146} with executor MoreExecutors.directExecutor()
[11:55:32][:kotlinx-coroutines-guava:test]     kotlin.KotlinNullPointerException
[11:55:32][:kotlinx-coroutines-guava:test]     	at kotlinx.coroutines.guava.ListenableFutureKt$asDeferred$5.onSuccess(ListenableFuture.kt:145)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1021)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1137)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptibly(TrustedListenableFutureTask.java:131)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:133)
[11:55:32][:kotlinx-coroutines-guava:test]     	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[11:55:32][:kotlinx-coroutines-guava:test]     	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[11:55:32][:kotlinx-coroutines-guava:test]     	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:55:32][:kotlinx-coroutines-guava:test]     	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:55:32][:kotlinx-coroutines-guava:test]     	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:55:32][:kotlinx-coroutines-guava:test]     	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
in the build log

**Comment by zyp0759** [comment]
> ```
> "Test worker" #11 prio=5 os_prio=0 tid=0x0000000014252000 nid=0xafc waiting on condition [0x00000000148fc000]
>    java.lang.Thread.State: TIMED_WAITING (parking)
> 	at sun.misc.Unsafe.park(Native Method)
> 	- parking to wait for  <0x00000000f8882240> (a kotlinx.coroutines.BlockingCoroutine)
> 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:82)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 	at kotlinx.coroutines.TestBase.runTest(TestBase.kt:188)
> 	at kotlinx.coroutines.TestBase.runTest$default(TestBase.kt:182)
> 	at kotlinx.coroutines.guava.ListenableFutureTest.testFutureCompletedWithNullAsDeferred(ListenableFutureTest.kt:439)
> ```

Similar to your issue, do you how to solve [issue 1697](https://github.com/Kotlin/kotlinx.coroutines/issues/1697)
