### ISSUE TITLE
example-select-03.kt crashes

### ISSUE THREAD

**Issue by anolivetree** [Kotlin/kotlinx.coroutines#158]
compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.2"
compile "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.19.3"

example-select-03.kt crashes with following stacktrace.

```
/usr/lib/jvm/java-8-oracle/bin/java -Dvisualvm.id=8482677796201124 -javaagent:/home/sakurai/bin/idea-IC-171.3780.107/lib/idea_rt.jar=35023:/home/sakurai/bin/idea-IC-171.3780.107/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/sakurai/project/kotlin/exampleproj/build/classes/main:/home/sakurai/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre8/1.1.2/cd6d8b7a32971564fab0846009593f3bfabdcac1/kotlin-stdlib-jre8-1.1.2.jar:/home/sakurai/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/0.19.3/5c3df93a4ab645e801b27a03299b320344ca8846/kotlinx-coroutines-core-0.19.3.jar:/home/sakurai/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.1.2/8fe14858be2d85bb2c8ad1e060f6dafbd45f48f4/kotlin-stdlib-jre7-1.1.2.jar:/home/sakurai/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.51/e34fe80c9714240525f665113dd3749415515655/kotlin-stdlib-1.1.51.jar:/home/sakurai/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar MainKt
Exception in thread "main" java.lang.RuntimeException: Unexpected exception running DispatchTask[MainKt$main$1@5b37e0d2, cancellable=false, value=kotlinx.coroutines.experimental.JobCancellationException: Child job was cancelled because of parent failure; job=CancellableContinuation(DispatchedContinuation[BlockingEventLoop@69663380, MainKt$main$1@5b37e0d2]){Cancelled}@4459eb14]
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:127)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.ThreadEventLoop.shutdown(EventLoop.kt:264)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:224)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:152)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:145)
	at MainKt.main(main.kt:35)
Caused by: java.lang.IllegalStateException: Job BlockingCoroutine{CompletedExceptionally}@14514713 is already complete, but is being completed with CompletedExceptionally[kotlinx.coroutines.experimental.JobCancellationException: Child job was cancelled because of parent failure; job=CancellableContinuation(DispatchedContinuation[BlockingEventLoop@69663380, MainKt$main$1@5b37e0d2]){Cancelled}@4459eb14]
	at kotlinx.coroutines.experimental.JobSupport.makeCompleting$kotlinx_coroutines_core(Job.kt:975)
	at kotlinx.coroutines.experimental.AbstractCoroutine.resumeWithException(AbstractCoroutine.kt:51)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:59)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:122)
	... 7 more
Caused by: kotlinx.coroutines.experimental.JobCancellationException: Child job was cancelled because of parent failure; job=CancellableContinuation(DispatchedContinuation[BlockingEventLoop@69663380, MainKt$main$1@5b37e0d2]){Cancelled}@4459eb14
	at kotlinx.coroutines.experimental.JobSupport.cancelChildrenInternal(Job.kt:998)
	at kotlinx.coroutines.experimental.JobSupport.makeCompleting$kotlinx_coroutines_core(Job.kt:987)
	at kotlinx.coroutines.experimental.AbstractCoroutine.resumeWithException(AbstractCoroutine.kt:51)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
	at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:214)
	... 3 more
Caused by: java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Boolean
	at MainKt$main$1.doResume(main.kt:48)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	... 7 more

Process finished with exit code 1
```

**Comment by elizarov** [comment]
What OS and hardware do you use? (trying to reproduce)

**Comment by anolivetree** [comment]
Ubuntu 17.04, Intel(R) Core(TM) i7-4770(4core, 8threads)

**Comment by anolivetree** [comment]
It crashes at produceNumbers(coroutineContext, side).consumeEach.
I guess hasNextSuspend() should return Boolean but COROUTINE_SUSPENDED is Object.

consumeEach
↓
    private class Itr<E>(val channel: AbstractChannel<E>) : ChannelIterator<E> {
        suspend override fun hasNext(): Boolean {
            // slow-path does suspend
            return hasNextSuspend() ★
        }
↓
private suspend fun hasNextSuspend(): Boolean = suspendAtomicCancellableCoroutine(holdCancellability = true) sc@ { ★
↓
public inline suspend fun <T> suspendAtomicCancellableCoroutine(
): T =
    suspendCoroutineOrReturn { cont ->
        cancellable.getResult() ★
    }
↓
    internal fun getResult(): Any? {
        if (trySuspend()) return COROUTINE_SUSPENDED ★

**Comment by anolivetree** [comment]
> It crashes at produceNumbers(coroutineContext, side).consumeEach.

I meant that a error happens at consumeEach and ProducerCorourine's state is set to "Cancelled (Child job was cancelled bacause of ...)". 
The program continues running until RuntimeException is thrown at delay(100).

**Comment by elizarov** [comment]
Ok. I guess I see now where the problem is. It was hidden in the plain sight:

```
compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.2"
```

while `kotlinx.coroutines` library requires Kotlin standard library `1.1.4` or later.

**Comment by anolivetree** [comment]
Do I need to use kotlin compiler 1.1.4 too? Changing only stdlib to 1.1.4 didn't solve the problem. Switching from IDEA 2017.1.5 to IDEA 2017.2.5 seemed to have solved the problem.

**Comment by elizarov** [comment]
You'll need 1.1.4+ compiler, too. Updating IDEA version had probably updated your compiler version

**Comment by anolivetree** [comment]
OK. Thank you. I haven't seen the problem on 1.1.4 so far.
