### ISSUE TITLE
testGuideContextExample06 fails sometimes

### ISSUE THREAD

**Issue by anolivetree** [Kotlin/kotlinx.coroutines#160]
IDEA 2017.2.5
kotlinx.coroutines version 0.19.3 (commit eb98bc8e84db9ed620cba9d88384244dea92d002)
Ubuntu 17.04, Intel(R) Core(TM) i7-4770(4core, 8threads)

Running unit test fails with following error sometimes.

```
--- Running testGuideContextExample06
job2: I am a child of the request coroutine
job1: I have my own context and execute independently!
[V: Time = 500 ms]
[V: Time = 1000 ms]
job1: I am not affected by cancellation of the request
[V: Time = 1500 ms]
main: Who has survived request cancellation?
--- shutting down
--- done

org.junit.ComparisonFailure: Line 1 
Expected :job1: I have my own context and execute independently!
Actual   :job2: I am a child of the request coroutine
 <Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:115)
	at guide.test.TestUtilKt.verifyCommonLines(TestUtil.kt:279)
	at guide.test.TestUtilKt.verifyCommonLines$default(TestUtil.kt:274)
	at guide.test.TestUtilKt.verifyLines(TestUtil.kt:291)
	at guide.test.GuideTest.testGuideContextExample06(GuideTest.kt:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by anolivetree** [comment]
I've run the test 20 times. No error has occurred after the fix.
