### ISSUE TITLE
Provide meaningful stacktrace on cancellation

### ISSUE THREAD

**Issue by vlsi** [Kotlin/kotlinx.coroutines#1625]
Sample: https://stackoverflow.com/questions/58482407/is-there-a-way-to-understand-what-the-coroutine-was-doing-when-it-was-cancelled

```kotlin
import kotlinx.coroutines.*

suspend fun test() {
    println("test.begin")
    delay(5000)
    println("test.end")
}

suspend fun proxy() {
    test()
}

fun main() {
    runBlocking {
        withTimeout(100) {
            proxy()
        }
    }
}
```

Output:

```
Exception in thread "main" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 100 ms
 at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException (Timeout.kt:126) 
 at kotlinx.coroutines.TimeoutCoroutine.run (Timeout.kt:92) 
 at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run (EventLoop.common.kt:491) 
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent (EventLoop.common.kt:270) 
 at kotlinx.coroutines.DefaultExecutor.run (DefaultExecutor.kt:68) 
 at java.lang.Thread.run (Thread.java:745) 
```

Note: neither `test` nor `proxy` nor `main` are mentioned in the stack trace.

Expected: "at least `test`" should be mentioned (because the coroutine resumes from that function). Ideally, `proxy` and `withTimeout` should be present as well.

As far as I see, Kotlin-JVM generates state machine like

```
var6_4 = IntrinsicsKt.getCOROUTINE_SUSPENDED();
switch ($continuation.label) {
    case 0: {
        ResultKt.throwOnFailure((Object)$result);
        var2_5 = "test.begin";
```

What if it added and extra string parameter to `throwOnFailure` method like
`ResultKt.throwOnFailure((Object)$result, "com.acme.Example.test(Example.kt:15)");` ?

Then failure cases could contain proper stacktraces for cancelation / exceptional outcomes.

**Comment by fvasco** [comment]
That string should be removed by shrinkers/obfuscators.

**Comment by qwwdfsad** [comment]
Unfortunately, we cannot provide **generic** mechanism that will always properly recover a stacktrace.
For example your proposal
>ResultKt.throwOnFailure((Object)$result, "com.acme.Example.test(Example.kt:15)"); 

is quite hard to implement, because `$result` already has an instance of the exception (potentially shared!)

>Expected: "at least test" should be mentioned (because the coroutine resumes from that function).

True, but the exception is created not in a resumption point

To improve the debugging experience, we have a [debug mode](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#debug-mode) that copies an exception and enhance the copy with coroutine-related frames.
Debug mode can be enabled by `-ea` VM option or corresponding VM property.

Unfortunately, `TimeoutException` cannot be recovered yet (I will fix it in the next release), but debug mode can be demonstrated with `CE` anyway, e.g. the following code

```
suspend fun test() {
    println("test.begin")
    suspendCancellableCoroutine<Unit> {
        thread {
            Thread.sleep(100)
            it.cancel()
        }
    }
    println("test.end")
}

suspend fun proxy() {
    test()
    println("Proxy.end") // Prevent tail-call optimization by kotlinc
}

fun main() {
    runBlocking {
        proxy()
    }
}
```

will produce
```
java.util.concurrent.CancellationException: Continuation CancellableContinuation(DispatchedContinuation[BlockingEventLoop@124ca831, Continuation at kotlinx.coroutines.AsyncJvmTest.test(AsyncJvmTest.kt:38)@e0cfd13]){Active}@7053d0dc was cancelled normally
	(Coroutine boundary)
	at kotlinx.coroutines.AsyncJvmTest.test(AsyncJvmTest.kt:38)
	at kotlinx.coroutines.AsyncJvmTest.proxy(AsyncJvmTest.kt:25)
	at kotlinx.coroutines.AsyncJvmTest$main$1.invokeSuspend(AsyncJvmTest.kt:33)
Caused by: java.util.concurrent.CancellationException: Continuation CancellableContinuation(DispatchedContinuation[BlockingEventLoop@124ca831, Continuation at kotlinx.coroutines.AsyncJvmTest.test(AsyncJvmTest.kt:38)@e0cfd13]){Active}@7053d0dc was cancelled normally
	at kotlinx.coroutines.CancelledContinuation.<init>(CompletedExceptionally.kt:51)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:168)
	at kotlinx.coroutines.CancellableContinuation$DefaultImpls.cancel$default(CancellableContinuation.kt:118)
```
