### ISSUE TITLE
Default value of a multiplatform function parameter is ignored in `runBlocking`

### ISSUE THREAD

**Issue by wild-lynx** [Kotlin/kotlinx.coroutines#1647]
```
// common code
expect suspend fun someFun(param: String = "default value")

// JVM target
actual suspend fun someFun(param: String) {
    println("Received parameter: $param")
}

fun main() {
    runBlocking {
        someFun()
    }
}
```

On `main` run, there is the exception: 

> Exception in thread "main" java.lang.NoSuchMethodError: sample.SampleJvmKt.someFun$default(Ljava/lang/String;Lkotlin/coroutines/Continuation;ILjava/lang/Object;)Ljava/lang/Object;
	at sample.SampleJvmKt$main$1.invokeSuspend(SampleJvm.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at sample.SampleJvmKt.main(SampleJvm.kt:22)
	at sample.SampleJvmKt.main(SampleJvm.kt)

If `someFun` is not `suspend`, it works just fine.

Reproduced both with `coroutines_version=1.3.2-1.3.60-eap-76` and `coroutines_version=1.3.2`, having Kotlin Gradle plugins `1.3.60-eap-76` and `1.3.50` correspondingly.

**Comment by elizarov** [comment]
Seems to be a bug in Kotlin compiler. Can you, please, submit it to http://kotl.in/issue

**Comment by wild-lynx** [comment]
https://youtrack.jetbrains.com/issue/KT-34823

**Comment by qwwdfsad** [comment]
Please keep track there
