### ISSUE TITLE
Hard to debug stacktrace with exception thrown in `.onStart { .. }`

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1661]
My use case is that I disallow having 2 simultaneous subscriptions to a `Flow<T>`. So I create an API like this:

```kotlin
myFlow.singleCollector()
  .collect() // <-- I want a stracktrace that points here
```

Full source of this is:

```kotlin
/**
 * A [Flow] that can only have one active collector (subscription) at a time. After unsubscribing, you can subscribe to
 * again.
 *
 * This is useful if you are backing a Flow's state with a channel whose lifetime outlives the Flow's subscription, and
 * unsubscribing from the Flow should not close the backing channel
 *
 * @throws IllegalStateException when a second collector subscribes while there is already an active subscription
 *
 * @see [singleCollect] for a variant of this where `this` Flow can never be subscripted to again.
 */
fun <T> Flow<T>.singleCollector(): Flow<T> = SingleCollectFlow(
    this,
    allowResubscriptionAfterUnsubscribing = true,
    errorMessage = "`.singleCollector()` was used - this Flow cannot be subscribed to again while it already has an active subscription. Please unsubscribe the first flow before subscribing a second."
)
    .actual

/**
 * Throws an exception if the same instance of this flow is subscribed to twice.
 *
 * This is useful for a [Flow] backed by a [ReceiveChannel] instance, because that instance can only be subscribed to
 * once.
 *
 * If [allowResubscriptionAfterUnsubscribing] is `true`, then the delegate `Flow` can be subscribed to again, as long as it is never
 * subscribed to twice. If `false`, this is disallowing throwing an [IllegalStateException]
 */
internal class SingleCollectFlow<T>(
    delegate: Flow<T>,
    private val allowResubscriptionAfterUnsubscribing: Boolean,
    errorMessage: String
) {
    val isStarted = AtomicBoolean(false)

    val actual = delegate.onStart {
        check(!isStarted.getAndSet(true)) {
            errorMessage
        }
    }
        .onCompletion {
            if (allowResubscriptionAfterUnsubscribing) {
                isStarted.set(false)
            }
        }
}
```

Unfortunately, the exception message I get from this is hard to debug, because the `.singleCollect()` call is not part of the stacktrace. Example stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: com.example.sample.debug, PID: 5851
    java.lang.IllegalStateException: `.singleCollector()` was used - this Flow cannot be subscribed to again while it already has an active subscription. Please unsubscribe the first flow before subscribing a second.
        at com.example.extensions.internal.coroutines.SingleCollectFlow$actual$1.invokeSuspend(FlowExtensionsInternal.kt:160)
        at com.example.extensions.internal.coroutines.SingleCollectFlow$actual$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1.collect(SafeCollector.kt:126)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:232)
        at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source:1)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1.collect(SafeCollector.kt:128)
        at com.example.extensions.internal.coroutines.FlowExtensionsInternalKt$asFairChannel$1.invokeSuspend(FlowExtensionsInternal.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

What can I change to get the `.singleCollector()` call (`myFlow.singleCollector()`) to be part of the stacktrace?

EDIT: digging further into the stacktrace, it looks like because the `.combine()` operator uses a channel internally, that is the [`.collect()`](https://github.com/Kotlin/kotlinx.coroutines/blob/7f0da424ed98e3a30e0a7ca2daff33f9a9cdbf0c/kotlinx-coroutines-core/common/src/flow/internal/Combine.kt#L97) that gets reported to the stacktrace

**Comment by ZakTaccardi** [comment]
slack thread on this https://kotlinlang.slack.com/archives/C1CFAFJSK/p1574098033318800

**Comment by qwwdfsad** [comment]
Could you please provide a complete reproducer?

I've tried to trigger an exception using `singleCollector`, but received an exception which stacktrace contains both `collect` call site (the one you marked as "<-- I want a stracktrace that points here" and `SingleCollectFlow` (where `check` actually fails).
So in your case probably more complex/suspending operators are involved

**Comment by qwwdfsad** [comment]
Closing, feel free to reopen if you still have this problem
