### ISSUE TITLE
callbackFlow unexpected CancellationException

### ISSUE THREAD

**Issue by Globegitter** [Kotlin/kotlinx.coroutines#1669]
We are having an application that is integrating with AWS Kinesis using the AWS Kinesis Client Library 2.2.6 and we are making use of `callbackFlow` to turn the Kinesis `RecordProcessor` into a flow which is then consumed by the rest of the application. Occasionally the whole application stops due to a `CancellationException` and it does not seem clear to me why it is being cancelled or what the cause of it is.

To show a simplified code snippet of the setup:

```
fun run(): Flow<...> = callbackFlow {
// some kinesis config & setup code
...
      // This factory just creates a new RecordProcessor with the channel provided here
      val recordProcessorFactory = RecordProcessorFactory(this)
...
       // scheduler is provided by the AWS Kinesis library
        val schedulerThread = Thread(scheduler)
        schedulerThread.isDaemon = true
        schedulerThread.start()
        awaitClose {
            logger.info { "Kinesis client's channel has been closed. The flow will cease to emit items." }
        }
}

internal class RecordProcessor(
    private val channel: SendChannel<...>
) : ShardRecordProcessor {
...
    override fun processRecords(processRecordsInput: ProcessRecordsInput) {
        try {
            processRecordsInput.records().forEach { record ->
                runBlocking { channel.send(Ok(pipelineData)) }
            }
        }  catch (t: Throwable) {
               logger.error(t) { "Some extra logs" } 
               Runtime.getRuntime().halt(1)
        }
    }
}
```

And this is the error that is getting logged from the try/catch above:
```
java.util.concurrent.CancellationException: Channel was consumed, consumer had failed
at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:33) ~[app-all.jar:?]
at kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt.cancelConsumed(Channels.common.kt:118) ~[app-all.jar:?]
at kotlinx.coroutines.channels.ChannelsKt.cancelConsumed(Unknown Source) ~[app-all.jar:?]
at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAll(Channels.kt:62) ~[app-all.jar:?]
at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source) ~[app-all.jar:?]
at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAll$1.invokeSuspend(Channels.kt) ~[app-all.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[app-all.jar:?]
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) ~[app-all.jar:?]
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270) ~[app-all.jar:?]
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79) ~[app-all.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54) ~[app-all.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[app-all.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36) ~[app-all.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[app-all.jar:?]
at package.name.app.App.main(App.kt:30) ~[app-all.jar:?]
```

Could this be an issue with the callbackFlow, as it still is marked experimental? Is there any way how I could debug this further to find what exactly is cancelling this coroutine? And what does ` Channel was consumed, consumer had failed` even mean?

**Comment by Globegitter** [comment]
Not a 100% confirmed yet but maybe there was just some issue around some stacktraces not showing completely. Sometimes there where further underlying stacktraces being shown indicating connection failures to some of the external services. This have been fixed and the the app has been running stable since then.
