### ISSUE TITLE
Flow catch not work

### ISSUE THREAD

**Issue by turingking** [Kotlin/kotlinx.coroutines#1712]
```
import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.flowOf

class MainActivity : AppCompatActivity() {
    val liveData = MutableLiveData<Int>()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        GlobalScope.launch {
            test()
        }

    }

    fun test() = runBlocking {
        liveData.lastValue()
            .catch { println("catch = "+it.message) }
            .collect { println("collect = $it") }
    }
}


suspend fun <T> LiveData<T>.lastValue(): Flow<T> = flowOf(withContext(Dispatchers.Main) { value!! })



fun Any.println(msg: String) {
    Log.e("MainActivity " + Thread.currentThread().name, msg)
}
```

error info :
```
2019-12-16 17:14:07.371 26746-26777/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.example.myapplication, PID: 26746
    kotlin.KotlinNullPointerException
        at com.example.myapplication.MainActivityKt$lastValue$2.invokeSuspend(MainActivity.kt:31)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6388)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```

**Comment by qwwdfsad** [comment]
It is because `flowOf(withContext(Dispatchers.Main) { value!! })` is not doing what you expect.
It is the same as
```
val value = withContext(Dispatchers.Main) { value!! } // NPE is thrown here
flowOf(value)
```
The value is being computed not at the moment of flow collection, but at the moment of flow creation.
You have to use `flow` builder instead:
```
flow {
    val value = withContext(Dispatchers.Main) {
       ...
    }
    emit(value)
}
```

**Comment by turingking** [comment]
thank you very much @qwwdfsad
