### ISSUE TITLE
Application crash while opening plaid button screen

### ISSUE THREAD

**Issue by kanji-keraliya** [Kotlin/kotlinx.coroutines#1734]
Application crash when I open page contain plaid button

`
"react-native": "0.61.5",
 "react-native-plaid-link-sdk": "^2.0.4",
`

`2019-12-24 19:37:15.879 17221-17287/com.anchorusd E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.anchorusd, PID: 17221
    java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.anchorusd-S6BdJ2myTkrCxkc8Tmdafg==/base.apk:classes23.dex)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:91)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:74)
        at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:43)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:75)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by qwwdfsad** [comment]
What makes you think this is a `kotlinx.coroutines`-specific issue?

**Comment by kanji-keraliya** [comment]
Sorry by mistake post in this repository instead of plaid
