### ISSUE TITLE
cleanupTestCoroutines does not detect awaiting CompletableDeferred

### ISSUE THREAD

**Issue by mhernand40** [Kotlin/kotlinx.coroutines#1749]
Please see the following test:
```Kotlin
@ExperimentalCoroutinesApi
class Repro {

    private val scope = TestCoroutineScope()
    private val subject = Subject(scope)

    @After
    fun tearDown() {
        scope.cleanupTestCoroutines()
    }

    @Test
    fun `test with delay`() {
        subject.launchCoroutineWithDelay(delayMillis = 5L)

        assertNull(subject.result)
    }

    @Test
    fun `test with CompletableDeferred`() {
        val deferred = CompletableDeferred<String>()
        subject.launchCoroutineAndAwait(deferred)

        assertNull(subject.result)
    }
}

class Subject(private val scope: CoroutineScope) {
    var result: String? = null

    fun launchCoroutineWithDelay(delayMillis: Long) {
        scope.launch {
            delay(timeMillis = delayMillis)
            result = "Result"
        }
    }

    fun launchCoroutineAndAwait(deferred: Deferred<String>) {
        scope.launch {
            result = deferred.await()
        }
    }
}
```

When I run the test class, only `test with delay` fails with:
```
kotlinx.coroutines.test.UncompletedCoroutinesError: Unfinished coroutines during teardown. Ensure all coroutines are completed or cancelled by your test.
	at kotlinx.coroutines.test.TestCoroutineDispatcher.cleanupTestCoroutines(TestCoroutineDispatcher.kt:178)
	at kotlinx.coroutines.test.TestCoroutineScopeImpl.cleanupTestCoroutines(TestCoroutineScope.kt:35)
```

However, `test with CompletableDeferred` passes even though the `CompletableDeferred` is never completed nor cancelled. Is this considered an undetected leak in the test?

**Comment by StolarczykJakub** [comment]
This may help.
https://proandroiddev.com/eliminating-coroutine-leaks-in-tests-3af825e7cde2
