### ISSUE TITLE
`WithTimeoutOrNullTest.testOuterTimeout` failed

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.coroutines#1787]
Happened only once (Windows, JDK 11). I couldn't reproduce it on Linux, running in a `repeat (1000) { }`. https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxCoroutines_Jdk11BuildWindows/2756986?mode=branches
```
java.lang.IllegalStateException: Executed: 3 times
	at kotlinx.coroutines.TestBase.makeError(TestBase.kt:73)
	at kotlinx.coroutines.TestBase.error(TestBase.kt:69)
	at kotlinx.coroutines.TestBase.error$default(TestBase.kt:68)
	at kotlinx.coroutines.WithTimeoutOrNullTest$testOuterTimeout$1.invokeSuspend(WithTimeoutOrNullTest.kt:143)
```

**Comment by elizarov** [comment]
It seems to be happening because our windows agents are very slow sometimes. I really don't know what else we can do to fix it.
