### ISSUE TITLE
flow {} does not allow passing of reified Type parameters

### ISSUE THREAD

**Issue by jensbaitingerbosch** [Kotlin/kotlinx.coroutines#1859]
I wanted to create a client for a paged rest API (for [Bitbucket](https://docs.atlassian.com/bitbucket-server/rest/7.0.1/bitbucket-rest.html#paging-params)) using Ktor Client . Each GET request returns N elements and you continue then on the N+1th element in your next request. To abstract the paging of type <T>, I wanted to provide a flow of <T>.

Here is my simplified example: 

```
suspend fun main() {
  HttpClient(Apache) {
   // ...
   }.use { client ->
     client.getPaged<Repository>("someUrl").collect{ println(it) }
   }
}   

inline fun <reified T> HttpClient.getPaged(url: String) = flow {

    var start = 0
    do {
        val page = get<PagedResult<T>>("$url?start=$start")

        page.values.forEach { emit(it) }
        start = page.nextPageStart
    } while (!page.isLastPage)
}
```

The issue is get<T> is an inline function with a reified Type <T> and when I call it the following exception is thrown:

```
Exception in thread "main" java.lang.UnsupportedOperationException: This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
	at kotlin.jvm.internal.Intrinsics.throwUndefinedForReified(Intrinsics.java:202)
	at kotlin.jvm.internal.Intrinsics.throwUndefinedForReified(Intrinsics.java:196)
	at kotlin.jvm.internal.Intrinsics.reifiedOperationMarker(Intrinsics.java:206)
	at com.....MainKt$getPaged$1.invokeSuspend(Main.kt:86)
	at com.....MainKt$getPaged$1.invoke(Main.kt)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$2.collect(SafeCollector.kt:126)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.kt:127)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.kt:127)
	at com.....MainKt.main(Main.kt:73)
	at com.....MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at com.....MainKt.main(Main.kt)
```

This is not intuitive, especially since this an exception that is only thrown at Runtime and not while compiling

here is the model:
```
import kotlinx.serialization.Serializable

@Serializable
data class PagedResult<T>(
    val size: Int,
    val limit: Int,
    val isLastPage: Boolean,
    val values: List<T>,
    val start: Int,
    val nextPageStart: Int
)

@Serializable
data class Repository(
    var slug: String
)
```

**Comment by elizarov** [comment]
Thanks. This is a bug in Kotlin compiler. I've reported it here: https://youtrack.jetbrains.com/issue/KT-37425 Please, track the corresponding issue.
