### ISSUE TITLE
Using ticker() causes NoSuchMethodError

### ISSUE THREAD

**Issue by DRSchlaubi** [Kotlin/kotlinx.coroutines#1867]
Code:
```kotlin
    @OptIn(ObsoleteCoroutinesApi::class)
    private val channel = ticker(TimeUnit.SECONDS.toMillis(30), 0)
    private val executor = DefaultThreadFactory.newSingleThreadExecutor("GameAnimator").asCoroutineDispatcher()

    /**
     * Starts the game animation.
     */
    fun start() {
        GlobalScope.launch(executor) {
            for (unit in channel) {
                animate()
            }
        }
    }
```
Error:
```text
Exception in thread "GameAnimator-pool-3-thread-1" java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.channels.ChannelIterator.next()'
        at com.github.seliba.devcordbot.core.GameAnimator$start$1.invokeSuspend(GameAnimator.kt:44)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```
This error only seems to occourr on Linux-based systems (Ubuntu 18.04 & Debian 9 for me)

**Comment by elizarov** [comment]
What version of Kotlin and `kotlinx.coroutines` libraries are you using?

**Comment by DRSchlaubi** [comment]
1.3.4

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer?
Does this problem reproduce regularly or only a specific project?

**Comment by DRSchlaubi** [comment]
I just made a plain project and could not reproduce it in that specific project

**Comment by qwwdfsad** [comment]
Closing as outdated
