### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/coroutines/AbstractCoroutineContextKey when running Spring tests with kotlin coroutines version 1.3.5

### ISSUE THREAD

**Issue by ErolPeel** [Kotlin/kotlinx.coroutines#1879]
Hi!

I have upgraded to Kotlin coroutines version 1.3.5.
Now I am getting this error when running my Spring Boot tests:
```
2:04:32.496 [boundedElastic-1] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: kotlin/coroutines/AbstractCoroutineContextKey
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at kotlinx.coroutines.CoroutineDispatcher.<clinit>(CoroutineDispatcher.kt)
	at kotlinx.coroutines.CoroutineContextKt.createDefaultDispatcher(CoroutineContext.kt:23)
	at kotlinx.coroutines.Dispatchers.<clinit>(Dispatchers.kt:33)
	at org.springframework.web.reactive.function.server.CoRouterFunctionDsl$asHandlerFunction$1.handle(CoRouterFunctionDsl.kt:598)
	at org.springframework.web.reactive.function.server.support.HandlerFunctionAdapter.handle(HandlerFunctionAdapter.java:61)
	at org.springframework.web.reactive.DispatcherHandler.invokeHandler(DispatcherHandler.java:161)
	at org.springframework.web.reactive.DispatcherHandler.lambda$handle$1(DispatcherHandler.java:146)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
```
When I downgrade to version 1.3.3 everything is OK again. 1.3.4 also results in this error.
How can I solve this problem?
Greetings
Erol

**Comment by elizarov** [comment]
Please, try updating Kotlin to 1.3.70, too. Does it help?

**Comment by ErolPeel** [comment]
> Please, try updating Kotlin to 1.3.70, too. Does it help?

Thank you, that worked.

**Comment by ErolPeel** [comment]
> Please, try updating Kotlin to 1.3.70, too. Does it help?

Thank you, that worked.
