### ISSUE TITLE
CompletedContinuation cannot be cast to DispatchedContinuation

### ISSUE THREAD

**Issue by andreimesina** [Kotlin/kotlinx.coroutines#1909]
Hello, on the Android platform I use a `callbackFlow` to emit some data, and I collect the data inside a viewmodel. If I try to call `delay(timeMillis: Long)` inside the `flow.collect` operator, I encounter the following exception:

```
2020-04-08 18:29:10.840 10163-10163/app.package E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:94)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:173)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:305)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:315)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by andreimesina** [comment]
After keeping the exact same code, but moving the `delay` into a separate `suspend` function, and then calling that function instead of directly calling `delay`, I got the following stacktrace:

```
2020-04-08 19:34:14.654 13246-13246/app.package E/AndroidRuntime: FATAL EXCEPTION: main
    kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Main [immediate], Continuation at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAll(Channels.kt:45)@30ba6c2]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
        at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:320)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at app.package.ViewModel.<init>(ViewModel.kt:104)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at app.package.Activity.onCreate(Activity.kt:28)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:94)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68) 
        at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:320) 
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26) 
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109) 
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54) 
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) 
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1) 
        at app.package.ViewModel.<init>(ViewModel.kt:104) 
        at java.lang.Class.newInstance(Native Method) 
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219) 
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41) 
        at app.package.Activity.onCreate(Activity.kt:28) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by elizarov** [comment]
What version of `kotlinx.coroutines` are you using? Can you create a small self-contained reproducer or is it only shows as a part of a big project?

**Comment by elizarov** [comment]
Please, see if upgrading the most recent version (`1.3.5` help).

**Comment by andreimesina** [comment]
I was using `1.3.3` at the time of posting this issue. Now I've just upgraded to `1.3.5`, and I get the same initial exception (`java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation`). 

It is happening inside a small sample project, so there's just a simple `callbackFlow` that sends some items and a `collect` operator with a `delay` call inside it.

**Comment by elizarov** [comment]
Can you post a reproducer, please?

**Comment by andreimesina** [comment]
I've just added [this repository](https://github.com/andreimesina/KotlinFlowDelayReproducer/tree/master) in which I tried to reproduce the issue above.

The interesting fact is that this reproducer project does not fail, but when I add the same `Activity`-`ViewModel` pair to a bigger existing project, it fails with the original exception that I've posted. The `coroutines` version is also the same in both projects.

**Comment by elizarov** [comment]
Can you, please, check the actual versions of all the kotlin libraries that go into your project with `gradlew dependencies`.

**Comment by andreimesina** [comment]
Hey, sorry for the late reply. Seems like updating the Kotlin dependency 
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin"`
 version from `1.3.30` to the current `1.3.71` fixed the problem. Thanks for the support!

**Comment by yvolk** [comment]
I'm observing the same exception on Android in kotlinx-coroutines-core-jvm-1.4.1.jar

I got this error myself once and two of not many (yet :-) ) users of my [Open source app](https://github.com/andstatus/game2048/blob/master/README.md#readme) reported this. Obviously the problem occurs relatively seldom, so I will think about some automated playing test to reproduce this...

```
2020-12-04 16:53:10.264 24118-24137/org.andstatus.game2048 E/AndroidRuntime: FATAL EXCEPTION: GLThread 8681
    Process: org.andstatus.game2048, PID: 24118
    kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[GameWindowCoroutineDispatcher, Continuation at com.soywiz.korge.tween.TweenKt$tween$3.invokeSuspend(tween.kt:149)@e8be942]){CompletedContinuation(result=kotlin.Unit, cancelHandler=InvokeOnCancel[@db09d53], onCancellation=null, idempotentResume=null, cancelCause=kotlinx.coroutines.JobCancellationException: TimeoutCoroutine has completed normally; job=TimeoutCoroutine(timeMillis=374){Completed}@5547690)}@4768b89. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:106)
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:383)
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0(GameWindow.kt:316)
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0$default(GameWindow.kt:313)
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:310)
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:81)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
     Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:226)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:106) 
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:383) 
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0(GameWindow.kt:316) 
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0$default(GameWindow.kt:313) 
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:310) 
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:81) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259) 
```
