### ISSUE TITLE
AbstractCoroutineContextKey Error 

### ISSUE THREAD

**Issue by shantanu10** [Kotlin/kotlinx.coroutines#1913]
I am simply using a function in the following form:
`fun someMethod() = runBlocking {
     ..... // some code
      launch {
          callSomeMethod()
    }
   ..... // some code
}`

**Package Info:**

- kotlinVersion = '1.3.61'
- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'

I am getting following error:

`kotlin/coroutines/AbstractCoroutineContextKey
java.lang.NoClassDefFoundError: kotlin/coroutines/AbstractCoroutineContextKey
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at kotlinx.coroutines.CoroutineDispatcher.<clinit>(CoroutineDispatcher.kt)
	at kotlinx.coroutines.EventLoopKt.createEventLoop(EventLoop.kt:26)
	at kotlinx.coroutines.ThreadLocalEventLoop.getEventLoop$kotlinx_coroutines_core(EventLoop.common.kt:126)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:43)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
.........
.........
Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.AbstractCoroutineContextKey
`

**Comment by qwwdfsad** [comment]
kotlinx-coroutines-core `1.3.5` is, unfortunately, compatible only with Kotlin 1.3.70+

**Comment by shantanu10** [comment]
Thanks, worked.

**Comment by romrell4** [comment]
I'm having this same issue, but using Kotlin 1.4.0 and coroutines 1.3.9... Any ideas?

**Comment by elizarov** [comment]
Please, check the versions of the dependencies you use with `gradlew dependencies` and make sure you indeed use Kotlin 1.4.0 and coroutines 1.3.9.
