### ISSUE TITLE
can not compile suspended inline extension function in object class when java functional interface is invoked

### ISSUE THREAD

**Issue by ftong2010** [Kotlin/kotlinx.coroutines#1962]
when using kotlin 1.3.72 with coroutine 1.3.5, if I try to create a extension function within an object, 

```
object DummyUtil {
    suspend inline fun DummyClass.nestedCall(
        context: CoroutineContext = Dispatchers.IO,
        crossinline action: () -> Unit
    ): Unit = withContext(context) {
        this@nestedCall.doAction {
            action()
        }
    }
}

```

the compiler will throw following exception:
```
java.lang.UnsupportedOperationException: Don't know how to generate outer expression: Class: class DummyUtil
        at org.jetbrains.kotlin.codegen.context.CodegenContext.getOuterExpression(CodegenContext.java:219)
        at org.jetbrains.kotlin.codegen.context.CodegenContext.lookupInContext(CodegenContext.java:560)
        at org.jetbrains.kotlin.codegen.context.MethodContext.lookupInContext(MethodContext.java:83)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.findCapturedValue(ExpressionCodegen.java:1976)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.findLocalOrCapturedValue(ExpressionCodegen.java:1967)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.getContinuationParameterFromEnclosingSuspendFunctionDescriptor(ExpressionCodegen.java:2466)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.getContinuationParameterFromEnclosingSuspendFunction(ExpressionCodegen.java:2457)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.prepareCoroutineArgumentForSuspendCall(ExpressionCodegen.java:2407)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeFunction(ExpressionCodegen.java:2376)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeFunction(ExpressionCodegen.java:2368)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:2280)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:112)
        at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:304)
        ... 115 more

```

[here](https://github.com/ftong2010/OutClassGenerationIssueDemo) is a minimal project that can reproduce this issue. 

Do notice that this issue only occurs when java class are invovled. When I try to isolate the issue, I found that kotlin classes and lamdas are not affected by this issue.

My current work round is to move this extension function to top level(file level), and it works just fine.

**Comment by elizarov** [comment]
Thanks for the detailed report. I've reported the corresponding compiler bug: https://youtrack.jetbrains.com/issue/KT-38630
