### ISSUE TITLE
Unhandled Exceptions Getting Eaten

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#1970]
We are trying to debug some odd behavior that we are seeing in our application. While trying to reproduce an issue small-scale, we found this bug instead.

For the given code, we would expect 3 unhandled exceptions, but we are only seeing 2. One is getting eaten.

```
private fun testCoroutines() {
  val logger = Logger("TestCoroutine")

  val scope: CoroutineScope = GlobalScope +
      NonCancellable +
      Executors.newSingleThreadExecutor().asCoroutineDispatcher() +
      CoroutineExceptionHandler { coroutineContext, throwable ->
        logger.i("Unhandled Exception:", t = throwable)
      }

  var authDeferred: Deferred<String>? = null

  suspend fun test(): String {
    while (true) {
      val result: String? = try {
        authDeferred?.await()
      } catch (e: Exception) {
        null
      }

      if (result == null && authDeferred == null) {
        // No current running requests, so let's run our own.
        break
      } else if (result == "Success") {
        // No need to try to authorize now, as we successfully logged in
        return result
      }
    }

    val deferred = scope.async { async { throw RuntimeException("401") }.await() }
    authDeferred = deferred
    try {
      return deferred.await()
    } finally {
      authDeferred = null
    }
  }

  fun launchTest(num: Int) {
    scope.launch {
      logger.i("Run $num Start")
      test()
      logger.i("Run $num End")
    }
  }
  launchTest(1)
  launchTest(2)
  launchTest(3)
}
```

 My output:
```
2020-04-28 15:36:11.746 21406-21520/com.rally.coach.internal.debug I/TestCoroutine: Run 1 Start
2020-04-28 15:36:11.749 21406-21520/com.rally.coach.internal.debug I/TestCoroutine: Run 2 Start
2020-04-28 15:36:11.759 21406-21520/com.rally.coach.internal.debug I/TestCoroutine: Run 3 Start
2020-04-28 15:36:11.770 21406-21520/com.rally.coach.internal.debug I/TestCoroutine: Unhandled Exception:
    java.lang.RuntimeException: 401
        at com.rally.coach.base.MainActivityKt$testCoroutines$1$deferred$1$1.invokeSuspend(MainActivity.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-04-28 15:36:11.777 21406-21520/com.rally.coach.internal.debug I/TestCoroutine: Unhandled Exception:
    java.lang.RuntimeException: 401
        at com.rally.coach.base.MainActivityKt$testCoroutines$1$deferred$1$1.invokeSuspend(MainActivity.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by elizarov** [comment]
How do you run it? I'm seeing all three unhandled exceptions. Could be the case that whatever test framework you are using simply exists before the last one gets a chance to be printed?

**Comment by ScottPierce** [comment]
I'm running it in an Android app in the onCreate of the MainActivity. It repros 100% of the time for me. The application isn't crashing or anything either, so it should have ample time to complete. We found this while trying to reproduce a super tricky issue in production.

Here is the same android code using the Android Logger, instead of our mpp implementation that wraps the android logger. Same result:
```Kotlin
private fun testCoroutines() {
  val TAG = "TestCoroutine"

  val scope: CoroutineScope = GlobalScope +
      NonCancellable +
      Executors.newSingleThreadExecutor().asCoroutineDispatcher() +
      CoroutineExceptionHandler { coroutineContext, throwable ->
        Log.i(TAG, "Unhandled Exception:", throwable)
      }

  var authDeferred: Deferred<String>? = null

  suspend fun test(): String {
    while (true) {
      val result: String? = try {
        authDeferred?.await()
      } catch (e: Exception) {
        null
      }

      if (result == null && authDeferred == null) {
        // No current running requests, so let's run our own.
        break
      } else if (result == "Success") {
        // No need to try to authorize now, as we successfully logged in
        return result
      }
    }

    val deferred = scope.async { async { throw RuntimeException("401") }.await() }
    authDeferred = deferred
    try {
      return deferred.await()
    } finally {
      authDeferred = null
    }
  }

  fun launchTest(num: Int) {
    scope.launch {
      Log.i(TAG, "Run $num Start")
      test()
      Log.i(TAG, "Run $num End")
    }
  }
  launchTest(1)
  launchTest(2)
  launchTest(3)
}
```

**Comment by fvasco** [comment]
> We found this while trying to reproduce a super tricky issue in production.

I suspect that the solution of your problems isn't in this library.

**Comment by ScottPierce** [comment]
@fvasco Actually - the issue we're seeing is that all jobs run on a scope are throwing cancellation exceptions. It's super tricky to reproduce, and every time we think we've fixed it we find a way to make it happen again. It 100% has to do with a bug in this library, or a bug in how we're using it.

**Comment by ScottPierce** [comment]
I've had some other people at my company attempt to repro based on the instructions above. Their results:

>Yep I only get 2 exceptions in my logs as well, but when I try by adding some more it works I get 5 errors back when I do this:
```
launchTest(1)
launchTest(2)
launchTest(3)
launchTest(4)
launchTest(5)
```
>same if I just do 2 and 1 I get all the errors

**Comment by fvasco** [comment]
In your last example, you launched `test` many times, and test performs an unsynchronized access to `authDeferred`, this looks wrong to me.

Whatever is your bug, it is really hard to me understand how your example should works.

**Comment by ScottPierce** [comment]
@fvasco Everything is running inside of `scope`, which only has a single thread: `Executors.newSingleThreadExecutor().asCoroutineDispatcher()`.

This code is adapted from our auth code where we ensure that we have only a single auth request running at a time, and we keep a `Deferred` handy to keep track of any currently running auth requests.

**Comment by fvasco** [comment]
@ScottPierce,
a single thread does not mean nothing, unless you remove the `suspend` keyword from the `test` function.

**Comment by ScottPierce** [comment]
> a single thread does not mean nothing

Tell that to Kotlin/native :P

Interesting point though. If I pull `authDeferred` out of the function, into a volatile member variable, I can still reproduce the missing exception.

```
@Volatile var authDeferred: Deferred<String>? = null
```

I tried a few other things that resulted in me getting all 3 exceptions though, like running the entire `testCoroutines()` function from the same thread that is owned by `scope`.

**Comment by fvasco** [comment]
Hi, @ScottPierce,
you can remove the `@Volatile`, it does not fix the issue.

Please consider to put `authDeferred` in a [`ResouceMutex`](https://github.com/Kotlin/kotlinx.coroutines/issues/1382) (or use a [`Mutex`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-mutex/index.html))

**Comment by Dico200** [comment]
Agreed with @fvasco . The fact there is a single thread here does not mean it is thread safe. There are 2 pieces of code that the thread can choose to run at a given moment and it's not clear which one it will choose when it suspends.

**Comment by Dico200** [comment]
I suggest you add a `println` before throwing the error. That way you can verify how many errors actually get thrown versus how many get printed.
