### ISSUE TITLE
Sample code snippet cannot run to expected result

### ISSUE THREAD

**Issue by CarterChen247** [Kotlin/kotlinx.coroutines#1997]
When I copy the sample code from the example of chapter **[Transform operator](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/flow.md#transform-operator)**   and runs it, it produces the following error:

```
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@606d8acf, Continuation at 5_flow/ExampleFlowOperatorTransformKt.performRequest(ExampleFlowOperatorTransform.kt:6)@2a33fae0]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.common.kt:224)
	at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:114)
	at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:108)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

My code is as same as one in the example:
```
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

suspend fun performRequest(request: Int): String {
    delay(1000) // imitate long-running asynchronous work
    return "response $request"
}

fun main() = runBlocking<Unit> {
    //sampleStart
    (1..3).asFlow() // a flow of requests
        .transform { request ->
            emit("Making request $request")
            emit(performRequest(request))
        }
        .collect { response -> println(response) }
//sampleEnd
}
```

**Comment by CarterChen247** [comment]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/flow.md#buffering this chapter cannot run to complete as well

**Comment by elizarov** [comment]
Can you, please, elaborate on how exactly you try to run it? Run fine for me, and all in playground: https://pl.kotl.in/HylkKFpKG

**Comment by CarterChen247** [comment]
Thank you for your help. The code runs properly on playground.

Here are my reproduction steps:

1. Open IntelliJ IDEA, 
```
IntelliJ IDEA 2018.3.2 (Community Edition)
Build #IC-183.4886.37, built on December 18, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

2. Create a Kotlin file which named `ExampleFlowOperatorTransform.kt`

3. Copy the full code from the [example].(https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/example-flow-09.kt) 

3. Run it, and I got the messages as following:
```
Making request 1
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@606d8acf, Continuation at 5_flow/ExampleFlowOperatorTransformKt.performRequest(ExampleFlowOperatorTransform.kt:12)@2a33fae0]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.common.kt:224)
	at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:114)
	at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:108)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at 5_flow.ExampleFlowOperatorTransformKt.main(ExampleFlowOperatorTransform.kt:17)
	at 5_flow.ExampleFlowOperatorTransformKt.main(ExampleFlowOperatorTransform.kt)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:103)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:38)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
	... 11 more
Exception in thread "main" java.lang.ClassCastException: kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to java.lang.String
	at 5_flow.ExampleFlowOperatorTransformKt$main$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:74)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:14)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:71)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:54)
	at 5_flow.ExampleFlowOperatorTransformKt$main$1$invokeSuspend$$inlined$transform$1$1.emit(Collect.kt:139)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$9.collect(SafeCollector.common.kt:115)
	at 5_flow.ExampleFlowOperatorTransformKt$main$1$invokeSuspend$$inlined$transform$1.invokeSuspend(Emitters.kt:182)
	at 5_flow.ExampleFlowOperatorTransformKt$main$1$invokeSuspend$$inlined$transform$1.invoke(Emitters.kt)
	at kotlinx.coroutines.flow.SafeFlow.collect(Builders.kt:56)
	at 5_flow.ExampleFlowOperatorTransformKt$main$1.invokeSuspend(ExampleFlowOperatorTransform.kt:31)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at 5_flow.ExampleFlowOperatorTransformKt.main(ExampleFlowOperatorTransform.kt:17)
	at 5_flow.ExampleFlowOperatorTransformKt.main(ExampleFlowOperatorTransform.kt)

Process finished with exit code 1
```

**Comment by elizarov** [comment]
How's your project setup? What version of libraries to you use?

**Comment by CarterChen247** [comment]
Kotlin version `v1.3.61-release-IJ2018.3-1`
Coroutines version `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5`

**Comment by elizarov** [comment]
How's you project is setup? Can you share it?

**Comment by CarterChen247** [comment]
I've prepared a repo here:
https://github.com/CarterChen247/KotlinCoroutineGuideFlowPart

`example-basic-01.kt` works just fine but `example-flow-09.kt` throws exception.

**Comment by elizarov** [comment]
Both work like a charm for me. There are two possible culprits I see (please, try the first one first):

1. Upgrade your Kotlin plugin to the recent version (`1.3.72`) and rebuild the project. See if it helps.

2. Maven cache somehow got corrupted and you have broken `.jar` files downloaded. Please, clean your `.m2/repository` folder (found inside your user-home) and then rebuild the project. See if it helps.

**Comment by CarterChen247** [comment]
Since I have trouble upgrading the Kotlin plugin in my IntelliJ, I uninstalled my IntelliJ and installed the latest version of IntelliJ from the JetBrains website. After doing this, the code works just fine.

I think there may be some compatibility problems in the older version of IntelliJ, and those problems can be solved by upgrade IntelliJ to the latest version. @elizarov Thank you for your kindly support 😄

**Comment by elizarov** [comment]
You are welcome.
