### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlinx.coroutines.EventLoopImplBase$DelayedTaskQueue

### ISSUE THREAD

**Issue by Palardin3** [Kotlin/kotlinx.coroutines#2100]
0
java.lang.NoClassDefFoundError: kotlinx.coroutines.EventLoopImplBase$DelayedTaskQueue
1
at kotlinx.coroutines.EventLoopImplBase.scheduleImpl(EventLoopImplBase.java:367)
2
at kotlinx.coroutines.EventLoopImplBase.schedule(EventLoopImplBase.java:354)
3
at kotlinx.coroutines.EventLoopImplBase.scheduleResumeAfterDelay(EventLoopImplBase.java:233)
4
at kotlinx.coroutines.DelayKt.delay(DelayKt.java:74)
_____________________________________________________

almost only on samsung mechines  and always commit some crash called “java.lang.NoClassDefFoundError”

**Comment by Palardin3** [comment]
kotlin_version 1.3.72

**Comment by Palardin3** [comment]
coroutines 1.3.5

**Comment by elizarov** [comment]
In what kind of project this problem shows up? Do you have a self-contained reproducer?
