### ISSUE TITLE
Very obscure error when not all subclasses of a sealed class are serializable

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#2160]
Run this code:

```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.*

@Serializable
sealed class Repository {
    abstract val name: String
}
            
// THIS IS NOT @Serializable
class SimpleRepository(override val name: String) : Repository()

@Serializable
class OwnedRepository(override val name: String, val owner: String) : Repository()

fun main() {
    val data: Repository = OwnedRepository("kotlinx.coroutines", "kotlin")
    println(Json.encodeToString(data))
}  
```

It results with a very obscure error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlinx.serialization.internal.PlatformKt.constructSerializerForGivenTypeArgs(Platform.kt:40)
	at kotlinx.serialization.internal.PlatformKt.compiledSerializerImpl(Platform.kt:23)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializerOrNull(Serializers.kt:109)
	at kotlinx.serialization.SerializersKt.serializerOrNull(Unknown Source)
	at example.examplePoly04.Example_poly_04Kt.main(example-poly-04.kt:23)
	at example.examplePoly04.Example_poly_04Kt.main(example-poly-04.kt)
Caused by: java.lang.IllegalArgumentException: Arrays of classes and serializers must have the same length, got arrays: [class example.examplePoly04.SimpleRepository, class example.examplePoly04.OwnedRepository], [example.examplePoly04.OwnedRepository$$serializer@281e3708]
Please ensure that @Serializable annotation is present on each sealed subclass
	at kotlinx.serialization.SealedClassSerializer.<init>(SealedSerializer.kt:96)
	at example.examplePoly04.Repository$Companion.serializer(example-poly-04.kt)
	... 10 more
```

Expected: It should either work or, at least, produce a human-friendly error message.

**Comment by elizarov** [comment]
Wrong repo
