### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by khovanskiy** [Kotlin/kotlinx.coroutines#2168]
The following code raises an exception at runtime:
```
class CoroutineBugTest {
    class Sample {
        suspend fun execute(batches: List<List<String>>) {
            for (batch in batches) {
                coroutineScope {
                    for (item in batch) {
                        launch {
                            // do nothing
                        }
                    }
                }
            }
        }
    }

    @Test
    fun test() = runBlocking {
        val sample = Sample()
        println(sample)
    }
}
```

**Exception:**
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    CoroutineBugTest$Sample.execute(Ljava/util/List;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; @128: invokespecial
  Reason:
    Type 'java/util/List' (current frame, stack[2]) is not assignable to 'kotlin/jvm/internal/Ref$ObjectRef'
  Current Frame:
    bci: @128
    flags: { }
    locals: { 'CoroutineBugTest$Sample', 'java/util/List', 'kotlin/coroutines/Continuation', 'java/util/List', 'java/util/Iterator', 'java/lang/Object', 'CoroutineBugTest$Sample$execute$1', 'java/lang/Object' }
    stack: { uninitialized 122, uninitialized 122, 'java/util/List', null }
  Bytecode:
    0000000: 2cc1 000b 9900 232c c000 0b3a 0619 06b4
    0000010: 000f 1210 7e99 0012 1906 59b4 000f 1210
    0000020: 64b5 000f a700 0ebb 000b 592a 2cb7 0014
    0000030: 3a06 1906 b400 183a 05b8 001e 3a07 1906
    0000040: b400 0faa 0000 00a4 0000 0000 0000 0001
    0000050: 0000 0015 0000 0070 1905 b800 242b b900
    0000060: 2a01 003a 0419 04b9 0030 0100 9900 7719
    0000070: 04b9 0033 0100 c000 264e bb00 3559 2d01
    0000080: b700 38c0 003a 1906 1906 2ab5 003d 1906
    0000090: 2bb5 0040 1906 2db5 0043 1906 1904 b500
    00000a0: 4619 0604 b500 0fb8 004c 5919 07a6 0032
    00000b0: 1907 b019 06b4 0046 c000 2c3a 0419 06b4
    00000c0: 0043 c000 264e 1906 b400 40c0 0026 4c19
    00000d0: 06b4 003d c000 024b 1905 b800 2419 0557
    00000e0: a7ff 85b2 0052 b0bb 0054 5912 56b7 0059
    00000f0: bf                                     
  Stackmap Table:
    same_frame(@39)
    full_frame(@50,{Object[#2],Object[#38],Object[#100],Top,Top,Top,Object[#11]},{})
    full_frame(@88,{Object[#2],Object[#38],Object[#100],Top,Top,Object[#4],Object[#11],Object[#4]},{})
    full_frame(@101,{Object[#2],Object[#38],Object[#100],Top,Object[#44],Object[#4],Object[#11],Object[#4]},{})
    full_frame(@179,{Object[#2],Object[#38],Object[#100],Top,Top,Object[#4],Object[#11],Object[#4]},{})
    full_frame(@223,{Object[#2],Object[#38],Object[#100],Object[#38],Object[#44],Object[#4],Object[#11],Object[#4]},{Object[#4]})
    full_frame(@227,{Object[#2],Object[#38],Object[#100],Top,Object[#44],Object[#4],Object[#11],Object[#4]},{})
    full_frame(@231,{Object[#2],Object[#38],Object[#100],Top,Top,Object[#4],Object[#11],Object[#4]},{})


	at CoroutineBugTest$test$1.invokeSuspend(CoroutineBugTest.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at CoroutineBugTest.test(CoroutineBugTest.kt:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Environment Details:**
* jdk version: javac 11.0.2
* kotlin version: 1.3.72
* kotlinx-coroutines version: 1.3.7

UPD: This code is also not working:
```
class CoroutineBugTest {
    class Sample {
        suspend fun execute(batches: Set<Any>) {
            for (batch in batches) {
                coroutineScope {
                    inner(batch)
                }
            }
        }

        private fun inner(batch: Any) {
        }
    }

    @Test
    fun test() = runBlocking {
        val sample = Sample()
        println(sample)
    }
}
```

**Comment by MikiLoz92** [comment]
happening to me as well

**Comment by istarion** [comment]
As I see, downgrade kotlinx-coroutines to v1.3.6 helps.

**Comment by qwwdfsad** [comment]
Unfortunately, this is a compiler bug, please see the comment https://github.com/Kotlin/kotlinx.coroutines/issues/2041#issuecomment-633271810 

As a workaround, it's possible to extract `coroutineScope` to a separate method:
```
class Sample {
    suspend fun execute(batches: List<List<String>>) {
        for (batch in batches) {
            separateMethod(batch)
        }
    }

    private suspend fun separateMethod(batch: List<String>) {
        coroutineScope {
            for (item in batch) {
                launch {
                    // do nothing
                }
            }
        }
    }
}
```
