### ISSUE TITLE
Not catching Exception in suspend function with Result<T> as return type

### ISSUE THREAD

**Issue by SteinerOk** [Kotlin/kotlinx.coroutines#2181]
I wrote a small piece of code to describe this problem:
```
fun main() = runBlocking<Unit> {
    println("Result: ${signInFlowStepFirst()}")
}

suspend fun signInFlowStepFirst(): Result<Unit> = try {
    val result = withContext(Dispatchers.IO) {
        if (true) throw Exception ("Request failed!")
    }
    Result.success(result)
} catch (e: Exception) {
    Result.failure(e)
}
```

When I run it on 1.3.72, I get the expected output in the console:
```
Result: Failure(java.lang.Exception: Request failed!)
```

But when I run it on 1.4.0-rc, I get the application crash with the specified error, but it is not caught, as expected:
```
Exception in thread "main" java.lang.Exception: Request failed!
	at ru.omnidesk.backend.api.service.EntrenceServiceTestKt$signInFlowStepFirst$result$1.invokeSuspend(EntrenceServiceTest.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
There is an assumption that this is due to the "withContext(Dispatchers.IO)" method, since if you remove it, then the behavior is as expected.

**Comment by qwwdfsad** [comment]
Thanks for the report!
It is indeed a major regression in Kotlin compiler, reported here: https://youtrack.jetbrains.com/issue/KT-40843
Will be fixed in 1.4 on the compiler side.
