### ISSUE TITLE
Kotlin Flow never collects info on unit testing

### ISSUE THREAD

**Issue by jclemus91** [Kotlin/kotlinx.coroutines#2189]
Could someone explain me why during unit testing, `departmentsUseCase.getDepartments()` that returns a kotlin flow, never calls `.collect{}` block code?

I have tried passing the dispatcher for `viewModelScope.launch(aDispatcherReceivedFromUnitTesting)` and even passing a `coroutineContext`.

My View Model:
```
private val _departments = MutableLiveData<List<DepartmentModel>>()
val departments: LiveData<List<DepartmentModel>> get() = _departments

private val _showErrorMessage = MutableLiveData<String>()
val showErrorMessage: LiveData<String> get() = _showErrorMessage

private val _showProgressBar = MutableLiveData<Boolean>()
val showProgressBar: LiveData<Boolean> get() = _showProgressBar


// This function is called from a Fragment and it works, but not on unit testing context completely
fun getDepartments() {
    viewModelScope.launch {
        departmentsUseCase.getDepartments()
            .onStart { _showProgressBar.value = true } // This block is executed on unit testing
            .onCompletion { _showProgressBar.value = false } // This block is executed on unit testing
            .collect {
                // This code block is never called on unit testing
                when (it) {
                    is Success -> _departments.value = it.value
                    is Failure -> _showErrorMessage.value = it.reason.message
                }
            }
    }
}
```

During the test case, it finishes as success, however, the observer change never happens. It seems test finishes before `.collect{ }` be executed.

My Test Case:
```
@Test
fun `my test`() {
    // Given
    whenever(departmentsStateUseCase.getDepartments()) doReturn flow { Success(listOf<DepartmentModel>()) }

    // When
    viewModel.getDepartments()
    
    // Then
    val observer = object : Observer<List<DepartmentModel>> {
        override fun onChanged(data: List<DepartmentModel>) {
            assertThat(data, IsEqual(listOf()))
            viewModel.departments.removeObserver(this)
        }
    }
    viewModel.departments.observeForever(observer)
}
```

I have other test implementation libraries, in deed. However I'm focusing on those:
```
"org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.8"
"com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
```
I'm not sure if I'm missing an additional line. I need to make sure `Flow` collects data to then test `LiveData` result.

Let me know if you require more useful information.

**Comment by qwwdfsad** [comment]
You probably have to replace `whenever(departmentsStateUseCase.getDepartments()) doReturn flow { Success(listOf<DepartmentModel>()) }` with either 
`whenever(departmentsStateUseCase.getDepartments()) doReturn flow { emit(Success(listOf<DepartmentModel>())) }`
 or 
`whenever(departmentsStateUseCase.getDepartments()) doReturn flowOf(Success(listOf<DepartmentModel>()))`

**Comment by jclemus91** [comment]
Oh, so simple. Thank you so much for your invested time. @qwwdfsad

**Comment by aligurelli** [comment]
@qwwdfsad you are the best!!!

> You probably have to replace `whenever(departmentsStateUseCase.getDepartments()) doReturn flow { Success(listOf<DepartmentModel>()) }` with either
> `whenever(departmentsStateUseCase.getDepartments()) doReturn flow { emit(Success(listOf<DepartmentModel>())) }`
> or
> `whenever(departmentsStateUseCase.getDepartments()) doReturn flowOf(Success(listOf<DepartmentModel>()))`

**Comment by saitej-janjirala** [comment]
I am getting this error Exception in thread "Test worker @coroutine#1" java.lang.NullPointerException: Cannot invoke "kotlinx.coroutines.flow.Flow.collect(kotlinx.coroutines.flow.FlowCollector, kotlin.coroutines.Continuation)"
	at com.saitejajanjirala.newsapp.presentation.MainViewModel$fetchHeadLines$1.invokeSuspend(MainViewModel.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.saitejajanjirala.newsapp.presentation.MainViewModel.fetchHeadLines(MainViewModel.kt:34)
	at com.saitejajanjirala.newsapp.presentation.MainViewModel.<init>(MainViewModel.kt:29)
	at com.saitejajanjirala.newsapp.presentation.MainViewModelTest.setUp(MainViewModelTest.kt:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(1), "coroutine#1":StandaloneCoroutine{Cancelling}@3701e6e4, Dispatchers.Main]

No value produced in 3s
app.cash.turbine.TurbineAssertionError: No value produced in 3s
	at app//app.cash.turbine.TurbineAssertionError$Companion.invoke(TurbineAssertionError.kt:32)
	at app//app.cash.turbine.ChannelKt.awaitEvent(channel.kt:89)
	at app//app.cash.turbine.ChannelKt$awaitEvent$1.invokeSuspend(channel.kt)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at app//kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
	at app//kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:322)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:310)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:160)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at app//com.saitejajanjirala.newsapp.presentation.MainViewModelTest.test updates items with success result(MainViewModelTest.kt:72)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Unknown Source)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: app.cash.turbine.TurbineTimeoutCancellationException: Timed out waiting for 3s
	at app//app.cash.turbine.ChannelKt$withWallclockTimeout$2$1$2.invokeSuspend(channel.kt:123)
	at app//app.cash.turbine.ChannelKt$withWallclockTimeout$2$1$2.invoke(channel.kt)
	at app//app.cash.turbine.ChannelKt$withWallclockTimeout$2$1$2.invoke(channel.kt)
	at app//kotlinx.coroutines.selects.SelectImplementation$ClauseData.invokeBlock(Select.kt:824)
	at app//kotlinx.coroutines.selects.SelectImplementation.processResultAndInvokeBlockRecoveringException(Select.kt:712)
	at app//kotlinx.coroutines.selects.SelectImplementation.complete(Select.kt:705)
	at app//kotlinx.coroutines.selects.SelectImplementation.doSelectSuspend(Select.kt:441)
	at app//kotlinx.coroutines.selects.SelectImplementation.access$doSelectSuspend(Select.kt:239)
	at app//kotlinx.coroutines.selects.SelectImplementation$doSelectSuspend$1.invokeSuspend(Select.kt)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at kotlinx.coroutines.selects.SelectImplementation.processResultAndInvokeBlockRecoveringException(Select.kt:712)
	at kotlinx.coroutines.selects.SelectImplementation.doSelectSuspend(Select.kt:441)
	at app.cash.turbine.ChannelKt$withWallclockTimeout$2.invokeSuspend(channel.kt:270)
	at app.cash.turbine.ChannelKt.awaitEvent(channel.kt:83)
	at app.cash.turbine.ChannelKt.awaitComplete(channel.kt:222)
	at app.cash.turbine.ChannelTurbine$awaitComplete$2.invokeSuspend(Turbine.kt:203)
	at com.saitejajanjirala.newsapp.presentation.MainViewModelTest$test updates items with success result$1$1.invokeSuspend(MainViewModelTest.kt:106)
	at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:149)
	at app.cash.turbine.FlowKt$turbineScope$2$1.invokeSuspend(flow.kt:91)
	at app.cash.turbine.FlowKt$turbineScope$2$scopeFn$1.invokeSuspend(flow.kt:83)
	at app.cash.turbine.FlowKt$turbineScope$2.invokeSuspend(flow.kt:88)
	at app.cash.turbine.CoroutinesKt$reportTurbines$2.invokeSuspend(coroutines.kt:89)
	at com.saitejajanjirala.newsapp.presentation.MainViewModelTest$test updates items with success result$1.invokeSuspend(MainViewModelTest.kt:103)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)

@OptIn(ExperimentalCoroutinesApi::class)
class MainViewModelTest {


    @get:Rule
    val testDispatcher = TestDispatcherRule()
    private lateinit var getNewsUseCase: GetNewsUseCase
    private lateinit var mainViewModel: MainViewModel
    private lateinit var stateHandle: SavedStateHandle




    @Before
    fun setUp() {
        getNewsUseCase = mock() 
        stateHandle = mock()
        mainViewModel = MainViewModel(getNewsUseCase, stateHandle)
    }
    @After
    fun tearDown() {
        // Reset the dispatcher
    }

    @Test
    fun `test updates items with success result`()  = runTest{
        // Mock articles
        val articles = listOf(
            Article(
                author = "John Doe",
                content = "Sample content",
                description = "Sample description",
                publishedAt = "2024-10-02T04:45:00Z",
                source = Source(id = "source-id", name = "Source Name"),
                title = "Sample Title",
                url = "https://example.com",
                urlToImage = "https://example.com/image.jpg",
                id = 1
            )
        )

        val successResult = Result.Success(articles)

        whenever(getNewsUseCase.invoke("health")) doReturn flowOf(successResult)

        mainViewModel = MainViewModel(getNewsUseCase, stateHandle)

        mainViewModel.fetchHeadLines()


        mainViewModel.items.test {
            val res = awaitItem()
            assertEquals(successResult,res)
            awaitComplete()
        }

    }


}

@HiltViewModel
class MainViewModel @Inject constructor(
    val getNewsUseCase: GetNewsUseCase,
    val savedStateHandle: SavedStateHandle
):ViewModel(){

    private val _items = MutableStateFlow<Result<List<Article>>>(Result.Loading())
    val items: StateFlow<Result<List<Article>>> = _items.asStateFlow()
    init {
        fetchHeadLines()
    }

    fun fetchHeadLines(){

        viewModelScope.launch {
           getNewsUseCase.invoke("health").collect {
               _items.value = it
           }
        }
    }

    fun getUrl(): String? {
       return savedStateHandle.get<String>("url")
    }

} @qwwdfsad  please help
