### ISSUE TITLE
CoroutinesInternalError with a simple reproducer (Kotlin 1.4, Coroutines 1.3.9)

### ISSUE THREAD

**Issue by chemist777** [Kotlin/kotlinx.coroutines#2221]
I faced `CoroutinesInternalError` in my complex code, but made it possible to reproduce it with a smaller one.

Reproducer (Kotlin 1.4, Coroutines 1.3.9, OpenJDK 11):
```kotlin
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import java.util.concurrent.Executors
import kotlin.coroutines.resume
import kotlin.coroutines.suspendCoroutine

private suspend inline fun switchDispatcher(crossinline handler: suspend () -> Unit) {
    Executors.newSingleThreadExecutor().asCoroutineDispatcher().use { dispatcher ->
        withContext(dispatcher) {
            handler.invoke()
        }
    }
}

private suspend fun actualAsyncAction() {
    suspendCoroutine<String> {
        Thread {
            it.resume("test")
        }.start()
    }
}

fun main() {
    runBlocking {
        switchDispatcher {
            actualAsyncAction()
        }
        delay(2000)
    }
}
```

Console output:
```
Exception in thread "pool-1-thread-1" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[java.util.concurrent.Executors$FinalizableDelegatedExecutorService@6f028c61, Continuation at TestKt$main$1$invokeSuspend$$inlined$switchDispatcher$1@a235041]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:103)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	... 3 more
```

And i don't know the reason yet.

**Comment by chemist777** [comment]
Reproducer for another `CoroutinesInternalError` but reason should be the same.

```kotlin
import kotlinx.coroutines.*
import java.util.concurrent.Executors

private suspend inline fun switchDispatcher(dispatcher: CoroutineDispatcher, crossinline handler: suspend () -> Unit) {
    withContext(dispatcher) {
        handler.invoke()
    }
}

fun main() {
    val d1 = Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    val d2 = Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    try {
        runBlocking {
            switchDispatcher(d1) {
                switchDispatcher(d2) {
                    // nothing
                }
            }
            delay(2000)
        }
    } finally {
        d2.close()
        d1.close()
    }
}
```

Console output:
```
Exception in thread "pool-2-thread-1" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[java.util.concurrent.Executors$FinalizableDelegatedExecutorService@789ed779, Continuation at TestKt$main$1$invokeSuspend$$inlined$switchDispatcher$1$lambda$1@d653e64]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: This continuation is already complete
	at kotlin.coroutines.jvm.internal.CompletedContinuation.resumeWith(ContinuationImpl.kt:129)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	... 3 more
```

**Comment by chemist777** [comment]
Workaround for both exceptions is don't use `suspend` and `inline` modifiers in the same time.

**Comment by elizarov** [comment]
Thanks for the report and reporoducer. That's a bug in the compiler. Please, follow this issue: https://youtrack.jetbrains.com/issue/KT-41563
