### ISSUE TITLE
Error Converting Coroutine to Promise in Kotlin and using in JavaScript

### ISSUE THREAD

**Issue by mikeholler** [Kotlin/kotlinx.coroutines#2293]
Kotlin Version: 1.4.10
kotlinx.coroutines version: 1.3.9
npm version: 8.10.0

I got an error while trying to convert a coroutine to a promise in Kotlin and use that promise in js. Code and exception below. I'm actively seeking guidance.

Here is the JavaScript code that is running. Please note that all "local only" functions work as expected, it is just this promise/coroutine part that does not.

Bonus points if you can help me convert a coroutine to a promise directly in JS.

```javascript
let kotlin_b64 = require("physiq-multiplatform-base64");
let b64 = kotlin_b64.com.example.base64

b64.decodeFromStringPromise("YXNkZg==")
    // These next two lines could be commented out and the error would
    // still occur:
    .then( (val) => console.log("Decoded:", val))
    .catch( (val) => console.log("Rejected"))
```

Here is commonKotlin:

```kotlin
package com.example.base64

import io.ktor.client.HttpClient
import io.ktor.client.request.get
import io.ktor.client.statement.HttpResponse
import io.ktor.client.statement.readText
import io.ktor.http.Url
import io.ktor.utils.io.core.use
import kotlin.js.JsName
import kotlin.jvm.JvmName

interface Base64Encoder {
    @JsName("encode")
    fun encode(src: ByteArray): ByteArray

    @JsName("encodeToString")
    fun encodeToString(src: ByteArray): String {
        return encode(src).let { encoded ->
            buildString(encoded.size) {
                encoded.forEach { append(it.toChar()) }
            }
        }
    }

    suspend fun downloadAndEncodeToString(url: String): String {
        return HttpClient().use {
            it.get<HttpResponse>(url = Url(url)).readText()
        }
    }
}

class Base64Decoder {
    @JsName("decodeFromString")
    suspend fun decodeFromString(encoded: String): String {
        return HttpClient().use {
            it.get<HttpResponse>(
                url = Url("https://httpbin.org/base64/$encoded")
            ).readText()
        }
    }
}

expect object Base64Factory {
    fun createEncoder(): Base64Encoder
}

@JsName("createDecoder")
fun createDecoder(): Base64Decoder = Base64Decoder()
```

And here is jsMain:

```kotlin
package com.example.base64

import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.promise
import kotlin.js.Promise

actual object Base64Factory {
    actual fun createEncoder(): Base64Encoder = JsBase64Encoder
}

object JsBase64Encoder : Base64Encoder {
    override fun encode(src: ByteArray): ByteArray {
        val buffer = js("Buffer").from(src)
        val string = buffer.toString("base64") as String
        return ByteArray(string.length) { string[it].toByte() }
    }
}

@JsName("decodeFromStringPromise")
fun decodeFromString(str: String): Promise<String> {
    return GlobalScope.promise { createDecoder().decodeFromString(str) }
}
```

Output:
```
Immediate end.
Rejected
{ CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@1, [object Object]]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
    at Object.captureStack (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/node_modules/kotlin/kotlin.js:39117:15)
    at CoroutinesInternalError.Error_0 [as constructor] (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/node_modules/kotlin/kotlin.js:39413:14)
    at new CoroutinesInternalError (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core.js:2871:13)
    at DispatchedContinuation.DispatchedTask.handleFatalException_mseuzz$ (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core.js:34332:16)
    at DispatchedContinuation.DispatchedTask.run (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core.js:34325:10)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core.js:37640:15)
    at /home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core.js:37456:30
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
  'message_q7r8iu$_0': 'Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@1, [object Object]]. Please read KDoc to \'handleFatalException\' method and report this incident to maintainers',
  'cause_us9j0c$_0': 
   { NullPointerException
    at Object.captureStack (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39117:15)
    at NullPointerException.Exception [as constructor] (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39444:14)
    at NullPointerException.RuntimeException [as constructor] (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39470:17)
    at RuntimeException_init_0 (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39481:24)
    at new NullPointerException (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39590:7)
    at Object.throwNPE (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:43106:13)
    at Kotlin.ensureNotNull (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:750:35)
    at Coroutine$decodeFromString$lambda.CoroutineImpl.releaseIntercepted_0 (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39310:9)
    at Coroutine$decodeFromString.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/packages_imported/kotlin/1.4.10/kotlin.js:39291:19)
    at Coroutine$execute_s9rlw$.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/scratch/physiq-multiplatform-base64/build/js/node_modules/kotlin/kotlin.js:39297:24)
     'message_8yp7un$_0': undefined,
     'cause_th0jdv$_0': null,
     name: 'NullPointerException' },
  name: 'CoroutinesInternalError' }

Process finished with exit code 0
```

**Comment by dkhalanskyjb** [comment]
Hi! I was unable to reproduce your issue. Here's the code that I tested: https://github.com/dkhalanskyjb/check2293, and `gradle jsTest --info` correctly outputs `Decoded:asdf` if the site is available and `Rejected:Error: Fail to fetch` if it's not. Could you please provide a complete reproducer?

As for the bonus points: please see https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/promise.html.
