### ISSUE TITLE
JS - 1.4.0-M1 - Channel based Coroutine cancelling when it shouldn't

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#2318]
Using Kotlin 1.4.10 and kotlinx.coroutines 1.4.0-M1 I'm seeing the coroutine cancel and not complete, when they shouldn't. I've reproduced what I'm seeing on a smaller scale below.

What's very interesting is if I remove `e.printStackTrace()` from `awaitOrNull()` the issue goes away.

```Kotlin
actual fun <T> runTest(block: suspend () -> T): dynamic
        = GlobalScope.async { block() }.asPromise()
```

```Kotlin
class ExampleFailureTest {
    @Test fun jsFailure() = runTest {
        val deferredValue1 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue2 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue3 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue4 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue5 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue6 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue7 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue8 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue9 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue10 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue11 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue12 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue13 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue14 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue15 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue16 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue17 = GlobalScope.async { lastValueFromFlow() }
        val deferredValue18 = GlobalScope.async { lastValueFromFlow() }

        val value1 = deferredValue1.awaitOrNull()
        val value2 = deferredValue2.awaitOrNull()
        val value3 = deferredValue3.awaitOrNull()
        val value4 = deferredValue4.awaitOrNull()
        val value5 = deferredValue5.awaitOrNull()
        val value6 = deferredValue6.awaitOrNull()
        val value7 = deferredValue7.awaitOrNull()
        val value8 = deferredValue8.awaitOrNull()
        val value9 = deferredValue9.awaitOrNull()
        val value10 = deferredValue10.awaitOrNull()
        val value11 = deferredValue11.awaitOrNull()
        val value12 = deferredValue12.awaitOrNull()
        val value13 = deferredValue13.awaitOrNull()
        val value14 = deferredValue14.awaitOrNull()
        val value15 = deferredValue15.awaitOrNull()
        val value16 = deferredValue16.awaitOrNull()
        val value17 = deferredValue17.awaitOrNull()
        val value18 = deferredValue18.awaitOrNull()

        println("Done") // This never runs
    }
}

fun channelFlow(): Flow<Int> {
    val channel = Channel<Int>()

    GlobalScope.launch {
        channel.send(0)
        delay(100)
        channel.send(1)
        delay(100)
        channel.cancel()
        channel.send(2)
    }

    return channel.receiveAsFlow()
}

suspend fun lastValueFromFlow(): Int {
    var last: Int? = null
    channelFlow().collect {
        last = it
    }
    return last!!
}

suspend fun <T> Deferred<T>.awaitOrNull(): T? {
    return try {
        await()
    } catch (e: Throwable) {
        e.printStackTrace()
        null
    }
}
```

I end up with a bunch of these exceptions, and my code never completes:
```
CancellationException: RendezvousChannel was cancelled
    at Object.captureStack (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlin/kotlin/builtins.kt:103:21)
    at CancellationException.Exception [as constructor] (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlin/kotlin.js:39444:14)
    at CancellationException.RuntimeException [as constructor] (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlin/kotlin/exceptions.kt:35:101)
    at CancellationException.IllegalStateException [as constructor] (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlin/kotlin/exceptions.kt:47:106)
    at CancellationException [as constructor] (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:39394:27)
    at CancellationException_init (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:39403:27)
    at RendezvousChannel.AbstractChannel.cancel_m4sck1$$default (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:5964:55)
    at RendezvousChannel.ReceiveChannel.cancel_m4sck1$ (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:7517:55)
    at Coroutine$channelFlow$lambda.doResume (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/service/src/commonTest/kotlin/mobiletest/service/BasicInfoIosDataSourceTests.kt:113:17)
    at Coroutine$channelFlow$lambda.CoroutineImpl.resumeWith_tl1gpc$ (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlin/kotlin/coroutines/CoroutineImpl.kt:47:35)
    at resume (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:36301:26)
    at dispatch (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:36290:7)
    at CancellableContinuationImpl.dispatchResume_0 (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:1555:3)
    at CancellableContinuationImpl.resumeImpl_0 (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:1587:18)
    at CancellableContinuationImpl.resumeUndispatched_hyuxa3$ (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:1658:8)
    at Timeout._onTimeout (/Users/scott.pierce/workspace/dev.scottpierce/mobile-tester/mobile-tester-repository/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:39473:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by LouisCAD** [comment]
Duplicate of #974

**Comment by LouisCAD** [comment]
What happens to `offer` can also happen to `send`.

**Comment by ScottPierce** [comment]
This isn't a duplicate of #974. I've edited the above sample to surround the `channel.send` with a `try / catch`, and I can still reproduce the failure. I think I'm encountering a bug in the coroutines js code.

**Comment by ScottPierce** [comment]
I found that by removing the `e.printStackTrace()` statement, the test passes, and the expected behavior is achieved. This doesn't make any sense as printing shouldn't impact the result of the test.

I've tried the same solution for my actual code, and I still encounter the issue.

**Comment by ScottPierce** [comment]
I was able to work around this in my code by adding mutex locks around send and close of my channel.

For reference - here is my actual code that I swapped out for the `channelFlow` function in my smaller example. It's an object that runs commands on the command line and manages the child processes:

```Kotlin
import child_process.exec
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flatMapConcat
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

internal actual object InternalCommandRunner {
    private const val DEBUG = true
    private var commandCount = 0

    actual fun run(command: String): Flow<String> {
        val scope = CoroutineScope(Job()) + NonCancellable
        val channel = Channel<List<String>>()
        val process = exec(command)
        // Wrap channel in mutex to stop race condition
        val mutex = Mutex()

        val commandId = ++commandCount
        if (DEBUG) {
            println("#$commandId: '$command'")
        }

        process.stdout!!.apply {
            setEncoding("utf8")

            val buffer = StringBuilder()
            on("data") { data: Any ->
                val message = data.toString()
                if (DEBUG) {
                    println("#$commandId: On Data: $message")
                }

                buffer.append(message)
                val lines = buffer.split('\n')
                val sendLastLine = lines.last().isEmpty()

                buffer.clear()
                if (!sendLastLine) {
                    buffer.append(lines.last())
                }

                val toSend: List<String> = if (sendLastLine) {
                    lines
                } else {
                    lines.subList(0, lines.lastIndex)
                }

                scope.launch {
                    mutex.withLock {
                        if (!channel.isClosedForSend) {
                            channel.send(toSend)
                        }
                    }
                }
            }

            on("end") { _: Any? ->
                if (DEBUG) {
                    println("#$commandId: On End")
                }
                scope.launch {
                    mutex.withLock {
                        channel.close()
                    }
                }
            }
        }

        process.stderr!!.on("data") { data: Any ->
            val message = data.toString()
            if (DEBUG) {
                println("#$commandId: Error: $message")
            }
            scope.launch {
                mutex.withLock {
                    if (!channel.isClosedForSend) {
                        channel.send(listOf(message))
                    }
                }
            }
        }

        var processIsExiting = false
        process.on("exit") { _ ->
            processIsExiting = true
            if (DEBUG) {
                println("#$commandId: Process On Exit")
            }
            scope.launch {
                mutex.withLock {
                    if (!channel.isClosedForSend) {
                        channel.close()
                    }
                }
            }
        }

        channel.invokeOnClose {
            if (DEBUG) {
                println("#$commandId: Invoke on Close")
            }
            if (!processIsExiting) {
                process.kill()
            }
        }

        return channel
            .receiveAsFlow()
            .flatMapConcat { lines ->
                flow {
                    for (line in lines) {
                        emit(line)
                    }
                }
            }
    }
}
```

**Comment by ScottPierce** [comment]
This also happens on the IR compiler. Is this a Kotlin JS issue or a coroutines issue?
