### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/cl 

### ISSUE THREAD

**Issue by SharpKnifer** [Kotlin/kotlinx.coroutines#2417]
Kotlin version: 1.3.71
coroutines version: 1.3.8
Android device version: 4.x
I build a 32bit android apk and install in a device which is  Android 4.x . But it always crash at the following up line:

crash code: 
`var MyMain = Looper.getMainLooper().asHandler(true).asCoroutineDispatcher("my-main")
//........

GlobalScope.launch(MyMain) {//crash is at this line
}`
stack trace:
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/cl
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_commonKt.java:55)
	at kotlinx.coroutines.BuildersKt.b(BuildersKt.java)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_commonKt.java:49)
	at kotlinx.coroutines.BuildersKt.b(BuildersKt.java)

The same code is okay on other Android version devices. I have no idea what is wrong. Could you please give me some solution to solve this  problem?

**Comment by qwwdfsad** [comment]
If it only crashes on a specific 32-bit device then it's an Android toolchain issue and I suggest you report it to Google bugtracker instead, unfortunately, we cannot help you here
