### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by weishl110** [Kotlin/kotlinx.coroutines#2480]
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:883)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by fvasco** [comment]
![Art of bug reporting](http://3.bp.blogspot.com/-i4P-QfIoUSE/T0dx50bJ53I/AAAAAAAAAcw/DzgWNO_KgBY/s1600/117+art+of+bug+reporting.png)

**Comment by JayArrowz** [comment]
> Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
> at java.lang.Thread.nativeCreate(Thread.java)
> at java.lang.Thread.start(Thread.java:883)
> at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
> at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)

https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

Maybe you would like a template for reporting bugs, this is so vague.

**Comment by weishl110** [comment]
already fix
