### ISSUE TITLE
Stack trace recovery for exception in nested suspend call

### ISSUE THREAD

**Issue by Pentagarn** [Kotlin/kotlinx.coroutines#2604]
I'm trying to get a useful stack trace in code that calls multiple suspend() methods. Several of the method calls use suspendCancellableCoroutine to work with Java code using futures. Here's an example using delay() to simulate what I'm seeing.

```kotlin
    @Test
    fun coroutineHasCallStack() {
        System.setProperty("kotlinx.coroutines.stacktrace.recovery", "true")
        val ex = assertThrows<RuntimeException> {
            runBlocking {
                firstCall()
            }
        }
        ex.printStackTrace()
        assert(ex.stackTrace.any() {
            it.methodName == "secondCall"
        })
    }

    suspend fun firstCall() {
        networkCall()
        secondCall()
        networkCall()
    }

    suspend fun secondCall() {
        networkCall()
        crashCall()
        networkCall()
    }

    suspend fun crashCall() {
        networkCall()
        throw RuntimeException("Failed")
    }

    suspend fun networkCall() {
        delay(50L)
    }
```

This test fails even if I enable [stack trace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md#stacktrace-recovery). The first part of the stack trace looks like this:
```
java.lang.RuntimeException: Failed
	at org.test.CoroutineTest.crashCall(CoroutineTest.kt:38)
	at org.test.CoroutineTest$crashCall$1.invokeSuspend(CoroutineTest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:369)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:403)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:395)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:491)
        ....
```

It does succeed if I wrap crashCall() in a coroutineScope like this:

```Kotlin
    suspend fun crashCall() = coroutineScope<Unit> {
        networkCall()
        throw RuntimeException("Failed")
    }
```

The trace looks like this now:

```
java.lang.RuntimeException: Failed
	at org.test.ScopedCoroutineTest$crashCall$2.invokeSuspend(ScopedCoroutineTest.kt:38)
	(Coroutine boundary)
	at org.test.ScopedCoroutineTest.secondCall(ScopedCoroutineTest.kt:32)
	at org.test.ScopedCoroutineTest.firstCall(ScopedCoroutineTest.kt:26)
	at org.test.ScopedCoroutineTest$scopedCoroutineHasCallStack$ex$1$1.invokeSuspend(ScopedCoroutineTest.kt:15)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        .....
```

I don't think we should be wrapping every method in a  coroutineScope just in case it may throw an exception, though. What is the best way to get a stack trace that includes the intermediate method calls in production code?

**Comment by qwwdfsad** [comment]
It's because there is no suspendable coroutine boundaries between top-level `runBlocking` and `crashCall`. Filed https://github.com/Kotlin/kotlinx.coroutines/issues/2607

As a workaround, you can use something like 
```
suspend fun crashCall() = coroutineScope {
    networkCall()
    throw RuntimeException("Failed")
}
```

**Comment by Pentagarn** [comment]
Thanks for opening an issue for it, @qwwdfsad. I can add more context in that thread.
