### ISSUE TITLE
Provide an API to recover stacktrace of the exception when it does not cross coroutine boundary

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#2607]
`kotlinx.coroutines` provides a [stacktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md#stacktrace-recovery) machinery in order to provide complete stacktraces that preserve information about all suspended functions in the stracktrace.

But the exception recovery only works through coroutine boundaries.

For example, the following code:
```
suspend fun foo() {
    yield() // Suspend
    bar()
    yield()
}

suspend fun bar() {
    yield() // Suspend
    throw IllegalStateException()
}

runBlocking { // Could've been 'launch' or any other coroutine builder
    foo()
}
```

will be missing `foo` function from the stacktrace because `IllegalStateException` does not cross any suspendable coroutine boundaries and stacktrace recovery machinery don't have a chance to kick in.

Instead, we could've provided a new top-level suspend function that recovers the stacktrace. Library authors and application developers could've been using that along with stacktrace-sensitive exceptions and/or "expected" failures.

There is a lot of shape for such API, e.g. `throw IllegalStateException().recoverStacktrace()` or 
```
recovering {
    require(myArg >= 1, "Expected myArg to be >= 1")
}
```

but the biggest question of this issue is whether it is useful for other developers.
Opinions regarding usefulness of such API are welcomed

**Comment by dovchinnikov** [comment]
In IJ we often log an error trace and proceed without throwing, this would be a huge help to have the ability to recover full trace.

We'd like to obtain “trace when caught” at the point of “trace when thrown” in the following example:
```
package com.foo.bar

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import kotlin.time.Duration.Companion.seconds

fun main() {
  runBlocking {
    try {
      withContext(Dispatchers.Default) {
        delay(1.seconds)
        doWork()
      }
    }
    catch (t: Throwable) {
      println("trace when caught:")
      t.printStackTrace(System.out)
    }
  }
}

private fun doWork(): Int {
  val ise = IllegalStateException("Internal invariant failed")
  println("trace when thrown:")
  ise.printStackTrace(System.out)
  throw ise
}
```

```
trace when thrown:
java.lang.IllegalStateException: Internal invariant failed
	at com.foo.bar.RecoveryExampleKt.doWork(recoveryExample.kt:26)
	at com.foo.bar.RecoveryExampleKt.access$doWork(recoveryExample.kt:1)
	at com.foo.bar.RecoveryExampleKt$main$1$1.invokeSuspend(recoveryExample.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
trace when caught:
java.lang.IllegalStateException: Internal invariant failed
	at com.foo.bar.RecoveryExampleKt.doWork(recoveryExample.kt:26)
	at com.foo.bar.RecoveryExampleKt.access$doWork(recoveryExample.kt:1)
	at com.foo.bar.RecoveryExampleKt$main$1$1.invokeSuspend(recoveryExample.kt:15)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
	at com.foo.bar.RecoveryExampleKt$main$1.invokeSuspend(recoveryExample.kt:13)
Caused by: java.lang.IllegalStateException: Internal invariant failed
	at com.foo.bar.RecoveryExampleKt.doWork(recoveryExample.kt:26)
	at com.foo.bar.RecoveryExampleKt.access$doWork(recoveryExample.kt:1)
	at com.foo.bar.RecoveryExampleKt$main$1$1.invokeSuspend(recoveryExample.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Anamorphosee** [comment]
>We'd like to obtain “trace when caught” at the point of “trace when thrown” in the following example:

@dovchinnikov With [Decoroutinator](https://github.com/Anamorphosee/stacktrace-decoroutinator) you can already achieve the full call trace for the example.
The output for [the example with Decoroutinator](https://gist.github.com/Anamorphosee/8df7dd169a056b462a75e3f132932faa) is
```
trace when thrown:
java.lang.IllegalStateException: Internal invariant failed
	at com.foo.bar.RecoveryExampleKt.doWork(recoveryExample.kt:27)
	at com.foo.bar.RecoveryExampleKt.access$doWork(recoveryExample.kt:1)
	at com.foo.bar.RecoveryExampleKt$main$1$1.invokeSuspend(recoveryExample.kt:16)
	at kotlin.coroutines.jvm.internal.DecoroutinatorBaseContinuationAccessorImpl.invokeSuspend(base-continuation-accessor.kt:15)
	at dev.reformator.stacktracedecoroutinator.common.internal.DecoroutinatorSpecImpl.resumeNext(utils-common.kt:288)
	at dcunknown.UnknownKt.unknown(unknown.kt:24)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:147)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.foo.bar.RecoveryExampleKt$main$1.invokeSuspend(recoveryExample.kt:14)
	at dev.reformator.stacktracedecoroutinator.mhinvoker.internal.RegularMethodHandleInvoker.callSpecMethod(mh-invoker.kt:21)
	at dev.reformator.stacktracedecoroutinator.common.internal.AwakenerKt.callSpecMethods(awakener.kt:179)
	at dev.reformator.stacktracedecoroutinator.common.internal.AwakenerKt.awake(awakener.kt:39)
	at dev.reformator.stacktracedecoroutinator.common.internal.Provider.awakeBaseContinuation(provider-impl.kt:36)
	at dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorProviderApiKt.awakeBaseContinuation(provider-api.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
trace when caught:
java.lang.IllegalStateException: Internal invariant failed
	at com.foo.bar.RecoveryExampleKt.doWork(recoveryExample.kt:27)
	at com.foo.bar.RecoveryExampleKt.access$doWork(recoveryExample.kt:1)
	at com.foo.bar.RecoveryExampleKt$main$1$1.invokeSuspend(recoveryExample.kt:16)
	at kotlin.coroutines.jvm.internal.DecoroutinatorBaseContinuationAccessorImpl.invokeSuspend(base-continuation-accessor.kt:15)
	at dev.reformator.stacktracedecoroutinator.common.internal.DecoroutinatorSpecImpl.resumeNext(utils-common.kt:288)
	at dcunknown.UnknownKt.unknown(unknown.kt:24)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:147)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.foo.bar.RecoveryExampleKt$main$1.invokeSuspend(recoveryExample.kt:14)
	at dev.reformator.stacktracedecoroutinator.mhinvoker.internal.RegularMethodHandleInvoker.callSpecMethod(mh-invoker.kt:21)
	at dev.reformator.stacktracedecoroutinator.common.internal.AwakenerKt.callSpecMethods(awakener.kt:179)
	at dev.reformator.stacktracedecoroutinator.common.internal.AwakenerKt.awake(awakener.kt:39)
	at dev.reformator.stacktracedecoroutinator.common.internal.Provider.awakeBaseContinuation(provider-impl.kt:36)
	at dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorProviderApiKt.awakeBaseContinuation(provider-api.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	at .(decoroutinator-boundary)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:147)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.foo.bar.RecoveryExampleKt$main$1.invokeSuspend(recoveryExample.kt:14)
	at .(decoroutinator-boundary)
```
