### ISSUE TITLE
Crossinline breaks coroutines

### ISSUE THREAD

**Issue by bluefireoly** [Kotlin/kotlinx.coroutines#2611]
The crossinline language feature of kotlin breaks a lot with kotlinx.coroutines.

## Reproduce
In the following example, it should wait 10 seconds and then print "hey":
```kt
import kotlinx.coroutines.*

val coroutineScope = CoroutineScope(Dispatchers.IO)

inline fun Int.doSomethingAsync(
    crossinline longRunning: suspend (Int) -> String
): Deferred<String> {
    return coroutineScope.async {
        longRunning.invoke(this@doSomethingAsync)
    }
}

suspend fun main() = println(
    30.doSomethingAsync {
        delay(10000)
        "hey"
    }.await()
)
```
...but in reality it prints "hey" immediately.

Also, I tested it without crossinline (and inline), which just works normal (waits 10 seconds and then prints "hey"):
```kt
import kotlinx.coroutines.*

val coroutineScope = CoroutineScope(Dispatchers.IO)

fun Int.doSomethingAsync(
    longRunning: suspend (Int) -> String
): Deferred<String> {
    return coroutineScope.async {
        longRunning.invoke(this@doSomethingAsync)
    }
}

suspend fun main() = println(
    30.doSomethingAsync {
        delay(10000)
        "hey"
    }.await()
)
```

## Other errors

In the above example there is no error message, but in more complex scenarios (with crossinline) I got the following error messages:

`kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[BlockingEventLoop@51d48632, Continuation at net.axay.fabrik.commands.BrigardierWrapperKt$simpleSuggests$1$1.invokeSuspend(BrigardierWrapper.kt:88)@3aefa4d1]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: BlockingCoroutine has completed normally; job="coroutine#1":BlockingCoroutine{Completed}@20adddb]}@26bcbda2. Please read KDoc to 'handleFatalException' method and report this incident to maintainers`

or

```
Exception in thread "DefaultDispatcher-worker-3" [17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at net.axay.fabrik.commands.BrigardierWrapperKt$simpleSuggests$1$1.invokeSuspend(BrigardierWrapper.kt:78)@2e46906e]){Cancelled}@767ba59b. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
[17:01:49] [DefaultDispatcher-worker-3 @coroutine#12/INFO] (Minecraft) [STDERR]: 	... 4 more
```

Both 100% appeared due to crossinline and inline, as I could fix them by removing the inline keywords.

## Conclusion
a. this should be fixed
or
b. the compiler must disallow combining coroutines with crossinline

**Comment by qwwdfsad** [comment]
Thanks for the report!

It is definitely a compiler bug and we are currently investigating whether it is a known one (so you at least will know where to keep track of it) or something new

**Comment by twyatt** [comment]
@bluefireoly as a workaround, you can drop the `invoke` and it will work as expected with `crossinline`.

In other words, your first example works as expected without the `.invoke`:

```diff
  import kotlinx.coroutines.*
  
  val coroutineScope = CoroutineScope(Dispatchers.IO)
  
  inline fun Int.doSomethingAsync(
      crossinline longRunning: suspend (Int) -> String
  ): Deferred<String> {
      return coroutineScope.async {
-         longRunning.invoke(this@doSomethingAsync)
+         longRunning(this@doSomethingAsync)
      }
  }
  
  suspend fun main() = println(
      30.doSomethingAsync {
          delay(10000)
          "hey"
      }.await()
  )
```

**Comment by twyatt** [comment]
Related YouTrack issue: https://youtrack.jetbrains.com/issue/KT-31269
