### ISSUE TITLE
CoroutinesInternalError with inline assertFailsWith on JS (node) platform

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/kotlinx.coroutines#2623]
I'm sorry if this has been reported before, I have seen several issues with this exception but it's hard to tell if the root cause is the same. I've faced this several times in different projects, and I finally could find a quite minimal example to reproduce 100% reliably, so here it is.

Notable elements:

* I'm wrapping suspending test code into `GlobalScope.promise { ... }`, which may be part of the problem ([please publish a multiplatform `kotlinx-coroutines-test`](https://github.com/Kotlin/kotlinx.coroutines/issues/1996) 😄 ). The equivalent code with `runBlocking` works fine on JVM.
* I'm using an inline function `assertFailsWith` (it works correctly with the non-inline variant)
* As you can see, this is running on my local windows, but I got the same error [on the CI using Ubuntu and JDK 15](https://github.com/joffrey-bion/krossbow/runs/2253976676?check_suite_focus=true#step:6:286)

```kotlin
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import kotlinx.coroutines.promise
import kotlin.test.Test
import kotlin.test.assertFailsWith

class FatalExceptionCoroutinesTest {

    @Test
    fun testFatalException() = GlobalScope.promise {
        val mock = MockClient()

        launch {
            mock.waitForConnectCall()
            mock.simulateFailedConnection(Exception("something bad"))
        }
        assertFailsWith<Exception> {
            mock.connect()
        }
    }
}

class MockClient {
    private val connectEventChannel = Channel<Unit>()
    private val connectedEventChannel = Channel<Unit>()

    suspend fun connect() {
        connectEventChannel.send(Unit)
        return connectedEventChannel.receive()
    }

    suspend fun waitForConnectCall() {
        connectEventChannel.receive()
    }

    fun simulateFailedConnection(cause: Throwable) {
        connectedEventChannel.close(cause)
    }
}
```

Several observations here:

* on NodeJS platform, I get the internal error (see below)
* on Browser platform, I get a test failure ("Expected an exception of class Exception to be thrown, but was completed successfully")
* when I use the non-inline `assertFailsWith(Exception::class) { ... }`, it works correctly on both platform 100% of the time!
* if I comment out the `connectEventChannel.send()` and `connectEventChannel.receive()` calls, I don't get the internal error on NodeJS anymore, but I get the same test failure as the one on browser platform.

Here is the stack trace:

```
CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[NodeDispatcher@1, [object Object]]){Cancelled}@2. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
    at Object.captureStack (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\builtins.kt:103:21)
    at CoroutinesInternalError.Error_0 [as constructor] (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin.js:39420:14)
    at new CoroutinesInternalError (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:2988:13)
    at CancellableContinuationImpl.DispatchedTask.handleFatalException_pr7uss$ (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:34920:16)
    at CancellableContinuationImpl.DispatchedTask.run (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:34913:10)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:38302:15)
    at C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:38118:30
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  'message_q7r8iu$_0': "Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[NodeDispatcher@1, [object Object]]){Cancelled}@2. Please read KDoc to 'handleFatalException' method and report this incident to maintainers",
  'cause_us9j0c$_0': ClassCastException: Illegal cast
      at Object.captureStack (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\builtins.kt:103:21)
      at ClassCastException.Exception [as constructor] (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin.js:39451:14)
      at ClassCastException.RuntimeException [as constructor] (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\exceptions.kt:35:101)
      at RuntimeException_init_0 (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\exceptions.kt:37:44)
      at new ClassCastException (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin.js:39607:7)
      at throwCCE_0 (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\exceptionUtils.kt:15:11)
      at NodeDispatcher.CoroutineDispatcher.releaseInterceptedContinuation_k98bjh$ (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:2053:84)
      at Coroutine$FatalExceptionCoroutinesTest$testFatalException$lambda.CoroutineImpl.releaseIntercepted_0 (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\coroutines\CoroutineImpl.kt:75:48)
      at Coroutine$connect.CoroutineImpl.resumeWith_tl1gpc$ (C:\Projects\krossbow\build\js\node_modules\kotlin\kotlin\coroutines\CoroutineImpl.kt:56:17)
      at CancellableContinuationImpl.DispatchedTask.run (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:34890:22)
      at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:38302:15)
      at C:\Projects\krossbow\build\js\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:38118:30
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    'message_8yp7un$_0': 'Illegal cast',
    'cause_th0jdv$_0': null,
    name: 'ClassCastException'
  },
  name: 'CoroutinesInternalError'
}
```

**Comment by qwwdfsad** [comment]
Thanks for the write-up and analysis! 

It is, indeed, a compiler bug that is unlikely to be fixed in the current JS backend but will be fixed in the JS IR backend.
Please keep track of this bug here: https://youtrack.jetbrains.com/issue/KT-37645

**Comment by joffrey-bion** [comment]
Ok thanks a lot for the info! I wish I could use the IR backend, but [this other issue](https://youtrack.jetbrains.com/issue/KT-45542) is still (transitively) blocking me from moving, unfortunately. Because I depend on Okio and they are blocked by this.
