### ISSUE TITLE
 Unresolved reference: receiveAsFlow

### ISSUE THREAD

**Issue by mertceyhan** [Kotlin/kotlinx.coroutines#2629]
I use `receiveAsFlow` function for a `Channel`. There is no problem when I build and run the application on my phone. Flow is working well but, I'm getting  `Unresolved reference: receiveAsFlow` when I run `./gradlew check` or `./gradlew lint` task only the terminal.

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileReleaseKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)

```

**Comment by qwwdfsad** [comment]
Sorry, the problem lacks context and there is not much from the exception message, so we cannot assist you without further information and/or self-contained reproducer
