### ISSUE TITLE
Passing non-suspending method into method accepting suspending method with receiver and parameter crashes with VerifyError on Android

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#2658]
Starting following activity on Android:

```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setLamda(MainActivity::nonSuspendingMethod)
    }

    fun setLamda(lamda: suspend MainActivity.(a: String) -> Unit) {
    }


    fun nonSuspendingMethod(a: String) {
    }
}
```

Will crash the app with the following error:

```
    java.lang.VerifyError: Verifier rejected class com.matejdro.coroutinesttest.MainActivity$onCreate$1: java.lang.Object com.matejdro.coroutinesttest.MainActivity$onCreate$1.invoke(com.matejdro.coroutinesttest.MainActivity, java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.matejdro.coroutinesttest.MainActivity$onCreate$1.invoke(com.matejdro.coroutinesttest.MainActivity, java.lang.String, kotlin.coroutines.Continuation): [0x0] register v4 has type Reference: kotlin.coroutines.Continuation but expected Precise Reference: java.lang.String (declaration of 'com.matejdro.coroutinesttest.MainActivity$onCreate$1' appears in /data/app/com.matejdro.coroutinesttest-_T2NB8HnzUXRnWoJ93LkwQ==/base.apk!classes3.dex)
        at com.matejdro.coroutinesttest.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6723)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

This is with Kotlin 1.4.32, coroutines 1.4.3 and Android 9 running on OnePlus 3.

**Comment by qwwdfsad** [comment]
Hi, unfortunately, this is a compiler bug related to methods references and coroutines.
I've verified that it does reproduce on Kotlin 1.4.31 and does not on Kotlin 1.5.0-RC, so it will be enough to upgrade to 1.5 when it's ready
