### ISSUE TITLE
NoClassDefFoundError BuildersKt

### ISSUE THREAD

**Issue by shakram02** [Kotlin/kotlinx.coroutines#269]
Hello, I was trying out the library and I got this error. I'm not sure what is the source

It says that the error is in [Event.kt:30](https://github.com/shakram02/Kt-Events/blob/master/src/main/java/Event.kt#L30)
```Kotlin
handlers.forEach { h -> launch { h(value) } }
```

The error originates [here](https://github.com/shakram02/Blue/blob/enhance-event-based-architecture/src/BlueClientTest.kt) in any of the tests

The coroutines library worked normally in the Kt-Event project, I created a jar and I wanted to use it in the other project when it threw an exception

```
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: kotlinx/coroutines/experimental/BuildersKt
	at PooledEvent.invoke(Event.kt:30)
	at BlueServer$acceptHandler$1.invoke(BlueServer.kt:35)
	at BlueServer$acceptHandler$1.invoke(BlueServer.kt:9)
	at HandlerUtils$Companion$toHandler$1.completed(HandlerUtils.kt:13)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.experimental.BuildersKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by jcornaz** [comment]
The Jar you created only contains the "Kt-Event" project. It doesn't contains "kotlinx.coroutines".

You should either:
1. create a *fat-jar* with all dependencies of the "Kt-Event" project, 
2. add kotlinx.coroutines as a dependency of the other project
3. use maven or gradle on the other project (this would solve all sub-dependencies)
Note that if you don't want to setup an artifact repository you can use [jitpack](https://jitpack.io/#shakram02/Kt-Events)

**Comment by shakram02** [comment]
I'll use the third option as you recommended and will try to play with the first one. 
Thank you so much, ( I never heard about jitpack before ) :+1:
