### ISSUE TITLE
Compilation exception (AssertionError: Stack should be spilled before suspension call) after moving from 1.4.2 to 1.5.0

### ISSUE THREAD

**Issue by vadim-shb** [Kotlin/kotlinx.coroutines#2742]
I've moved from 1.4.2 to 1.5.0 and get a compilation exception:
```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during code generation
File being compiled: /***/src/main/kotlin/org/example/Test.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.doGenerateFilesInternal(JvmIrCodegenFactory.kt:209)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:62)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:592)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:212)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:155)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:386)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:110)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:303)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:121)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1659)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Exception while generating code for:
FUN name:main visibility:public modality:FINAL <> () returnType:kotlin.Unit
  BLOCK_BODY
    VAR name:st type:kotlinx.coroutines.flow.MutableStateFlow<kotlin.collections.List<kotlin.String>> [val]
      CALL 'public final fun MutableStateFlow <T> (value: T of kotlinx.coroutines.flow.StateFlowKt.MutableStateFlow): kotlinx.coroutines.flow.MutableStateFlow<T of kotlinx.coroutines.flow.StateFlowKt.MutableStateFlow> declared in kotlinx.coroutines.flow.StateFlowKt' type=kotlinx.coroutines.flow.MutableStateFlow<kotlin.collections.List<kotlin.String>> origin=null
        <T>: kotlin.collections.List<kotlin.String>
        value: CALL 'public final fun emptyList <T> (): kotlin.collections.List<T of kotlin.collections.CollectionsKt.emptyList> declared in kotlin.collections.CollectionsKt' type=kotlin.collections.List<kotlin.String> origin=null
          <T>: kotlin.String
    VAR name:sortedSt type:kotlinx.coroutines.flow.StateFlow<kotlin.collections.List<kotlin.String>> [val]
      CALL 'public final fun mapX <N, M> (change: kotlin.Function1<N of org.example.TestKt.mapX, M of org.example.TestKt.mapX>): kotlinx.coroutines.flow.StateFlow<M of org.example.TestKt.mapX> [inline] declared in org.example.TestKt' type=kotlinx.coroutines.flow.StateFlow<kotlin.collections.List<kotlin.String>> origin=null
        <N>: kotlin.collections.List<kotlin.String>
        <M>: kotlin.collections.List<kotlin.String>
        $receiver: GET_VAR 'val st: kotlinx.coroutines.flow.MutableStateFlow<kotlin.collections.List<kotlin.String>> [val] declared in org.example.TestKt.main' type=kotlinx.coroutines.flow.MutableStateFlow<kotlin.collections.List<kotlin.String>> origin=null
        change: BLOCK type=kotlin.Function1<kotlin.collections.List<kotlin.String>, kotlin.collections.List<kotlin.String>> origin=LAMBDA
          COMPOSITE type=kotlin.Unit origin=null
          FUNCTION_REFERENCE 'private final fun main$lambda-1 (it: kotlin.collections.List<kotlin.String>): kotlin.collections.List<kotlin.String> declared in org.example.TestKt' type=kotlin.Function1<kotlin.collections.List<kotlin.String>, kotlin.collections.List<kotlin.String>> origin=LAMBDA reflectionTarget=null

	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate$default(FunctionCodegen.kt:43)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethodNode(ClassCodegen.kt:364)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethod(ClassCodegen.kt:379)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:132)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.doGenerateFilesInternal(JvmIrCodegenFactory.kt:206)
	... 34 more
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
emit (Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;:
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
    ALOAD 2
    INSTANCEOF org/example/TestKt$main$$inlined$mapX$1$1$1
    IFEQ L0
    ALOAD 2
    CHECKCAST org/example/TestKt$main$$inlined$mapX$1$1$1
    ASTORE 12
    ALOAD 12
    GETFIELD org/example/TestKt$main$$inlined$mapX$1$1$1.label : I
    LDC -2147483648
    IAND
    IFEQ L0
    ALOAD 12
    DUP
    GETFIELD org/example/TestKt$main$$inlined$mapX$1$1$1.label : I
    LDC -2147483648
    ISUB
    PUTFIELD org/example/TestKt$main$$inlined$mapX$1$1$1.label : I
    GOTO L1
   L0
    NEW org/example/TestKt$main$$inlined$mapX$1$1$1
    DUP
    ALOAD 0
    ALOAD 2
    INVOKESPECIAL org/example/TestKt$main$$inlined$mapX$1$1$1.<init> (Lorg/example/TestKt$main$$inlined$mapX$1$1;Lkotlin/coroutines/Continuation;)V
    ASTORE 12
   L1
    ALOAD 12
    GETFIELD org/example/TestKt$main$$inlined$mapX$1$1$1.result : Ljava/lang/Object;
    ASTORE 11
   L2
   L3
    ACONST_NULL
    POP
   L4
    LINENUMBER 73 L4
    ALOAD 1
    ALOAD 12
    ICONST_0
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.mark (I)V
    ASTORE 4
    ASTORE 5
   L5
    ICONST_0
    ISTORE 6
   L6
    LINENUMBER 135 L6
    ALOAD 0
    GETFIELD org/example/TestKt$main$$inlined$mapX$1$1.$out$inlined : Lkotlinx/coroutines/flow/MutableStateFlow;
    ALOAD 5
    CHECKCAST java/util/List
    ASTORE 7
    ASTORE 9
   L7
    ICONST_0
    ISTORE 8
   L8
    LINENUMBER 141 L8
    ALOAD 7
    CHECKCAST java/lang/Iterable
    INVOKESTATIC kotlin/collections/CollectionsKt.sorted (Ljava/lang/Iterable;)Ljava/util/List;
    NOP
    GOTO L9
   L10
   L11
   L12
   L9
    ASTORE 10
    ALOAD 9
    ALOAD 10
    INVOKEINTERFACE kotlinx/coroutines/flow/MutableStateFlow.setValue (Ljava/lang/Object;)V (itf)
   L13
    ICONST_1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.mark (I)V
   L14
    NOP
   L15
    GETSTATIC kotlin/Unit.INSTANCE : Lkotlin/Unit;
    ARETURN
   L16
   L17
   L18
    LOCALVARIABLE this Lorg/example/TestKt$mapX$$inlined$collectX$1$1; L3 L14 0
    LOCALVARIABLE value Ljava/lang/Object; L3 L14 1
    LOCALVARIABLE it Ljava/lang/Object; L5 L13 5
    LOCALVARIABLE it Ljava/util/List; L7 L12 7
    LOCALVARIABLE $i$a$-mapX-TestKt$main$sortedSt$1 I L8 L12 8
    LOCALVARIABLE $i$a$-collectX-TestKt$mapX$1 I L6 L13 6
    LOCALVARIABLE $completion Lkotlin/coroutines/Continuation; L5 L18 4
    LOCALVARIABLE $continuation Lkotlin/coroutines/Continuation; L1 L18 12
    LOCALVARIABLE $result Ljava/lang/Object; L2 L18 11
    MAXSTACK = 4
    MAXLOCALS = 13

File is unknown
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.spillVariables(CoroutineTransformerMethodVisitor.kt:645)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:772)
	at org.jetbrains.kotlin.codegen.inline.DeferredMethodVisitor.visitEnd(DeferredMethodVisitor.kt:31)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:183)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:192)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:216)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:473)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:77)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:357)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:108)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:78)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethod(AnonymousObjectTransformer.kt:325)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethodAndUpdateGlobalResult(AnonymousObjectTransformer.kt:285)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:165)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:192)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:216)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:473)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:77)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:357)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:108)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:78)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:241)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:136)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrInlineCodegen.genInlineCall(IrInlineCodegen.kt:146)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrInlineCallGenerator$DefaultImpls.genCall(IrInlineCallGenerator.kt:28)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrInlineCodegen.genCall(IrInlineCodegen.kt:33)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:451)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:111)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitVariable(ExpressionCodegen.kt:583)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitVariable(ExpressionCodegen.kt:111)
	at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.accept(IrVariableImpl.kt:74)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:398)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:402)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:111)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.generate(ExpressionCodegen.kt:222)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.doGenerate(FunctionCodegen.kt:111)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:48)
	... 39 more
Caused by: java.lang.AssertionError: Stack should be spilled before suspension call
	at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.spillVariables(CoroutineTransformerMethodVisitor.kt:645)
	at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.performTransformations(CoroutineTransformerMethodVisitor.kt:141)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:70)
	... 81 more
```

Code snippet to reproduce the issue:
```
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*


inline fun <N> Flow<N>.collectX(crossinline block: suspend (value: N) -> Unit) {
    GlobalScope.launch { this@collectX.collect(block) }
}

inline fun <N, M> StateFlow<N>.mapX(crossinline change: (N) -> M): StateFlow<M> {
    val out = MutableStateFlow<M>(change(this.value))
    this.collectX { out.value = change(it) }
    return out
}

fun main() {
    val st = MutableStateFlow<List<String>>(emptyList())
    val sortedSt: StateFlow<List<String>> = st.mapX { it.sorted() }
}
```

kotlin version: 1.5.10

**Comment by qwwdfsad** [comment]
Thanks! 

This is a regression in Kotlin 1.5.0 that can be fixed only on compiler side: https://youtrack.jetbrains.com/issue/KT-46879

**Comment by vadim-shb** [comment]
The same code, the same compiler but with dependency "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3" works fine. Are you sure it's the compiler issue?

**Comment by qwwdfsad** [comment]
Yes, the coroutines have been compiled with a different version of compiler and inliner behaves differently.
The rule of thumb -- if `org.jetbrains.kotlin.backend.common.BackendException` is thrown during a compilation -- it's **always** a compiler bug.
Compiler should never crash, only produce human-readable warnings and errors
