### ISSUE TITLE
Could not initialize class kotlinx.coroutines.CompletedExceptionally When using viewModelScope inside lazy

### ISSUE THREAD

**Issue by mohammadmahozi** [Kotlin/kotlinx.coroutines#2807]
Hello

The problem occurs only inside lazy delgate when i use viewModelScope to post value of a live data.

Sample code

```kotlin
class VM : ViewModel() {
    
    private val liveData: MutableLiveData<String> by lazy {

        test()
        MutableLiveData()
    }
    
    fun test(){

        viewModelScope.launch {

            liveData.postValue("it")
        }

    }
}
```

RunBlocking causes the same problem but GlobaLScope works fine. The problem only happens when i run unit tests. I am using Kotlin version 1.5.20. I have noticed that sometimes when i change the version and sync gradle then run the test, it throws the real exception(in this case it is a stackoverflow)

Here is the test:

```kotlin
  class ExampleUnitTest {
    // Set the main coroutines dispatcher for unit testing.
    @ExperimentalCoroutinesApi
    @get:Rule
    var mainCoroutineRule = CoroutineDispatcherRule()

    @get:Rule
    var instantExecutorRule = InstantTaskExecutorRule()


    private var vm = VM()

    @Test
    fun test() {
        
        vm.test()
        assert(true)
    }
}



```

full error:

```kotlin
java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.CompletedExceptionally

	at kotlinx.coroutines.CompletionStateKt.toState(CompletionState.kt:16)
	at kotlinx.coroutines.CompletionStateKt.toState$default(CompletionState.kt:12)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:65)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.mahozi.kotlinexception.VM.test(VM.kt:21)
	at com.mahozi.kotlinexception.ExampleUnitTest.test(ExampleUnitTest.kt:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

Here is a sample project: https://github.com/mohammadmahozi/KotlinException

**Comment by qwwdfsad** [comment]
You have an unbounded recursion in your code: `test` tries to initialize `liveData` in-place (because main test dispatcher does so), but `liveData` initialization immediately invokes `test` again.

In the end, the code throws`StackOverflowError` and this error starts being handled. But during the handling, some classes has to be loaded, that loading also triggers `StackOverflowError` (because we're way beyond stack limit at this point) and error during class initialization triggers various `NoClassDefFoundError` and `ExceptionInInitializerError`
