### ISSUE TITLE
flow debounce with selector crashes compiler while getting TypeInfo of resultant Flow

### ISSUE THREAD

**Issue by greggiacovelli** [Kotlin/kotlinx.coroutines#2825]
Found an interesting issue regarding debounce with a selector. By debouncing a flow containing values of a sealed class, things get weird. This seems like it would be a common usecase for this extension, however I was able to reproduce this locally with kotlin 1.5.0/coroutines 1.5.0 and within the jetbrains sandbox (https://jetbrains.github.io/kotlin-playground/examples/ with kotlin junit or jvm) .

**Offending Code**

    import kotlinx.coroutines.flow.flowOf
    import kotlinx.coroutines.flow.debounce
    import kotlinx.coroutines.flow.collect
    import kotlinx.coroutines.flow.Flow

    sealed class Foo {
      object A: Foo()
      data class B(val a: Int): Foo()
    }

    fun invalidFlow(): Flow<Foo> {
      return flowOf(Foo.A, Foo.B(1)).debounce { value -> if (value == Foo.A) 0 else 1000L} 
      // debounce { 0L } in this cases produces the same result
    }

    fun main(args: Array<Strings>) {
      runBlocking { println(invalidFlow().toList()) }
    }

**Resulting Error**

    Exception in thread "main" org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (26,12) in /File.kt
    at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:253) 
    at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:224) 
    at org.jetbrains.kotlin.util.PerformanceCounter.time (PerformanceCounter.kt:101) 
    Caused by: java.lang.IllegalStateException: Type variable TypeVariable(T) should not be fixed!
        Base constraint: Flow<TypeVariable(T)> <: Flow<Foo> from position: Incorporate Flow<TypeVariable(T)> <: Flow<Foo> 
        from ExpectedType for call debounce { value -> 0L } from position ExpectedType for call debounce { value -> 0L }
        at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector$TypeCheckerContext.fixedTypeVariable(ConstraintInjector.kt:428)
        at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector.processGivenConstraints(ConstraintInjector.kt:174)
        at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector.processConstraints(ConstraintInjector.kt:145)

**Workaround**

    import kotlinx.coroutines.flow.flowOf
    import kotlinx.coroutines.flow.debounce
    import kotlinx.coroutines.flow.toList
    import kotlinx.coroutines.flow.merge
    import kotlinx.coroutines.runBlocking
    import kotlinx.coroutines.flow.Flow

    sealed class Foo {
      object A: Foo()
      data class B(val a: Int): Foo()
    }

    fun validFlow(): Flow<Foo> {
      return merge(
        flowOf(Foo.A).debounce(0L),
        flowOf(Foo.B(1)).debounce(1000L),
      )
    }

    fun main(args: Array<String>) { 
      runBlocking { println(validFlow().toList()) }
    }

**Comment by qwwdfsad** [comment]
Thanks for the self-contained reproducer! This is indeed a compiler issue, filed https://youtrack.jetbrains.com/issue/KT-48031, please keep track of it there
