### ISSUE TITLE
CompilationException

### ISSUE THREAD

**Issue by DaatSer** [Kotlin/kotlinx.coroutines#2849]
Got this issue after migration from the `1.4.2` to `1.5.1` version.    

### Description
It was a Android compilation with next compile options:
```
compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
```

### Function that fails to compile
```
override fun getCriticalFaultsFlow(): Flow<List<FaultInfo?>> {
        return faultsDao.getAllFaultsFlow()
            .map { faults ->
                faults.sortedBy(FaultEntity::priority)
                    .distinctBy(FaultEntity::deviceId)
                    .map(FaultEntity::toFault)
            }
    }
```

### Stacktrace
```
> Task :yyy:compileControllerDebugKotlin FAILED
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
emit (Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;:
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
   L0
    ALOAD 2
    INSTANCEOF com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1
    IFEQ L1
    ALOAD 2
    CHECKCAST com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1
    ASTORE 28
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.label : I
    LDC -2147483648
    IAND
    IFEQ L1
    ALOAD 28
    DUP
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.label : I
    LDC -2147483648
    ISUB
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.label : I
    GOTO L2
   L1
    NEW com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1
    DUP
    ALOAD 0
    ALOAD 2
    INVOKESPECIAL com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.<init> (Lcom/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2;Lkotlin/coroutines/Continuation;)V
    ASTORE 28
   L2
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.result : Ljava/lang/Object;
    ASTORE 27
   L3
    INVOKESTATIC kotlin/coroutines/intrinsics/IntrinsicsKt.getCOROUTINE_SUSPENDED ()Ljava/lang/Object;
   L4
    LINENUMBER 32 L4
    ASTORE 29
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.label : I
    TABLESWITCH
      0: L5
      1: L6
      default: L7
   L5
    ALOAD 27
    INVOKESTATIC kotlin/ResultKt.throwOnFailure (Ljava/lang/Object;)V
   L8
    NOP
   L9
    LINENUMBER 73 L9
    ALOAD 1
    ALOAD 28
    ASTORE 4
    ASTORE 5
   L10
    ICONST_0
    ISTORE 6
   L11
    LINENUMBER 135 L11
    ALOAD 0
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2.$this_unsafeFlow$inlined : Lkotlinx/coroutines/flow/FlowCollector;
    ALOAD 5
    ALOAD 28
    ASTORE 7
    ASTORE 8
    ASTORE 9
   L12
    ICONST_0
    ISTORE 10
   L13
    LINENUMBER 136 L13
    ALOAD 9
    ASTORE 11
    ALOAD 8
    ALOAD 28
    CHECKCAST kotlin/coroutines/Continuation
    ASTORE 12
    CHECKCAST java/util/List
    ASTORE 13
   L14
    ICONST_0
    ISTORE 14
   L15
    LINENUMBER 137 L15
   L16
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:

    LINENUMBER 139 L16
   L17
    LINENUMBER 137 L17
   L18
    LINENUMBER 138 L18
   L19
    LINENUMBER 137 L19
    ALOAD 13
    CHECKCAST java/lang/Iterable
    ASTORE 15
    NOP
   L20
    ICONST_0
    ISTORE 16
   L21
    LINENUMBER 140 L21
    ALOAD 15
    ICONST_0
    ISTORE 17
    NEW com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$lambda$1
    DUP
    INVOKESPECIAL com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$lambda$1.<init> ()V
    CHECKCAST java/util/Comparator
   L22
    LINENUMBER 140 L22
    INVOKESTATIC kotlin/collections/CollectionsKt.sortedWith (Ljava/lang/Iterable;Ljava/util/Comparator;)Ljava/util/List;
    NOP
    GOTO L23
   L23
    CHECKCAST java/lang/Iterable
    ASTORE 15
   L24
    LINENUMBER 138 L24
    NOP
   L25
    ICONST_0
    ISTORE 16
   L26
    LINENUMBER 141 L26
    NEW java/util/HashSet
    DUP
    INVOKESPECIAL java/util/HashSet.<init> ()V
    ASTORE 17
   L27
    LINENUMBER 142 L27
    NEW java/util/ArrayList
    DUP
    INVOKESPECIAL java/util/ArrayList.<init> ()V
    ASTORE 18
   L28
    LINENUMBER 143 L28
    ALOAD 15
    INVOKEINTERFACE java/lang/Iterable.iterator ()Ljava/util/Iterator; (itf)
    ASTORE 19
   L29
    LINENUMBER 143 L29
    ALOAD 19
    INVOKEINTERFACE java/util/Iterator.hasNext ()Z (itf)
    IFEQ L30
    ALOAD 19
    INVOKEINTERFACE java/util/Iterator.next ()Ljava/lang/Object; (itf)
    ASTORE 20
   L31
    LINENUMBER 144 L31
    ALOAD 20
    ASTORE 21
   L32
    ICONST_0
    ISTORE 22
   L33
    ALOAD 21
    CHECKCAST com/xxx/db/entity/FaultEntity
   L34
    LINENUMBER 138 L34
    INVOKEVIRTUAL com/xxx/db/entity/FaultEntity.getDeviceId ()Ljava/lang/String;
    NOP
    GOTO L35
   L35
    ASTORE 21
   L36
    LINENUMBER 145 L36
    ALOAD 17
    ALOAD 21
    INVOKEVIRTUAL java/util/HashSet.add (Ljava/lang/Object;)Z
    IFEQ L37
   L38
    LINENUMBER 146 L38
    ALOAD 18
    ALOAD 20
    INVOKEVIRTUAL java/util/ArrayList.add (Ljava/lang/Object;)Z
    POP
   L37
    LINENUMBER 143 L37
    GOTO L29
   L30
    LINENUMBER 148 L30
    ALOAD 18
    CHECKCAST java/util/List
    NOP
    GOTO L39
   L39
    CHECKCAST java/lang/Iterable
    ASTORE 15
   L40
    LINENUMBER 139 L40
    NOP
   L41
    ICONST_0
    ISTORE 16
   L42
    LINENUMBER 149 L42
    ALOAD 15
    ASTORE 17
    NEW java/util/ArrayList
    DUP
    ALOAD 15
    BIPUSH 10
    INVOKESTATIC kotlin/collections/CollectionsKt.collectionSizeOrDefault (Ljava/lang/Iterable;I)I
    INVOKESPECIAL java/util/ArrayList.<init> (I)V
    CHECKCAST java/util/Collection
    ASTORE 18
   L43
    ICONST_0
    ISTORE 19
   L44
    LINENUMBER 150 L44
    ALOAD 17
    INVOKEINTERFACE java/lang/Iterable.iterator ()Ljava/util/Iterator; (itf)
    ASTORE 20
   L45
    LINENUMBER 150 L45
    ALOAD 20
    INVOKEINTERFACE java/util/Iterator.hasNext ()Z (itf)
    IFEQ L46
    ALOAD 20
    INVOKEINTERFACE java/util/Iterator.next ()Ljava/lang/Object; (itf)
    ASTORE 21
   L47
    LINENUMBER 151 L47
    ALOAD 18
    ALOAD 21
    CHECKCAST com/xxx/db/entity/FaultEntity
    ASTORE 22
    ASTORE 23
   L48
    ICONST_0
    ISTORE 24
   L49
    ALOAD 22
   L50
    LINENUMBER 139 L50
    INVOKESTATIC com/xxx/yyy/alarmalerts/FaultsModelMappingExtentionsKt.toFault (Lcom/xxx/db/entity/FaultEntity;)Lcom/xxx/yyy/alarmalerts/FaultInfo;
    NOP
    GOTO L51
   L51
    ASTORE 25
    ALOAD 23
    ALOAD 25
    INVOKEINTERFACE java/util/Collection.add (Ljava/lang/Object;)Z (itf)
    POP
   L52
    LINENUMBER 150 L52
    GOTO L45
   L46
    LINENUMBER 152 L46
    ALOAD 18
   L53
    CHECKCAST java/util/List
   L54
    LINENUMBER 149 L54
    NOP
    GOTO L55
   L55
   L56
    NOP
    GOTO L57
   L58
   L59
   L57
    ASTORE 26
    ALOAD 11
    ALOAD 26
    ALOAD 28
    ALOAD 28
    ALOAD 0
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$0 : Ljava/lang/Object;
    ALOAD 28
    ALOAD 1
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$1 : Ljava/lang/Object;
    ALOAD 28
    ALOAD 5
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$2 : Ljava/lang/Object;
    ALOAD 28
    ALOAD 8
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$3 : Ljava/lang/Object;
    ALOAD 28
    ALOAD 9
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$4 : Ljava/lang/Object;
    ALOAD 28
    ICONST_1
    PUTFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.label : I
    INVOKEINTERFACE kotlinx/coroutines/flow/FlowCollector.emit (Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; (itf)
   L60
    DUP
    ALOAD 29
    IF_ACMPNE L61
   L62
    LINENUMBER 32 L62
    ALOAD 29
    ARETURN
   L6
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$4 : Ljava/lang/Object;
    CHECKCAST kotlinx/coroutines/flow/FlowCollector
    ASTORE 9
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$3 : Ljava/lang/Object;
    ASTORE 8
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$2 : Ljava/lang/Object;
    ASTORE 5
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$1 : Ljava/lang/Object;
    ASTORE 1
    ALOAD 28
    GETFIELD com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2$1.L$0 : Ljava/lang/Object;
    CHECKCAST com/xxx/yyy/alarmalerts/FaultsRepositoryImpl$getCriticalFaultsFlow$$inlined$map$1$2
    ASTORE 0
   L63
    NOP
    ALOAD 27
    INVOKESTATIC kotlin/ResultKt.throwOnFailure (Ljava/lang/Object;)V
    ALOAD 27
   L61
    LINENUMBER 149 L61
    POP
   L64
    GETSTATIC kotlin/Unit.INSTANCE : Lkotlin/Unit;
    ARETURN
   L65
   L66
   L67
   L7
    NEW java/lang/IllegalStateException
    DUP
    LDC "call to 'resume' before 'invoke' with coroutine"
    INVOKESPECIAL java/lang/IllegalStateException.<init> (Ljava/lang/String;)V
    ATHROW
    RETURN
   L68
    LOCALVARIABLE $this$sortedBy$iv Ljava/lang/Iterable; L20 L23 15
    LOCALVARIABLE $i$f$sortedBy I L21 L23 16
    LOCALVARIABLE receiver Ljava/lang/Object; L32 L35 21
    LOCALVARIABLE $i$a$-unknown-Object I L33 L35 22
    LOCALVARIABLE key$iv Ljava/lang/Object; L36 L37 21
    LOCALVARIABLE e$iv Ljava/lang/Object; L31 L37 20
    LOCALVARIABLE list$iv Ljava/util/ArrayList; L28 L39 18
    LOCALVARIABLE set$iv Ljava/util/HashSet; L27 L39 17
    LOCALVARIABLE $this$distinctBy$iv Ljava/lang/Iterable; L25 L39 15
    LOCALVARIABLE $i$f$distinctBy I L26 L39 16
    LOCALVARIABLE p1 Lcom/xxx/db/entity/FaultEntity; L48 L51 22
    LOCALVARIABLE $i$a$-unknown-FaultsRepositoryImpl$getCriticalFaultsFlow$1$3 I L49 L51 24
    LOCALVARIABLE item$iv$iv Ljava/lang/Object; L47 L52 21
    LOCALVARIABLE $this$mapTo$iv$iv Ljava/lang/Iterable; L43 L53 17
    LOCALVARIABLE destination$iv$iv Ljava/util/Collection; L43 L53 18
    LOCALVARIABLE $i$f$mapTo I L44 L53 19
    LOCALVARIABLE $this$map$iv Ljava/lang/Iterable; L41 L55 15
    LOCALVARIABLE $i$f$map I L42 L55 16
    LOCALVARIABLE faults Ljava/util/List; L14 L59 13
    LOCALVARIABLE continuation Lkotlin/coroutines/Continuation; L14 L59 12
    LOCALVARIABLE $i$a$-map-FaultsRepositoryImpl$getCriticalFaultsFlow$1 I L15 L59 14
    LOCALVARIABLE $i$a$-unsafeTransform-FlowKt__TransformKt$map$1 I L13 L64 10
    LOCALVARIABLE $this$map_u24lambda_u2d4 Lkotlinx/coroutines/flow/FlowCollector; L12 L64 9
    LOCALVARIABLE value Ljava/lang/Object; L12 L64 8
    LOCALVARIABLE $completion Lkotlin/coroutines/Continuation; L12 L64 7
    LOCALVARIABLE $i$a$-collect-FlowKt__EmittersKt$unsafeTransform$1$1 I L11 L64 6
    LOCALVARIABLE value Ljava/lang/Object; L10 L64 5
    LOCALVARIABLE $completion Lkotlin/coroutines/Continuation; L10 L64 4
    LOCALVARIABLE this Lkotlinx/coroutines/flow/FlowKt__TransformKt$map$$inlined$unsafeTransform$1$2; L0 L68 0
    LOCALVARIABLE value Ljava/lang/Object; L0 L68 1
    LOCALVARIABLE $completion Lkotlin/coroutines/Continuation; L8 L65 2
    LOCALVARIABLE $completion Lkotlin/coroutines/Continuation; L8 L66 2
    LOCALVARIABLE $continuation Lkotlin/coroutines/Continuation; L2 L67 28
    LOCALVARIABLE $result Ljava/lang/Object; L3 L67 27
    MAXSTACK = 4
    MAXLOCALS = 30

File is unknown
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.fixRangeOfLvtRecord(CoroutineTransformerMethodVisitor.kt:335)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:813)
	at org.jetbrains.kotlin.codegen.inline.DeferredMethodVisitor.visitEnd(DeferredMethodVisitor.kt:31)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:170)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:192)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:216)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:472)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:77)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:370)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:107)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:77)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethod(AnonymousObjectTransformer.kt:305)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethodAndUpdateGlobalResult(AnonymousObjectTransformer.kt:265)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:152)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:192)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:216)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:472)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:77)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:370)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:107)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:77)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:251)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:146)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCallInner(PsiInlineCodegen.kt:67)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:115)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCall(PsiInlineCodegen.kt:33)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2656)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2598)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:124)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:117)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:393)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.lambda$visitReturnExpression$11(ExpressionCodegen.java:1666)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:67)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:124)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:117)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:393)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:374)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1760)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:86)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:639)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:467)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:249)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:165)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:136)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:196)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:169)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:89)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:128)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:301)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:285)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:616)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:203)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:346)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:102)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:240)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:39)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:601)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: Someone else occupies parameter's slot at 2
	at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.fixRangeOfLvtRecord(CoroutineTransformerMethodVisitor.kt:335)
	at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.fixLvtForParameters(CoroutineTransformerMethodVisitor.kt:329)
	at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.performTransformations(CoroutineTransformerMethodVisitor.kt:201)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:70)
	... 97 more

Caused by: java.lang.AssertionError: Someone else occupies parameter's slot at 2
```

I have tried to change this `map` to `transform` and it works. Is it a expected behavior?

**Comment by qwwdfsad** [comment]
Nope, it seems to be a bug in Kotlin compiler.

Could you please specify the version of Kotlin you are using?

**Comment by DaatSer** [comment]
Ohh, I see, I missed to update `Koltin` version. It was 1.4.10, after the update it built successfully.    
Sorry for my incompetence, have a nice day.
