### ISSUE TITLE
Kotlin/JS Internal Error

### ISSUE THREAD

**Issue by mikeholler** [Kotlin/kotlinx.coroutines#2859]
We encounter the following error when running our tests on Kotlin/JS using the NodeJS runtime. The other runtimes we use (Kotlin/JVM and Kotlin/Native/Linux) both work as expected. Worth noting, we are end-to-end testing suspend functions, and we have to use a custom `runTest` function. The particular suspend function that is failing is a ktor request.

Versions:

```
kotlin: 1.5.21
ktor: 1.6.2
kotlinx-coroutines: 1.5.1-native-mt
```

```
CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.Main, [object Object]]){Cancelled}@1. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
    at Object.captureStack (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/builtins.kt:103:21)
    at CoroutinesInternalError.Error_0 [as constructor] (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/kotlin.js:38896:14)
    at new CoroutinesInternalError (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:2984:13)
    at JobSupport$AwaitContinuation.DispatchedTask.handleFatalException_pr7uss$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:28993:16)
    at JobSupport$AwaitContinuation.DispatchedTask.run (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:28986:10)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:32439:15)
    at /home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:32255:30
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  'message_q7r8iu$_0': "Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.Main, [object Object]]){Cancelled}@1. Please read KDoc to 'handleFatalException' method and report this incident to maintainers",
  'cause_us9j0c$_0': ClassCastException: Illegal cast
      at Object.captureStack (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/builtins.kt:103:21)
      at ClassCastException.Exception [as constructor] (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/kotlin.js:38927:14)
      at ClassCastException.RuntimeException [as constructor] (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/exceptions.kt:35:101)
      at RuntimeException_init_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/exceptions.kt:37:44)
      at new ClassCastException (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/kotlin.js:39083:7)
      at throwCCE_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/js/src/kotlin/exceptionUtils.kt:15:11)
      at JsMainDispatcher.CoroutineDispatcher.releaseInterceptedContinuation_k98bjh$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:2077:88)
      at Coroutine$request_2kdidn$.CoroutineImpl.releaseIntercepted_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/CoroutineImpl.kt:75:48)
      at Coroutine$execute_s9rlw$.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/CoroutineImpl.kt:56:17)
      at SuspendFunctionGun.resumeRootWith_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5730:10)
      at SuspendFunctionGun$continuation$ObjectLiteral.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5835:34)
      at Coroutine$HttpRequestLifecycle$Feature$install$lambda.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/Continuation.kt:54:5)
      at SuspendFunctionGun.resumeRootWith_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5730:10)
      at SuspendFunctionGun$continuation$ObjectLiteral.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5835:34)
      at Coroutine$HttpCallValidator$Companion$install$lambda.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/Continuation.kt:54:5)
      at SuspendFunctionGun.resumeRootWith_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5730:10)
      at SuspendFunctionGun$continuation$ObjectLiteral.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5835:34)
      at Coroutine$execute_s9rlw$_0.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/Continuation.kt:54:5)
      at SuspendFunctionGun.resumeRootWith_0 (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5730:10)
      at SuspendFunctionGun$continuation$ObjectLiteral.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/ktor-ktor-utils-js-legacy/ktor-ktor-utils-js-legacy.js:5835:34)
      at Coroutine$await.CoroutineImpl.resumeWith_tl1gpc$ (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlin/src/kotlin/coroutines/Continuation.kt:54:5)
      at JobSupport$AwaitContinuation.DispatchedTask.run (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:28963:22)
      at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:32439:15)
      at /home/mjholler/Git/multiplatform-sdk/build/js/node_modules/kotlinx-coroutines-core/kotlinx-coroutines-core.js:32255:30
      at processTicksAndRejections (internal/process/task_queues.js:75:11) {
    'message_8yp7un$_0': 'Illegal cast',
    'cause_th0jdv$_0': null
  }
}
```

If helpful, here is the block of code we use to run our tests:

```
val testScope = MainScope()
val testCoroutineContext = testScope.coroutineContext

actual fun runTest(
    block: suspend (scope: CoroutineScope) -> Unit
): dynamic = testScope.promise(
    start = CoroutineStart.UNDISPATCHED,
    context = testCoroutineContext,
) {
    block(this)
}
```

**Comment by qwwdfsad** [comment]
Hi, could you please attach a test that reproduces a problem?

Also, I see `SuspendFunctionGun` in the stacktrace -- this is one of the trickiest places in Ktor. Could you please enable [developer mode](https://ktor.io/docs/development-mode.html) and see if the problem is gone?
