### ISSUE TITLE
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/CoroutineScope;

### ISSUE THREAD

**Issue by xuanguofeng** [Kotlin/kotlinx.coroutines#2870]
An error is reported on a MAC running on the M1 chip

Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.CoroutineScope" on path: DexPathList[[zip file "/data/app/~~Knpto4RysDAoQ9zBJk_rWA==/com.hzhu.m-Hem7x_4hNMQf2yDBOPIugQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Knpto4RysDAoQ9zBJk_rWA==/com.hzhu.m-Hem7x_4hNMQf2yDBOPIugQ==/lib/arm64, /data/app/~~Knpto4RysDAoQ9zBJk_rWA==/com.hzhu.m-Hem7x_4hNMQf2yDBOPIugQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]

**Comment by qwwdfsad** [comment]
Please provide [more additional details](http://testthewebforward.org/docs/bugs.html): the reproducing snippet of code, versions of Kotlin and `kotlinx.coroutines`, and whether it is reproducible on JVM (i.e. in unit test) or only on Android emulator.

Alas, we cannot do much without it

**Comment by xuanguofeng** [comment]
> Please provide [more additional details](http://testthewebforward.org/docs/bugs.html): the reproducing snippet of code, versions of Kotlin and `kotlinx.coroutines`, and whether it is reproducible on JVM (i.e. in unit test) or only on Android emulator.
> 
> Alas, we cannot do much without it

thanks，

    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/CoroutineScope;
        at androidx.lifecycle.ViewModelKt.getViewModelScope(ViewModel.kt:37)
        at com.hzhu.m.ui.logo.SplashViewModel.getVisitorInfo(SplashViewModel.kt:191)
        at com.hzhu.m.ui.logo.SplashViewModel.<init>(SplashViewModel.kt:63)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.hzhu.m.ui.logo.SplashActivity$splashViewModel$2.invoke(SplashActivity.kt:80) 
        at com.hzhu.m.ui.logo.SplashActivity$splashViewModel$2.invoke(SplashActivity.kt:79) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.hzhu.m.ui.logo.SplashActivity.getSplashViewModel(SplashActivity.kt:79) 
        at com.hzhu.m.ui.logo.SplashActivity.bindViewModel(SplashActivity.kt:401) 
        at com.hzhu.m.ui.logo.SplashActivity.onCreate(SplashActivity.kt:101) 
        at android.app.Activity.performCreate(Activity.java:7994) 
        at android.app.Activity.performCreate(Activity.java:7978) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.CoroutineScope" on path: DexPathList[[zip file "/data/app/~~VZwPnuO6CyBprOhDV7IjEA==/com.hzhu.m-VAGhFQykQmYzhoeGnXqTKA==/base.apk"],nativeLibraryDirectories=[/data/app/~~VZwPnuO6CyBprOhDV7IjEA==/com.hzhu.m-VAGhFQykQmYzhoeGnXqTKA==/lib/arm64, /data/app/~~VZwPnuO6CyBprOhDV7IjEA==/com.hzhu.m-VAGhFQykQmYzhoeGnXqTKA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.lifecycle.ViewModelKt.getViewModelScope(ViewModel.kt:37) 
        at com.hzhu.m.ui.logo.SplashViewModel.getVisitorInfo(SplashViewModel.kt:191) 
        at com.hzhu.m.ui.logo.SplashViewModel.<init>(SplashViewModel.kt:63) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.hzhu.m.ui.logo.SplashActivity$splashViewModel$2.invoke(SplashActivity.kt:80) 
        at com.hzhu.m.ui.logo.SplashActivity$splashViewModel$2.invoke(SplashActivity.kt:79) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.hzhu.m.ui.logo.SplashActivity.getSplashViewModel(SplashActivity.kt:79) 
        at com.hzhu.m.ui.logo.SplashActivity.bindViewModel(SplashActivity.kt:401) 
        at com.hzhu.m.ui.logo.SplashActivity.onCreate(SplashActivity.kt:101) 
        at android.app.Activity.performCreate(Activity.java:7994) 
        at android.app.Activity.performCreate(Activity.java:7978) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 


that's the error message，Mainly to use viewModelScope or Dispatchers , use kotlinx-coroutines-android and kotlinx-coroutines-core in version 1.3.9，version 1.5.1 has the same problem。 

thanks

**Comment by qwwdfsad** [comment]
Tried to reproduce it in pure Kotlin on M1 and failed. The issue seems to be Android-toolchain related. Could you please re-report this issue to the corresponding Google issue tracker?

**Comment by xuanguofeng** [comment]
> Tried to reproduce it in pure Kotlin on M1 and failed. The issue seems to be Android-toolchain related. Could you please re-report this issue to the corresponding Google issue tracker?

thanks，May I ask how to give feedback to Google Issue Tracker?

**Comment by qwwdfsad** [comment]
https://developers.google.com/issue-tracker, Android Public Tracker in `https://issuetracker.google.com/`
