### ISSUE TITLE
Missing package-list files in documentation

### ISSUE THREAD

**Issue by as-com** [Kotlin/kotlinx.coroutines#290]
For example, if I configure Dokka with this:
```groovy
	externalDocumentationLink {
		url = new URL("https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/")
	}
```
... it complains about a missing package-list:
```
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/, packageListUrl=https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:27)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:27)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:13)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:13)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:12)
    while locating org.jetbrains.dokka.PackageDocs
  
  1 error
```

**Comment by elizarov** [comment]
Thanks. Good catch. We need to fix build script for the `site` module to copy the package lists files to the jekyll output folder.

**Comment by snicoll** [comment]
@elizarov this is still 404ing for us.

**Comment by qwwdfsad** [comment]
At some point, Java migrated from per-module package-lists to multimodule package-list: https://docs.oracle.com/en/java/javase/12/docs/api/element-list

Dokka (=> `kotlinx.coroutines` as well) did the same and now we only provide a multimodule list: https://kotlin.github.io/kotlinx.coroutines/package-list

We're discussing whether we should provide an additional per-module package-lists right now

**Comment by qwwdfsad** [comment]
We decided to keep it as is for a while
