### ISSUE TITLE
java.lang.VerifyError crash in android 4.4 devices 

### ISSUE THREAD

**Issue by Harshal624** [Kotlin/kotlinx.coroutines#2931]
So I recently updated the coroutines core library from 1.2.1 to 1.4.1 
I am using these libraries 
"androidx.lifecycle:lifecycle-runtime-ktx:2.2.0"
"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"
"org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.0"

Kotlin version: 1.3.72

Since then I've been noticing a lot of crashes on crashlytics for android 4.4 devices (4.4.2 and 4.4.4)

Here's the stack trace:

Fatal Exception: java.lang.VerifyError: k/a/a
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_commonKt.java:55)
       at kotlinx.coroutines.BuildersKt.launch(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_commonKt.java:49)
       at kotlinx.coroutines.BuildersKt.launch$default(BuildersKt.java:1)
       at androidx.lifecycle.LifecycleCoroutineScopeImpl.register(LifecycleCoroutineScopeImpl.java:117)
       at androidx.lifecycle.LifecycleKt.getCoroutineScope(LifecycleKt.java:47)
       at androidx.lifecycle.LifecycleOwnerKt.getLifecycleScope(LifecycleOwnerKt.java:30)
       at com.intouchapp.home.FeedFragment.setUpFeedStatusObserver(FeedFragment.java:639)
       at com.intouchapp.home.FeedFragment.onViewCreated(FeedFragment.java:162)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:238)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:16749)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1413)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:696)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:589)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2439)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2072)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1175)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5996)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by 1014277960** [comment]
I got the same crash in 4.4

![image](https://user-images.githubusercontent.com/14831466/133747950-599cd2b3-d11a-414c-8fb4-18b110d832f1.png)
According to the log above, I find the reason.

In CompletedExceptionally.class, the method "getHandled" returns a boolean value, and an Int type variable "_handle" is returned internally. Because this method is simple and has no side effects，Proguard inline this method at all call points.
This will cause the original call to this method to become the acquisition of the "_handle" variable, and the type is changed from boolean to int, resulting in failure to pass the verification on the 4.x model.
![image](https://user-images.githubusercontent.com/14831466/133748823-1dd7b569-b31d-4c61-9be6-58e8d26fb0f4.png)
![image](https://user-images.githubusercontent.com/14831466/133749946-a9a56fb2-873f-4b1a-9aab-944602359af5.png)

CompletedExceptionally.class is just one of the problematic classes. The solution is to add a keep rule to keep all the problematic classes. The following is my keep rule

> -keep class kotlinx.coroutines.CompletedExceptionally {*;}
-keep class kotlinx.coroutines.flow.ChannelAsFlow {*;}
-keep class kotlinx.coroutines.JobSupport$Finishing {*;}
-keep class kotlinx.coroutines.scheduling.CoroutineScheduler {*;}
-keep class kotlinx.coroutines.EventLoopImplBase {*;}

**Comment by Harshal624** [comment]
> I got the same crash in 4.4
> 
> ![image](https://user-images.githubusercontent.com/14831466/133747950-599cd2b3-d11a-414c-8fb4-18b110d832f1.png)
> According to the log above, I find the reason.
> 
> In CompletedExceptionally.class, the method "getHandled" returns a boolean value, and an Int type variable "_handle" is returned internally. Because this method is simple and has no side effects，Proguard inline this method at all call points.
> This will cause the original call to this method to become the acquisition of the "_handle" variable, and the type is changed from boolean to int, resulting in failure to pass the verification on the 4.x model.
> ![image](https://user-images.githubusercontent.com/14831466/133748823-1dd7b569-b31d-4c61-9be6-58e8d26fb0f4.png)
> ![image](https://user-images.githubusercontent.com/14831466/133749946-a9a56fb2-873f-4b1a-9aab-944602359af5.png)
> 
> CompletedExceptionally.class is just one of the problematic classes. The solution is to add a keep rule to keep all the problematic classes. The following is my keep rule
> 
> > -keep class kotlinx.coroutines.CompletedExceptionally {*;}
> > -keep class kotlinx.coroutines.flow.ChannelAsFlow {*;}
> > -keep class kotlinx.coroutines.JobSupport$Finishing {*;}
> > -keep class kotlinx.coroutines.scheduling.CoroutineScheduler {*;}
> > -keep class kotlinx.coroutines.EventLoopImplBase {*;}

Will try this solution

**Comment by qwwdfsad** [comment]
This seems to be an Android-related issue on the edge of R8/ProGuard compiler and older devices verification.
Please file a bug to Google bugtracker. 

>In CompletedExceptionally.class, the method "getHandled" returns a boolean value, and an Int type variable "_handle" is returned internally.

This is perfectly valid behaviour for coroutines and Java libraries. Java **language** has the notion of `boolean` type, but on the bytecode level booleans are limited and compilers use ints to represent booleans.

E.g. the code:
```
fun foo() = true
```

will be compiled to 

```
public final static foo()Z
L0
LINENUMBER 9 L0
ICONST_1 // Push *integer* 1
IRETURN // Use integer return instruction
L1
MAXSTACK = 1
MAXLOCALS = 0
```
which is perfectly valid Java bytecode
