### ISSUE TITLE
IllegalStateException at SafeContinuation.resumeWith

### ISSUE THREAD

**Issue by sujittayde** [Kotlin/kotlinx.coroutines#2940]
Hi, we are getting IllegalStateException at SafeContinuation.resumeWith on our android app on production. It is hard to reproduce the issue, but we are getting it periodically in production.
- Devices : samsung, LGE, motorola, Oneplus
- OS versions : 9-10
- Firebase BOM version used : 28.1.0 
- Kotlin version used : 1.5.21
- Coroutines version used : 1.5.0
- Stack trace
Fatal Exception: java.lang.IllegalStateException: Already resumed
       at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuation.java:44)
       at <our Class>r$<our method>$2$1$invokeSuspend$$inlined$collect$1.emit(<our Class>.java:135)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:15)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:15)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:77)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:59)
       at <our Class>$<our method>$2$invokeSuspend$$inlined$collect$1.emit(<our Class>.java:135)
       at <our Class>$<our method>$2$invokeSuspend$$inlined$filter$1$2.emit(<our Class>.java:137)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:15)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:15)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:77)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:59)
       at <our Class>$<our method>$$inlined$transform$1$1.emit(<our Class>.java:136)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(FlowKt__ChannelsKt.java:62)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl(FlowKt__ChannelsKt.java:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(FlowKt__ChannelsKt.java:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by qwwdfsad** [comment]
`kotlinx.coroutines` does not use `SafeContinutation` at all.

It seems like you have a bug in your applcation in `suspendCoroutine` call at line `r$$2$1$invokeSuspend$$inlined$collect$1.emit(.java:135)` with calling `resume` on it twice
