### ISSUE TITLE
Exception handling of coroutine CompletableFuture doesn't work as expected

### ISSUE THREAD

**Issue by jameslan** [Kotlin/kotlinx.coroutines#2949]
The code

```kt
package james.exp.kotlin.coroutines

import kotlinx.coroutines.delay
import kotlinx.coroutines.future.await
import kotlinx.coroutines.future.future
import kotlinx.coroutines.runBlocking
import java.lang.Thread.sleep
import java.util.concurrent.CompletableFuture

fun main() = runBlocking {
    println(System.currentTimeMillis())
    val future1 = CompletableFuture.supplyAsync<String> {
        sleep(1000)
        val e = RuntimeException("exception future1")
        throw e
    }
    printFuture(future1)
    println(System.currentTimeMillis())
    val future2 = future<String> {
        delay(1000)
        val e = RuntimeException("exception future2")
        throw e
    }
    printFuture(future2)
    println(System.currentTimeMillis())
    val future3 = CompletableFuture.supplyAsync<String> {
        sleep(1000)
        val e = RuntimeException("exception future3")
        throw e
    }
    printFuture(future3)
    println(System.currentTimeMillis())
}

suspend fun printFuture(future: CompletableFuture<String>) {
    try {
        println(future.await())
    } catch (e: Throwable) {
        println(e)
    }
}
```
generates the output

```
1632433419004
java.lang.RuntimeException: exception future1
1632433420015
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@64729b1e
1632433421022
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@64729b1e
1632433421022
Exception in thread "main" java.lang.RuntimeException: exception future2
	at james.exp.kotlin.coroutines.CoMainKt$main$1$future2$1.invokeSuspend(CoMain.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:489)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at james.exp.kotlin.coroutines.CoMainKt.main(CoMain.kt:10)
	at james.exp.kotlin.coroutines.CoMainKt.main(CoMain.kt)
```

The `future1` works as expected, it sleeps for 1s, and the `await` rethrows the exception.
The `future2` wraps the exception with a `JobCancellationException`. Is this by design? Is there a way that the caller of the future could get the original exception without being aware of `CancellationException`? The framework I am using relies on the specific exception to return HTTP error code.
Awaiting the `future3` throws the same exception, instead of a new one, with `future2`, although its implementation is the same with `future1`.

The exception thrown in `future3`, seems to be uncaught, though.

PS, I am writing a converter, similar to `kotlinx-coroutines-jdk8`, for other async primitives, and ran into the same issue.

**Comment by dkhalanskyjb** [comment]
The reason for this is that throwing inside `future` also cancels the `CoroutineScope` in which it is launched. In your case, it's the scope created in `runBlocking`; this leads to calls to `await` being cancelled. The problem can be fixed by creating a new scope for the future to run in.
```kotlin
runBlocking {
    val scope = CoroutineScope(Dispatchers.Default) // change №1 here
    println(System.currentTimeMillis())
    val future1 = CompletableFuture.supplyAsync<String> {
        sleep(1000)
        val e = RuntimeException("exception future1")
        throw e
    }
    printFuture(future1)
    println(System.currentTimeMillis())
    val future2 = scope.future<String> { // change №2 here
        delay(1000)
        val e = RuntimeException("exception future2")
        throw e
    }
    printFuture(future2)
    println(System.currentTimeMillis())
    val future3 = CompletableFuture.supplyAsync<String> {
        sleep(1000)
        val e = RuntimeException("exception future3")
        throw e
    }
    printFuture(future3)
    println(System.currentTimeMillis())
}
```

**Comment by jameslan** [comment]
Thank you @dkhalanskyjb!. This cancellation by exception is not very clearly stated in the coroutines' doc. Using a `SupervisorJob()` as the parameter of `future()` could handle this.
