### ISSUE TITLE
java.lang.IllegalStateException: Inconsistent state CancellableContinuation {Completed}

### ISSUE THREAD

**Issue by diksha** [Kotlin/kotlinx.coroutines#2961]
```
[java.lang.IllegalStateException: Inconsistent state CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at com.zoox.box.data.clients.ApplicationClient$createBodyTelltaleDataFlow$dataActor$1.invokeSuspend(ApplicationClient.kt:87)@ef85b17]){Completed}@649fb04
	at kotlinx.coroutines.internal.DispatchedContinuation.claimReusableCancellableContinuation(DispatchedContinuation.kt:129)
	at kotlinx.coroutines.CancellableContinuationKt.getOrCreateCancellableContinuation(CancellableContinuation.kt:353)
	at kotlinx.coroutines.channels.AbstractChannel$Itr.hasNextSuspend(AbstractChannel.kt:1133)
	at kotlinx.coroutines.channels.AbstractChannel$Itr.hasNext(AbstractChannel.kt:841)
	at com.zoox.box.data.clients.ApplicationClient$createBodyTelltaleDataFlow$dataActor$1.invokeSuspend(ApplicationClient.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)](url)
```

I received this crash while using dataActor. Here is my sample code

```
private fun createBodyDataFlow(): MutableStateFlow<BodyData?> {
        val newBodyDataFlow = MutableStateFlow<BodyData?>(null)

        val dataActor = actor<BodyFeedbackOuterClass.BodyFeedback>(
            coroutineContext,
            capacity = Channel.CONFLATED
        ) {
            for (bodyFeedback in channel) {
                val transformedBodyFeedback =
                    bodyFeedback.transform(vehicleInterface.hmiQuadrant)
                bodyFeedback.logIncomingMessage(logger, vehicleInterface.hmiQuadrant)

                newBodyDataFlow.value = transformedBodyFeedback
                lastSuccessfulBodyMessage = System.currentTimeMillis()
                bodyMessageStatus.applyUpdate(
                    ComponentType.BODY,
                    logger,
                    ComponentStatus.OK
                )
            }
        }

        vehicleInterface.setBodyInterfaceCallback { bodyFeedback ->
            dataActor.trySend(bodyFeedback)
        }

        return newBodyDataFlow
    }
```

The message says that the CancellableContinuation is {Completed}. Why am I still facing an issue then?
Can someone help, I am unable to understand why I might be facing this error

**Comment by qwwdfsad** [comment]
Could you please specify which version of `kotlinx.coroutines` you are using and whether the bug reproducer on a regular basis or the crash happens rarely?

**Comment by diksha** [comment]
We only have a few instances of application running. 
So, ihappens rarely.
            const val coroutines = "1.5.1"
This is the coroutine version I am using.
