### ISSUE TITLE
JS silently crashing under highly obscure conditions

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.coroutines#2988]
```kotlin
    fun promiseCrashing(): Promise<Unit> {
        val block: suspend (suspend () -> Unit).() -> Unit = {
            assertFailsWith<IllegalStateException> {
                this()
            }
        }
        val test = {
            GlobalScope.promise {
                throw IllegalStateException()
            }
        }
        return GlobalScope.promise {
            block {
                test().await()
            }
        }
    }
```
crashes due to unfulfilled `assertFailsWith` and also spews the following into logs:
```
{ CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[NodeDispatcher@2, [object Object]]){Cancelled}@5. Please read KD
oc to 'handleFatalException' method and report this incident to maintainers
    at Object.captureStack (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/src/kotlin/builtins.kt:103:21)
    at CoroutinesInternalError.Error_0 [as constructor] (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlin.js:38897:14)
    at new CoroutinesInternalError (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-core.js:2982:13)
    at CancellableContinuationImpl.DispatchedTask.handleFatalException_pr7uss$ (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutin
es-core.js:28933:16)                                                                                                                                                                  
    at CancellableContinuationImpl.DispatchedTask.run (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-core.js:28926:10)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-
core.js:32303:15)                                                                                                                                                                     
    at /home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-core.js:32119:30                  
    at _combinedTickCallback (internal/process/next_tick.js:131:7)                                                                                                                    
    at process._tickCallback (internal/process/next_tick.js:180:9)                                                                                                                    
  'message_q7r8iu$_0': 'Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[NodeDispatcher@2, [object Object]]){Cancelled}@5. Please read KDoc 
to \'handleFatalException\' method and report this incident to maintainers',                                                                                                          
  'cause_us9j0c$_0':                                                                                                                                                                  
   { ClassCastException: Illegal cast                                                      
    at Object.captureStack (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/src/kotlin/builtins.kt:103:21)
    at ClassCastException.Exception [as constructor] (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlin.js:38928:14)
    at ClassCastException.RuntimeException [as constructor] (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/src/kotlin/exceptions.kt:35:101)
    at RuntimeException_init_0 (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/src/kotlin/exceptions.kt:37:44)
    at new ClassCastException (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlin.js:39084:7)
    at throwCCE_0 (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/js/src/kotlin/exceptionUtils.kt:15:11)
    at NodeDispatcher.CoroutineDispatcher.releaseInterceptedContinuation_k98bjh$ (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-corout
ines-core.js:2046:88)
    at Coroutine$PromiseTest$promiseCrashing$lambda_0.CoroutineImpl.releaseIntercepted_0 (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/src/ko
tlin/coroutines/CoroutineImpl.kt:75:48)                                                                                                                                               
    at Coroutine$PromiseTest$promiseCrashing$lambda$lambda_0.CoroutineImpl.resumeWith_tl1gpc$ (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/s
rc/kotlin/coroutines/CoroutineImpl.kt:56:17)
    at CancellableContinuationImpl.DispatchedTask.run (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-core.js:28903:22)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-
core.js:32303:15)                         
    at /home/dmitry.khalanskiy/Coroutines/Project/kotlinx-coroutines-test/build/node_modules/kotlinx-coroutines-core.js:32119:30
    at _combinedTickCallback (internal/process/next_tick.js:131:7)                                                                                                                    
    at process._tickCallback (internal/process/next_tick.js:180:9)   
     'message_8yp7un$_0': 'Illegal cast',                                                                                                                                             
     'cause_th0jdv$_0': null,
     name: 'ClassCastException' },
  name: 'CoroutinesInternalError' }  
```
Looking at the code now, I see that it's also unclear why it works at all; it probably shouldn't. Fixing it as follows, however, doesn't fix the error.
```kotlin
    fun promiseCrashing(): Promise<Unit> {
        val block: suspend (suspend () -> Unit) -> Unit = {
            assertFailsWith<IllegalStateException> {
                it()
            }
        }
        val test = {
            GlobalScope.promise {
                throw IllegalStateException()
            }
        }
        return GlobalScope.promise {
            block {
                test().await()
            }
        }
    }
```
As a bonus, my initial reproducer looked as follows:
```kotlin
    fun promiseCrashing(): TestResult {
        fun testResultMap(block: suspend (suspend () -> Unit).() -> Unit, test: () -> TestResult): TestResult {
            return GlobalScope.promise {
                block {
                    println("before await")
                    val result = test().await()
                    println("after await: $result")
                }
            }
        }
        return testResultMap({
            assertFailsWith<IllegalStateException> {
                this()
            }
        }) {
            GlobalScope.promise {
                throw IllegalStateException()
            }
        }
    }
```
Attempting "inline the function" refactoring led to disappointing results. I'll need to report all of this to the proper issue trackers eventually.

**Comment by qwwdfsad** [comment]
JS legacy is deprecated, we'll remove and the issue won't be relevant
