### ISSUE TITLE
GlobalScope.launch cause ANR coroutines-1.3.5

### ISSUE THREAD

**Issue by vzhilong** [Kotlin/kotlinx.coroutines#2994]
Here is my code:
`
GlobalScope.launch(ThreadPoolExecutor(xxxxx).asCoroutineDispatcher()) {
    //do something
}
`

And there is a lot of ANRs feedback:
`
com.xyz.androidcrashhandler.anr.ANRError: Application Not Responding for at least 5000 ms.
Caused by: com.yz.androidcrashhandler.anr.ANRError$$$_Thread: main (state = RUNNABLE)
	at kotlinx.coroutines.CoroutineContextKt.createDefaultDispatcher(CoroutineContextKt.java:0)
	at kotlinx.coroutines.Dispatchers.<clinit>(Dispatchers.java:0)
	at kotlinx.coroutines.CoroutineContextKt.newCoroutineContext(CoroutineContextKt.java:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_commonKt.java:0)
	at kotlinx.coroutines.BuildersKt.launch(BuildersKt.java:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_commonKt.java:0)
	at kotlinx.coroutines.BuildersKt.launch$default(BuildersKt.java:0)
	at com.yz.android.utils.ImageUtils.clearCache(ImageUtils.java:0)

`

We use 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5', and the kotlin version is "1.3.71"

**Comment by qwwdfsad** [comment]
It seems like a random fluctuation: `createDefaultDispatcher` doesn't do anything beyond the allocation of a few simple objects. Even threads are not created.

It's okay to reopen this issue with a stable reproducer, then we will be able to take a look and bisect the root cause
