### ISSUE TITLE
Promise.await() causes ClassCastException

### ISSUE THREAD

**Issue by brianguertin** [Kotlin/kotlinx.coroutines#3009]
Kotlin 1.5.31
Coroutines 1.5.2-native-mt

Given the following:
```kotlin
external interface BwipJs {
   fun toCanvas(canvas: HTMLCanvasElement)
}
external fun <Module : Any> import(path: String): Promise<Module>

```

The following code causes a ClassCastException:
```kotlin
GlobalScope.launch {
  import<BwipJs>("bwip-js").await()
}}
```

While this code witout coroutines works fine:
```kotlin
val canvas = document.createElement("canvas") as HTMLCanvasElement
import<BwipJs>("bwip-js").then { bwipjs ->
    bwipjs.toCanvas(canvas)
}
```

I suspect the issue would be the same regardless of what JS module is being loaded, but in this case I'm using https://github.com/metafloor/bwip-js

```
ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/combined-jgosdk.js:32134:11)
    at toState (webpack-internal:///./kotlin/combined-jgosdk.js:37552:87)
    at CancellableContinuationImpl.resumeWith_bnunh2_k$ (webpack-internal:///./kotlin/combined-jgosdk.js:37052:15)
    at _no_name_provided__129.invoke_iav7o_k$ (webpack-internal:///./kotlin/combined-jgosdk.js:53075:44)
    at eval (webpack-internal:///./kotlin/combined-jgosdk.js:53114:9)
```

**Comment by qwwdfsad** [comment]
Thanks! It definitely is a compiler bug, so filed https://youtrack.jetbrains.com/issue/KT-49601

**Comment by ivakub** [comment]
@brianguertin I failed to reproduce the problem. Can you attach a sample project?
