### ISSUE TITLE
`DumpCoroutineInfoAsJsonAndReferencesTest.testDumpWithNoCoroutines` spuriously fails on Mac OS X

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3028]
```
java.util.NoSuchElementException
	at kotlinx.coroutines.debug.internal.ConcurrentWeakMap$Core$KeyValueIterator.next(ConcurrentWeakMap.kt:232)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1313)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1071)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.dumpCoroutinesInfo(DebugProbesImpl.kt:643)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.dumpCoroutinesInfoAsJsonAndReferences(DebugProbesImpl.kt:186)
	at kotlinx.coroutines.debug.DumpCoroutineInfoAsJsonAndReferencesTest.testDumpWithNoCoroutines(DumpCoroutineInfoAsJsonAndReferencesTest.kt:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at kotlinx.coroutines.debug.junit4.CoroutinesTimeoutStatement$evaluate$$inlined$runWithTimeoutDumpingCoroutines$1.call(CoroutinesTimeoutImpl.kt:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by qwwdfsad** [comment]
Interested part of `toList`:

```
return when (size) {
            0 -> emptyList()
            1 -> listOf(if (this is List) get(0) else iterator().next())
            else -> this.toMutableList()
        }
```

Seems like in some circumstances `toList` is able to observe size being `1`

**Comment by qwwdfsad** [comment]
Fixed
