### ISSUE TITLE
ClassNotFoundException: com.sun.javafx.application.PlatformImpl

### ISSUE THREAD

**Issue by JJChill** [Kotlin/kotlinx.coroutines#3036]
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.application.PlatformImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at kotlinx.coroutines.javafx.PlatformInitializer.<clinit>(JavaFxDispatcher.kt:140)

I'm trying to run my compiled code on linux where I have openjdk 8. I understand that javafx is not included in openjdk but I've included the javafx plugin in gradle as well as specifying the javafx modules. But I still get the error above. I'm not sure what else I'm supposed to do to get javafx setup properly.

**Comment by dkhalanskyjb** [comment]
Try installing `openjfx`. Also, please use StackOverflow or the Slack channel for general questions.
