### ISSUE TITLE
StackOverflow when toString called.

### ISSUE THREAD

**Issue by SunJenry** [Kotlin/kotlinx.coroutines#3045]
Below is what showed in **trace.txt** when I got an ANR. 
Corountine Version:1.4.3

`  at java.lang.Throwable.nativeFillInStackTrace(Native method)
  at java.lang.Throwable.fillInStackTrace(Throwable.java:775)
  - locked <0x09651cc7> (a java.lang.NoSuchFieldException)
  at java.lang.Throwable.<init>(Throwable.java:258)
  at java.lang.Exception.<init>(Exception.java:66)
  at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
  at java.lang.NoSuchFieldException.<init>(NoSuchFieldException.java:50)
  at java.lang.Class.getDeclaredField(Native method)
  at kotlin.coroutines.jvm.internal.DebugMetadataKt.getLabel(DebugMetadata.kt:1)
  at kotlin.coroutines.jvm.internal.DebugMetadataKt.getStackTraceElement(DebugMetadata.kt:3)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.getStackTraceElement(ContinuationImpl.kt:1)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.toString(ContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.q0.c(DebugStrings.kt:2)
  at k.a.z2.i.toString(DispatchedContinuation.kt:1)
  at k.a.q0.c(DebugStrings.kt:1)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)

 ... thounds of  repeat lines...
  
  at k.a.j2.toString(JobSupport.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.c1.toString(CancellableContinuation.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.x.toString(CancellableContinuationImpl.kt:-1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at k.a.k.toString(CancellableContinuationImpl.kt:1)
  at java.lang.String.valueOf(String.java:2827)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:6694)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)`

**Comment by qwwdfsad** [comment]
Could you please elaborate on how often it occurs or what's the caller code is like?
Also, I would recommend updating to 1.5.0 where `CancellableContinuation` internals along with `toString` were reworked

**Comment by SunJenry** [comment]
> 

Only happened once in the past one year. I got the `trace.txt` from crash track service, the message above is all I known, so I have no idea what's the caller code.
Thank's a lot, I will try to update to 1.5.0.
