### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException (Flow has more than one element)

### ISSUE THREAD

**Issue by joaoeudes7** [Kotlin/kotlinx.coroutines#3057]
I get this error, and it doesn't show a path related to my code in StackTrace, I believe it's related to Flow

StackTrace: 
```
Fatal Exception: java.lang.IllegalArgumentException: Flow has more than one element
       at kotlinx.coroutines.flow.FlowKt__ReduceKt$single$$inlined$collect$1.emit(FlowKt__ReduceKt.java:135)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:15)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:77)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:59)
       at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.java:123)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by fvasco** [comment]
Did you read the [official documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/single.html)?

**Comment by joaoeudes7** [comment]
Yeah, i know, but not show stack trace with my code, is some in `androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.java:123`?

**Comment by qwwdfsad** [comment]
Unfortunately, stacktraces are internal details of how coroutines are implemented.

You can copy the stacktrace to the clipboard and in IDEA go to `Code -> Analyze stacktrace or thread dump` and then IDEA will match this stacktrace with your actual source and will navigate you to it
