### ISSUE TITLE
Multiple issues with `runTest` RC2 (`triple x86_64-unknown-linux-gnu` and `Timeout of 2000ms exceeded`)

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx.coroutines#3077]
On my Windows machine I am getting

```
> Task :semver-core:linkDebugTestLinuxX64 FAILED
e: Compilation failed: Cannot get target from triple x86_64-unknown-linux-gnu.
```

On CI, in Ubuntu, test are failing with a timeout issue:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Not sure why 2000ms, because default timeout is

```
internal const val DEFAULT_DISPATCH_TIMEOUT_MS = 60_000L
```

Everything is working with a default implementation based on `runBlocking`

Repo: https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp/pull/50
Run: https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp/actions/runs/1564278641

**Comment by joffrey-bion** [comment]
@JavierSegoviaCordoba the timeout problem probably only occurs for JS tests. This is due to Mocha, not Kotlin's test framework. I also find this confusing to be honest.

If you need a bigger timeout, you can change it in the Gradle configuration this way:

```kotlin
kotlin {
    ...
    js {
        nodejs {
            testTask {
                useMocha {
                    timeout = "10s"
                }
            }
        }
        browser {
            testTask {
                useMocha {
                    timeout = "10s"
                }
            }
        }
    }
    ...
}
```

**Comment by dkhalanskyjb** [comment]
> Everything is working with a default implementation based on `runBlocking`

The implementation that you were using before is this:
https://github.com/JavierSegoviaCordoba/run-blocking-kmp/blob/main/suspend-test/jsMain/kotlin/SuspendTest.kt This implementation does not work well: it only launches a `Promise` but does not *return* it. If a test *returns* a promise, the JS test frameworks handle this situation specifically and will wait for the promise to complete. Sometimes those test frameworks have their own timeouts for this, like the one you witness here. If you just *launch* a promise, but do not return it or wait for it in the test, the test framework will happily think that the test has finished immediately, even though in fact it hasn't yet started to execute. It's possible to lose some error messages this way, so it's possible that some tests have been silently failing.

**Comment by JavierSegoviaCordoba** [comment]
Fixed with mocha timeout, `triple` error is gone without changing anything, maybe temporal error. Thank you all :)

**Comment by JavierSegoviaCordoba** [comment]
I am going to re-open it, I am getting the `triple` issue in my Windows 10 machine.

And another one:

```
Task :run-blocking-all:compileNativeMainKotlinMetadata FAILED
e: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/cli/common/config/KotlinSourceRoot
        at org.jetbrains.kotlin.cli.common.config.ContentRootsKt.addKotlinSourceRoot(ContentRoots.kt:20)

...


Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.cli.common.config.KotlinSourceRoot
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:460)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 156 more
Caused by: java.io.IOException: The handle is invalid
        at java.base/java.io.RandomAccessFile.seek0(Native Method)
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
        at java.base/java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1314)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1003)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1018)
        at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
        at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:124)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        ... 161 more
```

For some reason, in CLI there is no issue but it is really weird to get this error, and even doing a clean plus deleting the `.konan` folder still I have those issues.

**Comment by dkhalanskyjb** [comment]
I don't see any indication of this error being related to kotlinx-coroutines, and especially to `runTest`.
