### ISSUE TITLE
Flow.first() throws java.util.NoSuchElementException: Expected at least one element , without meaningful stacktrace to track down

### ISSUE THREAD

**Issue by jkpelo** [Kotlin/kotlinx.coroutines#3098]
java.util.NoSuchElementException: Expected at least one element         at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(FlowKt__ReduceKt:96)         at kotlinx.coroutines.flow.FlowKt.first(FlowKt:1)         at kotlinx.coroutines.flow.FlowKt.first(FlowKt:1)         at kotlinx.coroutines.flow.FlowKt__ReduceKt$first$1.invokeSuspend(Unknown:13)         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl:33)         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask:106)         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler:571)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler:750)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler:678)         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler:665)

Exception thrown here: https://github.com/Kotlin/kotlinx.coroutines/blob/65e1b84f742a4fff14c67a11a873a4977a0ba539/kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt#L96

**Comment by jkpelo** [comment]
We're seeing a whole bunch of instances of these in a recent build, and I am wondering if this is a bug or bad usage. The one thing that makes debugging / understanding this difficult is that we can't find out where this happens, as the stacktrace we get from error reporting is the above.

**Comment by hoc081098** [comment]
Check if your Flow is empty :))

**Comment by jkpelo** [comment]
If I only know which flow this is :)

**Comment by hoc081098** [comment]
Can you add some code to reproduce?

**Comment by jkpelo** [comment]
The problem is that I don't know which call to .first() causes this. This happens in a large code base with many instances of .first(). It's possible that the problem here is that the stacktrace posted above is not the original one ( I got this from a bug tracking tool). I will look into this. 

If I run the following to trigger the same exception,:

```
    suspend fun badEmptyFlow() = withContext(Dispatchers.IO) {
        val flow = emptyList<String>().asFlow()
        flow.first()
    }
```
the resulting stacktrace looks like this: ( which is different from the above ^^  )
```
java.util.NoSuchElementException: Expected at least one element
    at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:96)
    at kotlinx.coroutines.flow.FlowKt.first(Unknown Source:1)
    at com.myapp.SomeFragmentViewModel$consumeFlow$2.invokeSuspend(SomeFragmentViewModel.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by dkhalanskyjb** [comment]
You can enable the `kotlinx.coroutines.debug` system property for more detailed stack traces:
```kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

suspend fun badEmptyFlow() = withContext(Dispatchers.IO) {
    val flow = emptyList<String>().asFlow()
    flow.first()
}

suspend fun main() {
    System.setProperty("kotlinx.coroutines.debug", "on")
    println(badEmptyFlow())
}
```
produces the following for me:
```
Exception in thread "main" java.util.NoSuchElementException: Expected at least one element
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:96)
	at kotlinx.coroutines.flow.FlowKt.first(Unknown Source)
	at Reproduce3098Kt$badEmptyFlow$2.invokeSuspend(Reproduce3098.kt:7)
	(Coroutine boundary)
	at Reproduce3098Kt.main(Reproduce3098.kt:12)
Caused by: java.util.NoSuchElementException: Expected at least one element
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:96)
	at kotlinx.coroutines.flow.FlowKt.first(Unknown Source)
	at Reproduce3098Kt$badEmptyFlow$2.invokeSuspend(Reproduce3098.kt:7)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

However, we use special symbols to display this neatly (https://github.com/Kotlin/kotlinx.coroutines/issues/2291), and some tooling takes issue with that. So, the bug tracking tools could have stripped part of the information.

**Comment by jkpelo** [comment]
Thanks @dkhalanskyjb , this is enlightening.

**Comment by dkhalanskyjb** [comment]
Great! Do you have any other questions/remarks, or can we close the issue?

**Comment by jkpelo** [comment]
Thanks! Most likely the issue was caused due to a .catch { } (https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/catch.html) call that didn't emit: 

`myFlow.catch { logSomething() }.first()`

The difficulty for me here was to find the location of the crash as that info was stripped out and I wasn't able to find the location of the crash. 

`System.setProperty("kotlinx.coroutines.debug", "on")`.  ( see comment above ) can probably help, although I'm not sure we'd want to turn this on in production. Need to write more tests, it seems ;-)

**Comment by OyaCanli** [comment]
I have no calls to first() in my codebase, yet I see this error on crashlytics, not referring to anywhere from my code. What else can be indirectly calling this? I use Kotlin version 1.8.10

**Comment by dkhalanskyjb** [comment]
We also don't call `first` anywhere from our code, so some third-party library must be at fault.

**Comment by odaga** [comment]
I have used firstOrNull() and it was able to clear the "NoSuchElementException".

**Comment by yangwuan55** [comment]
```
System.setProperty("kotlinx.coroutines.debug", "on")
```

this way is not used in android,what should I do for android platform?

**Comment by fzhinkin** [comment]
@yangwuan55 

> this way is not used in android,what should I do for android platform?

It should be possible to set up the property from a main activity creation callback.
Or do you mean that the property does not work on Android in general?

**Comment by globsterg** [comment]
AFAIK it doesn't work on Android at all: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-debug/README.md#debug-agent-and-android

**Comment by yangwuan55** [comment]
> @yangwuan55
> 
> > this way is not used in android,what should I do for android platform?
> 
> It should be possible to set up the property from a main activity creation callback. Or do you mean that the property does not work on Android in general?

yes,does not work on Android platform.
