### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Number.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by Monabr** [Kotlin/kotlinx.coroutines#3117]
Hi.

I was using 1.6.0 and get it before my collect method. I have even comment everything in collect but still get this exception.

I have even downgrade to 1.5.2 and still get this exception.

Don't know what to do :(

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Number.doubleValue()' on a null object reference
        at com.example.example.ui.screens.mainContainer.MainViewModel$getMyValues$1$5$1$1.emit(MainViewModel.kt:81)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

Code itself 

```
viewModelScope.launch(Dispatchers.IO) {

            . . .

            launch {
              
                    repository.getMyValues(index).collect {
                       
                    }
                }
            }

           . . .
      }
```

**Comment by Monabr** [comment]
Answer is - double that i got from room is null and when i marked it nullable - no exceptions after that

**Comment by Monabr** [comment]
Answer is - double that i got from room is null and when i marked it nullable - no exceptions after that
