### ISSUE TITLE
CoroutineScheduler.kt line 434 crash

### ISSUE THREAD

**Issue by ravisaini1990** [Kotlin/kotlinx.coroutines#3175]
`kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker (CoroutineScheduler.kt:434)`

**Fatal Exception: java.lang.NoClassDefFoundError: Not a primitive type: '\u0000'**
       at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker(CoroutineScheduler.kt:434)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.signalBlockingWork(CoroutineScheduler.kt:421)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch(CoroutineScheduler.kt:402)
       at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core(Dispatcher.kt:115)
       at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch(Dispatcher.kt:170)
       at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch(Dispatcher.kt:160)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(:1)

**Comment by qwwdfsad** [comment]
Could you please provide a reproducer or explain how you got this error?
It seems to be a corrupted JAR issue or worse, because neither `NoClassDefFoundError` is expected by any means there, nor the error message is reasonable for exception type

**Comment by ravisaini1990** [comment]
Getting this on app starting on line where i am trying to add logging on IO thread of app scoped corutines

**Comment by qwwdfsad** [comment]
Please clear all the caches and try again. We cannot help much without a reproducer here
