### ISSUE TITLE
when an uncatched UnkonwnHostException is thrown, no stack info print on Android

### ISSUE THREAD

**Issue by AlphaBoom** [Kotlin/kotlinx.coroutines#3222]
I wrote sample android application like this
```kotlin
        binding.btnThrowUnknownHostException.setOnClickListener {
            lifecycleScope.launch {
                throw UnknownHostException()
            }
        }
        binding.btnThrowException.setOnClickListener {
            lifecycleScope.launch {
                throw Exception()
            }
        }
        binding.btnThrowIoException.setOnClickListener {
            lifecycleScope.launch {
                throw IOException()
            }
        }
        binding.btnThrowNullPointerException.setOnClickListener {
            lifecycleScope.launch {
                throw NullPointerException()
            }
        }
```
When an unknownhostexception is thrown, the crash stack of the corresponding application is as follows
```
2022-03-25 18:30:17.099 16724-16724/com.example.kotlincoroutinestest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kotlincoroutinestest, PID: 16724
```
When other exceptions are thrown, stack strace print correctly.
```
2022-03-25 18:31:44.165 16808-16808/com.example.kotlincoroutinestest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kotlincoroutinestest, PID: 16808
    java.lang.NullPointerException
        at com.example.kotlincoroutinestest.MainActivity$onCreate$4$1.invokeSuspend(MainActivity.kt:36)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.example.kotlincoroutinestest.MainActivity.onCreate$lambda-3(MainActivity.kt:35)
        at com.example.kotlincoroutinestest.MainActivity.$r8$lambda$_ajEPZI_gmugFxRLZfv8yExqeMs(Unknown Source:0)
        at com.example.kotlincoroutinestest.MainActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7201)
```
Dependent version：
```
plugins {
    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.5.30' apply false
}
dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```
sample application here: https://github.com/AlphaBoom/KotlinCoroutinesTest

**Comment by RobertLK** [comment]
Amazingly this is nothing to do with coroutines and is actually a very old "feature" of the android log framework: https://stackoverflow.com/questions/28897239/log-e-does-not-print-the-stack-trace-of-unknownhostexception
