### ISSUE TITLE
IncompatibleClassChangeError when inlining suspend funs

### ISSUE THREAD

**Issue by RobertLK** [Kotlin/kotlinx.coroutines#3288]
See code here: https://pl.kotl.in/gj3li59nD

Running on kotlin 1.6 gives:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Class java.lang.Integer does not implement the requested interface kotlin.coroutines.Continuation
 at kotlinx.coroutines.CancellableContinuationImpl.&amp;lt;init&amp;gt; (CancellableContinuationImpl.kt:34) 
 at kotlinx.coroutines.DelayKt.delay (Delay.kt:160) 
 at FileKt$main$result$1$invokeSuspend$$inlined$map$1.invoke (File.kt:33) 
```

Running on kotlin 1.4 gives (note the final print means the code worked despite the error):
```
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[BlockingEventLoop@29ee9faa, Continuation at FileKt$main$result$1.invokeSuspend(File.kt)@c038203]){Cancelled}@cc285f4. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.common.kt:224)
	at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:114)
	at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:108)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:90)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at FileKt.main(File.kt:10)
	at FileKt.main(File.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at executors.JavaRunnerExecutor$Companion.main(JavaRunnerExecutor.kt:27)
	at executors.JavaRunnerExecutor.main(JavaRunnerExecutor.kt)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 17 more
Wrapper(value=3)
```

Some observations:
* Issue definitely seems to be in the andThen function which is combining an implicit suspend context with a regular function.
* Switching to map2 fixes on all versions (exactly the same but doesn't use andThen)
* Removing the delay() fixes on all versions
* [Changing everything to suspend](https://pl.kotl.in/zrgS-jyXi) fixes on all versions.
* [This bug](https://youtrack.jetbrains.com/issue/KT-44567/IncompatibleClassChangeError-caused-by-coroutines-and-Vertx) looks very similar but marked as fixed in kotlin 1.5
* Duplicates [this discussion](https://app.slack.com/client/T09229ZC6/C1CFAFJSK/thread/C1CFAFJSK-1652612669.959549) in kotlin Slack

**Comment by qwwdfsad** [comment]
Thanks for the detailed report and a reproducer that is easy to run!
This is a compiler bug that cannot be workarounded on our side, please keep track of https://youtrack.jetbrains.com/issue/KT-52403

**Comment by RobertLK** [comment]
Thanks pyos, that's really helpful context. I'm sure at one point saw a warning in Android Studio that something couldn't be inlined so that makes more sense now. Definitely happy with this being a compiler error because there's no other indication that the code is invalid (in fact we use something quite similar in production on kotlin 1.4 :scream: )
