### ISSUE TITLE
ConcurrentWeakMapOperationStressTest.testOperation failed on CI

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3341]
https://teamcity.jetbrains.com/viewLog.html?buildId=3878037&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_NightlyStress

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:63)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:62)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at kotlinx.coroutines.internal.ConcurrentWeakMapOperationStressTest.testOperations(ConcurrentWeakMapOperationStressTest.kt:71)
```

**Comment by qwwdfsad** [comment]
It doesn't reproduce locally and also has nothing in common with https://github.com/Kotlin/kotlinx.coroutines/pull/2187/

**Comment by qwwdfsad** [comment]
Another observation is that `assertEquals(v, m[k])` failed, so it may appear that value was prematurely deleted.
But it's not the case, because the very last assert `assertEquals(0, m.size)` failed with `0 != 1`, which likely means that it is possible to observe map in such intermediates state that the key is here, but `get` returns `null`

**Comment by dkhalanskyjb** [comment]
> It doesn't reproduce locally

Just to double-check, I tried running this test in a loop on Linux, and 20 minutes later, with `nSeconds = 75`, the bug did not surface.

**Comment by dkhalanskyjb** [comment]
I left the test to run in a loop for 2 days and 20 hours, but it still didn't crash.

**Comment by qwwdfsad** [comment]
Closing as "cannot reproduce", let's reopen it if it indeed was a real failure that will appear again and not a random fluke
