### ISSUE TITLE
[Android]  invokeSuspend throws NullPointer while minifyEnabled is true

### ISSUE THREAD

**Issue by proninyaroslav** [Kotlin/kotlinx.coroutines#3400]
This is very similar to the 4 years old issue #910. 

I got this when I was using the Retrofit suspend functions in my Android Compose app (I use Retrofit + Pagin 3 library). `org.jetbrains.kotlin.android:1.7.0`
```
FATAL EXCEPTION: main
Process: com.exmaple.myapp, PID: 23350
java.lang.NullPointerException: throw with null exception
 at com.exmaple.myapp.model.paging.CharactersRemoteMediator.fetch(CharactersRemoteMediator.kt:15)
 at com.exmaple.myapp.model.paging.CharactersRemoteMediator$fetch$1.invokeSuspend(Unknown Source:12)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
 at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:2)
 at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:1)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@7eb612f, androidx.compose.runtime.BroadcastFrameClock@2ee33c, StandaloneCoroutine{Cancelling}@99b38c5, AndroidUiDispatcher@fc1621a]
```

**Comment by qwwdfsad** [comment]
If something crashes only after minification, then it's minifer bug and we cannot really do much about it.
I suggest filing an issue to Google issue tracker instead
