### ISSUE TITLE
Support windows-arm64

### ISSUE THREAD

**Issue by VladRassokhin** [Kotlin/kotlinx.coroutines#3473]
```
java.lang.IllegalStateException: Error during attachment using: INSTANCE
	at kotlinx.coroutines.repackaged.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
	at kotlinx.coroutines.repackaged.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
	at kotlinx.coroutines.repackaged.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.attach(Attach.kt:21)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:17)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:15)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.install(DebugProbesImpl.kt:85)
	at kotlinx.coroutines.debug.DebugProbes.install(DebugProbes.kt:72)
	at com.intellij.diagnostic.CoroutineDumperKt.enableCoroutineDump(coroutineDumper.kt:22)
	at com.intellij.idea.StartupUtil$startApplication$4.invokeSuspend(StartupUtil.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlinx.coroutines.repackaged.net.bytebuddy.agent.Attacher.install(Attacher.java:106)
	at kotlinx.coroutines.repackaged.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'attach_hotspot_windows':
The specified module could not be found.
The specified module could not be found.
The specified module could not be found.
Native library (win32-aarch64/attach_hotspot_windows.dll) not found in resource path ...
```

**Comment by qwwdfsad** [comment]
Seems like we have to update JNA to the corresponding version

**Comment by qwwdfsad** [comment]
It's not JNA, see https://github.com/raphw/byte-buddy/issues/1336

**Comment by joffrey-bion** [comment]
@qwwdfsad could you please clarify why this is not planned and not just left open? Don't we want to support Windows arm64 _ever_? We are facing this problem with Amper now, where users cannot use Amper on arm64.
