### ISSUE TITLE
Call a suspend function through reflection fails

### ISSUE THREAD

**Issue by qimikimi** [Kotlin/kotlinx.coroutines#3476]
The following is the test code where the exception occurs:

```
class TestClass {

    suspend fun testFunction(): Result<String> {
        delay(1000)                           // It's normal to remove the delay
        return Result.success("success")      // It is normal to change the return type to other
    }

}

fun main() {
    val testObject: TestClass = TestClass()
    val testFunction: KFunction<*> = TestClass::class.memberFunctions.first { it.name == "testFunction" }

    runBlocking {
        val result: Result<String> = testFunction.callSuspend(testObject) as Result<String>
        println(result)
    }
}
```

The console output:

```
Success(COROUTINE_SUSPENDED)
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[BlockingEventLoop@34f6515b, Continuation at TestClass.testFunction-IoAF18A(Main.kt:9)@3e2059ae]){Cancelled}@398dada8. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.common.kt:229)
	at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:114)
	at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:108)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:91)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.main(Main.kt:19)
	at MainKt.main(Main.kt)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [BlockingCoroutine{Completed}@2812b107, BlockingEventLoop@34f6515b]
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:166)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 11 more
```

The version of kotlin is 1.6.21.

**Comment by qwwdfsad** [comment]
Thanks for the self-contained report!

This is a bug (or regression?) in kotlin-reflect, I've filed https://youtrack.jetbrains.com/issue/KT-54397/Double-resume-in-callSuspend-and-eager-return-of-COROUTINESUSPENDED-marker
