### ISSUE TITLE
BlockHound false positive in ConflatedChannel.isBufferEmpty

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.coroutines#3498]
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Relevant stack trace excerpt:

```text
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
    at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
    at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
    at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
    at kotlinx.coroutines.channels.ConflatedChannel.isBufferEmpty(ConflatedChannel.kt:145)
    at kotlinx.coroutines.channels.AbstractChannel.isEmptyImpl(AbstractChannel.kt:580)
    at kotlinx.coroutines.channels.AbstractChannel.registerSelectReceiveMode(AbstractChannel.kt:752)
    at kotlinx.coroutines.channels.AbstractChannel.access$registerSelectReceiveMode(AbstractChannel.kt:515)
    at kotlinx.coroutines.channels.AbstractChannel$onReceive$1.registerSelectClause1(AbstractChannel.kt:737)
    at kotlinx.coroutines.selects.SelectBuilderImpl.invoke(Select.kt:632)
```

Possibly an oversight introduced by 52cbf01c63c0737ee745ff08568f26385271a9ab.

EDIT: `bufferDebugString` will also be affected.

**Comment by qwwdfsad** [comment]
Should no longer be an issue -- we've got rid of locks in conflated channel
