### ISSUE TITLE
FATAL EXCEPTION: DefaultDispatcher-worker-1

### ISSUE THREAD

**Issue by LeonBatford** [Kotlin/kotlinx.coroutines#3508]
Process: com.example.github, PID: 22236
    java.lang.NoSuchMethodError: No virtual method checkUser(I)Ljava/lang/Integer; in class Lcom/example/github/ui/main/detail/DetailUserViewModel; or its super classes (declaration of 'com.example.github.ui.main.detail.DetailUserViewModel' appears in /data/data/com.example.github/code_cache/.overlay/base.apk/classes8.dex)
        at com.example.github.ui.main.detail.DetailUserActivity$onCreate$2.invokeSuspend(DetailUserActivity.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a196109, Dispatchers.IO]

**Comment by qwwdfsad** [comment]
Once again, please use stackoverflow or slack for general questions and troubleshooting
