### ISSUE TITLE
CoroutineScope  cause ServiceConfigurationError

### ISSUE THREAD

**Issue by cuichanghao** [Kotlin/kotlinx.coroutines#3518]
In the last week, there were 25 such crashes in our app.
When create scope with `private val scope = CoroutineScope(Dispatchers.Main)` or just use android `public val ViewModel.viewModelScope: CoroutineScope`, there will be crash with below error.
Please confirm it.

```
java.util.ServiceConfigurationError: kotlinx.coroutines.internal.MainDispatcherFactory: Error reading configuration file
    at java.util.ServiceLoader.fail(ServiceLoader.java:233)
    at java.util.ServiceLoader.parse(ServiceLoader.java:310)
    at java.util.ServiceLoader.-$$Nest$mparse(ServiceLoader.java:0)
    at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:358)
    at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:402)
    at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:488)
    at kotlin.sequences.SequencesKt___SequencesKt.toCollection(SequencesKt___SequencesKt.java:787)
    at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(SequencesKt___SequencesKt.java:817)
    at kotlin.sequences.SequencesKt___SequencesKt.toList(SequencesKt___SequencesKt.java:808)
    at kotlin.sequences.SequencesKt.toList(SequencesKt.java:0)
    at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatcherLoader.java:35)
    at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatcherLoader.java:22)
    at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.java:57)
    at androidx.lifecycle.ViewModelKt.getViewModelScope(ViewModelKt.java:43)
    at xxxxxxxxViewModel.<init>(xxxxxxxxViewModel.java:32)
    at java.lang.Class.newInstance(Class.java)
    at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:186)
    at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:238)
    at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
    at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:146)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
    at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:171)
    at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
    at xxxxxActivity.onCreate(xxxxxActivity.java:289)
    at android.app.Activity.performCreate(Activity.java:8121)
    at android.app.Activity.performCreate(Activity.java:8101)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3917)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2320)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:8064)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: java.io.EOFException: Detect premature EOF
    at sun.misc.IOUtils.readFully(IOUtils.java:68)
    at java.util.jar.JarFile.getBytes(JarFile.java:435)
    at java.util.jar.JarFile.getManifestFromReference(JarFile.java:201)
    at java.util.jar.JarFile.getManifest(JarFile.java:183)
    at java.util.jar.JarFile.maybeInstantiateVerifier(JarFile.java:354)
    at java.util.jar.JarFile.getInputStream(JarFile.java:455)
    at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
    at java.net.URL.openStream(URL.java:1072)
    at java.util.ServiceLoader.parse(ServiceLoader.java:305)

```

**Comment by qwwdfsad** [comment]
Hi, could you please provide more details, e.g. device models and API versions?

It seems like either this is a bag in a particular vendor implementation or corrupted APK installed

**Comment by dkhalanskyjb** [comment]
Looks like https://github.com/Kotlin/kotlinx.serialization/issues/1463.

Do you have R8 enabled? If so, it should eliminate the `ServiceLoader` usage, sidestepping the problem.

**Comment by cuichanghao** [comment]
Device is japan model: SH-53A, SCG10.
But now not happen in new app version. may be `com.android.tools.build:gradle:7.2.2` to `com.android.tools.build:gradle:7.3.1` is what's working?

**Comment by VikramBKadam** [comment]
Do we have any resolution for this issue?
