### ISSUE TITLE
Flow doesn't always rethrow the original throwable when conflated

### ISSUE THREAD

**Issue by francescotescari** [Kotlin/kotlinx.coroutines#3521]
Ciao, I found a weird behavior when throwing a `Throwable` in a conflated flow, maybe a bug? While I expect the same throwable to be rethrown by the flow collection, I get a slightly different `Throwable`. I haven't tested whether it happens with other channel-based operators. Just ping me if you need more info, hopefully the following is enough to reproduce. 

I'm on a standard Kotlin JVM project. I expected the following JUnit test to pass:
```kotlin
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.conflate
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.runBlocking
import org.junit.Test


class Test {

    @Test
    fun myTest() = runBlocking {
        val myThrowable = Throwable("Some message")
        try {
            flow<Unit> { throw myThrowable }
                .conflate()
                .collect()
        } catch (throwable: Throwable) {
            check(myThrowable === throwable) {
                """
                    Throwable: expected: $myThrowable, found: $throwable
                    Cause: expected: ${myThrowable.cause}, found: ${throwable.cause}
                    Equals: ${myThrowable == throwable}
                """
            }
        }
    }

}
```
But if fails:
```
java.lang.IllegalStateException: 
        Throwable: expected: java.lang.Throwable: Some message, found: java.lang.Throwable: Some message
        Cause: expected: null, found: java.lang.Throwable: Some message
        Equals: false
```
The same test without the `.conflated` passes successfully.
The same code (with `conflated`) executed in `main` also passes the check. 
if I don't catch the flow exception I get the following:
```kotlin
Some message
java.lang.Throwable: Some message
	at Test$myTest$1.invokeSuspend(Test.kt:11)
	(Coroutine boundary)
	at Test$myTest$1.invokeSuspend(Test.kt:15)
Caused by: java.lang.Throwable: Some message
	at Test$myTest$1.invokeSuspend(Test.kt:11)
```
My gradle config is as following:
```groovy
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.7.20'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
    testImplementation "junit:junit:4.13.2"
}
```

**Comment by dkhalanskyjb** [comment]
It's an expected effect of the stacktrace recovery: https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md#stacktrace-recovery. When I run your code without the stacktrace recovery enabled, it passes without issues. In the provided case, I think the easiest choice would be to just not check these exceptions for equality and instead compare their messages.
