### ISSUE TITLE
BlockHound false positive in ThreadPoolExecutor.execute

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.coroutines#3540]
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

This one occurred once in a stress test which runs very frequently. Seems similar to `ScheduledThreadPoolExecutor.execute`.

Full stack trace:
``` 
    reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
        at java.base@11.0.17/jdk.internal.misc.Unsafe.park(Unsafe.java)
        at java.base@11.0.17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.17/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base@11.0.17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base@11.0.17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base@11.0.17/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base@11.0.17/java.util.concurrent.LinkedBlockingQueue.signalNotEmpty(LinkedBlockingQueue.java:173)
        at java.base@11.0.17/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:421)
        at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1347)
        at java.base@11.0.17/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687)
        at app//kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:128)
        at app//kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
        at app//kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at app//kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:174)
        at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at app//io.kotest.engine.concurrency.FixedThreadCoroutineDispatcherFactory.withDispatcher(FixedThreadCoroutineDispatcherFactory.kt:52)
        at app//io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor.intercept(coroutineDispatcherFactoryInterceptor.kt:56)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.interceptors.SupervisorScopeInterceptor$intercept$2.invokeSuspend(SupervisorScopeInterceptor.kt:23)
        at app//io.kotest.engine.test.interceptors.SupervisorScopeInterceptor$intercept$2.invoke(SupervisorScopeInterceptor.kt)
        at app//io.kotest.engine.test.interceptors.SupervisorScopeInterceptor$intercept$2.invoke(SupervisorScopeInterceptor.kt)
        at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at app//kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
        at app//io.kotest.engine.test.interceptors.SupervisorScopeInterceptor.intercept(SupervisorScopeInterceptor.kt:22)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.interceptors.InvocationCountCheckInterceptor.intercept(InvocationCountCheckInterceptor.kt:24)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.interceptors.TestFinishedInterceptor.intercept(TestFinishedInterceptor.kt:21)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.interceptors.TestNameContextInterceptor$intercept$2.invokeSuspend(TestPathContextInterceptor.kt:35)
        at app//io.kotest.engine.test.interceptors.TestNameContextInterceptor$intercept$2.invoke(TestPathContextInterceptor.kt)
        at app//io.kotest.engine.test.interceptors.TestNameContextInterceptor$intercept$2.invoke(TestPathContextInterceptor.kt)
        at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at app//io.kotest.engine.test.interceptors.TestNameContextInterceptor.intercept(TestPathContextInterceptor.kt:34)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.interceptors.TestPathContextInterceptor$intercept$2.invokeSuspend(TestPathContextInterceptor.kt:20)
        at app//io.kotest.engine.test.interceptors.TestPathContextInterceptor$intercept$2.invoke(TestPathContextInterceptor.kt)
        at app//io.kotest.engine.test.interceptors.TestPathContextInterceptor$intercept$2.invoke(TestPathContextInterceptor.kt)
        at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at app//io.kotest.engine.test.interceptors.TestPathContextInterceptor.intercept(TestPathContextInterceptor.kt:19)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:92)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
        at app//io.kotest.engine.test.TestCaseExecutor.execute(TestCaseExecutor.kt:93)
        at app//io.kotest.engine.spec.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:121)
        at app//io.kotest.engine.spec.runners.SingleInstanceSpecRunner.access$runTest(SingleInstanceSpecRunner.kt:31)
        at app//io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$2.invokeSuspend(SingleInstanceSpecRunner.kt:51)
        at app//io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$2.invoke(SingleInstanceSpecRunner.kt)
        at app//io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$2.invoke(SingleInstanceSpecRunner.kt)
        at app//io.kotest.engine.test.scheduler.SequentialTestScheduler$schedule$3$1$1.invokeSuspend(SequentialTestScheduler.kt:20)
        at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by dkhalanskyjb** [comment]
Is there any indication that this is a false positive on our side? We only instruct the Executor to start a task, and if (all of this on Java's side) the task can not be executed at the time due to no threads being available and is put into a queue as a result, well, the thread *is* blocked, which BlockHound correctly detects.

**Comment by OliverO2** [comment]
If I understand it correctly, the blocking occurs briefly just for queue management. Is this any different from lock usage in, say, `ConflatedChannel.offerInternal`?

Given the lack of reproducibility, is there any other helpful information I could try to obtain?

**Comment by dkhalanskyjb** [comment]
> If I understand it correctly, the blocking occurs briefly just for queue management.

Hm, yes, looks like you're right. Still, that's still not *our* implementation detail, it's an implementation detail of `java.util.concurrent.LinkedBlockingQueue.offer`.

**Comment by OliverO2** [comment]
...which `ExecutorCoroutineDispatcherImpl` decided to use (via Java's `ThreadPoolExecutor`), so it became a kotlinx.coroutines implementation detail. Seems analogous to this allowance:

https://github.com/Kotlin/kotlinx.coroutines/blob/6dfabf763fe9fc91fbb73eb0f2d5b488f53043f1/kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt#L160-L163

**Comment by dkhalanskyjb** [comment]
Nope, we haven't decided to use this. We provide an ability to use an arbitrary `Executor` as a `CoroutineDispatcher`, and (probably) kotest decided to use as a `CoroutineDispatcher` an `Executor` that performs the blocking. Our code literally never mentions `ThreadPoolExecutor`, `DelegatedExecutorService`, or whatever.

**Comment by OliverO2** [comment]
OK, if that's the case I'll investigate. Will report back.

**Comment by OliverO2** [comment]
Turns out the above case was caused by **kotest**, which uses `ThreadPoolExecutor` by default in `FixedThreadCoroutineDispatcherFactory` (via `Executors.newSingleThreadExecutor().asCoroutineDispatcher()`).

Kotest currently has no provisions for BlockHound integration. I'll bring up the issue there and file a PR if possible.

Regarding kotlinx.coroutines: Would you be in favor of adding documentation to `asCoroutineDispatcher` (for both variants), reminding users to consider BlockHound requirements when introducing an `Executor`?
https://github.com/Kotlin/kotlinx.coroutines/blob/6dfabf763fe9fc91fbb73eb0f2d5b488f53043f1/kotlinx-coroutines-core/jvm/src/Executors.kt#L69

**Comment by dkhalanskyjb** [comment]
> I'll bring up the issue there and file a PR if possible.

Maybe https://github.com/reactor/BlockHound themselves would be open to such a request. They do have some integrations provided out of the box, like `System.out` etc.

> Regarding kotlinx.coroutines: Would you be in favor of adding documentation to `asCoroutineDispatcher` (for both variants), reminding users to consider BlockHound requirements when introducing an `Executor`?

Doesn't seem like a good idea. It wouldn't prevent your crash: the documentation for `ThreadPoolExecutor` doesn't state that it may use locking as part of its operation. If one *does* somehow know that the executor blocks as part of state management, this note is not needed because it's self-evident: sure, if the code we're wrapping blocks, it means that we also block. Also, we have many such wrappers. Spamming a non-actionable note throughout all of our documentation seems counterproductive.

**Comment by OliverO2** [comment]
OK, then there's two avenues to follow. I'll try to figure out which one works best. And in any case, this issue can serve as background documentation for others – although not as a preventive measure.

Thanks for discussing!
