### ISSUE TITLE
StackOverflowError in afterResume

### ISSUE THREAD

**Issue by hristijan-tap** [Kotlin/kotlinx.coroutines#3568]
**Describe the bug**

We're calling a suspending function that calls itself on a delay that has a withContext io dispatcher

**Provide a Reproducer**
```kotlin
override suspend fun queryProductSubsDetails(
        productIds: List<String>,
        productType: String
    ): List<ProductModel> = withContext(ioDispatcher) {
        val productList = productIds.map { productId ->
            QueryProductDetailsParams.Product.newBuilder()
                .setProductId(productId)
                .setProductType(productType)
                .build()
        }

        val params = QueryProductDetailsParams.newBuilder().setProductList(productList)

        val productDetailsResult: ProductDetailsResult = billingClientManager.billingClient.queryProductDetails(params.build())

        val response = productDetailsResult.billingResult.asBillingResponse
        val products = if (response.isOk) {
            productDetailsResult.mapProducts()
        } else {
            emptyList()
        }

        while (products.isEmpty()) {
            delay(UNIVERSAL_APP_DELAY) // 0.5s
            queryProductSubsDetails(productIds, productType) //recursive call until we have available products, probably what crashes machinery
        }

        return@withContext products
    }
```

**Trace**
```kotlin
kotlinx.coroutines.internal.LockFreeLinkedListNode.remove
Caused by java.lang.StackOverflowError: stack size 1043KB
       at java.lang.Class.isInstance(Class.java:542)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.accessCheck(AtomicReferenceFieldUpdater.java:389)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.lazySet(AtomicReferenceFieldUpdater.java:440)
       at kotlinx.coroutines.internal.LockFreeLinkedListNode.removed(LockFreeLinkedListNode.java:34)
       at kotlinx.coroutines.internal.LockFreeLinkedListNode.remove(LockFreeLinkedListNode.java)
       at kotlinx.coroutines.JobSupport.removeNode$kotlinx_coroutines_core(JobSupport.java:49)
       at kotlinx.coroutines.JobNode.dispose(JobNode.java:49)
       at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.java:6)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:167)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:228)
       at kotlinx.coroutines.JobSupport.l0(JobSupport.java:4)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:11)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:81)
```

```kotlin
kotlinx.coroutines.UndispatchedCoroutine.afterResume

Caused by java.lang.StackOverflowError: stack size 1043KB
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:25)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:11)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:81)
```

```kotlin
kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted

Caused by java.lang.StackOverflowError: stack size 1043KB
       at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.java:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:22)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:11)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:81)
```

```kotlin
kotlin.coroutines.CombinedContext.fold

Caused by java.lang.StackOverflowError: stack size 1043KB
       at kotlin.coroutines.CombinedContext.fold(CombinedContext.java:2)
       at kotlinx.coroutines.internal.ThreadContextKt.threadContextElements(ThreadContextKt.java:7)
       at kotlinx.coroutines.internal.ThreadContextKt.updateThreadContext(ThreadContextKt.java:2)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:35)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:11)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:81)
```

```kotlin
kotlinx.coroutines.AbstractCoroutine.onCancelled

Caused by java.lang.StackOverflowError: stack size 1041KB
       at kotlinx.coroutines.AbstractCoroutine.onCancelled(AbstractCoroutine.java)
       at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.java:12)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:135)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:228)
       at kotlinx.coroutines.JobSupport.l0(JobSupport.java:4)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(UndispatchedCoroutine.java:49)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:22)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:31)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:11)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:81)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:81)
```

The scope is [the application scope](https://medium.com/androiddevelopers/create-an-application-coroutinescope-using-hilt-dd444e721528) in android.

**Comment by FunkyMuse** [comment]
```toml
coroutines = "1.6.4"
```

**Comment by qwwdfsad** [comment]
You have an unbound recursion in your example -- `queryProductSubsDetails` can invoke itself an arbitrary number of times. Due to how coroutines are implemented internally, the stack is shown in the inside-out manner -- instead of N nested `queryProductSubsDetails` it shows N nested `afterResume` calls.

The recommended solution is to use a regular `while` loop with condition instead of unbound recursion
