### ISSUE TITLE
Kotlin 코루틴질문입니다.

### ISSUE THREAD

**Issue by leechaeeyoung** [Kotlin/kotlinx.coroutines#3610]
```kotlin
class UrlPrintActivity : AppCompatActivity() {

    @OptIn(DelicateCoroutinesApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        setContentView(R.layout.print_url)

        val binding = PrintUrlBinding.inflate(layoutInflater);
        setContentView(binding.root);

        binding.configBtn.setOnClickListener {
            GlobalScope.launch(Dispatchers.IO) {

                try {
                    val url = URL("~~~")
                    val urlConn = url.openConnection() as HttpURLConnection
                    urlConn.requestMethod = "GET"

                    if (urlConn.responseCode == HttpURLConnection.HTTP_OK) {
                        val streamReader = InputStreamReader(urlConn.inputStream)
                        val buffered = BufferedReader(streamReader)
                        val content = StringBuilder()

                        while (true) {
                            val data = buffered.readLine() ?: break
                            content.append(data)
                        }
                        buffered.close()
                        urlConn.disconnect()

                        launch(Dispatchers.Main) {
                            binding.textContent.text = content.toString()
                        }
                    }
                } catch (e:Exception){
                    e.printStackTrace()
                }
            }
        }
    }
}
```
configBtn을 클릭하면 URL의 데이터를 불러오는 코드입니다 ㅠㅠ 다만 실행하면
```
at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
2023-01-31 17:17:18.073 23736-23804 System.err              com.example.test1                    W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
2023-01-31 17:17:18.073 23736-23804 System.err              com.example.test1                    W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2023-01-31 17:17:18.073 23736-23804 System.err              com.example.test1                    W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at com.example.test1.UrlPrintActivity$onCreate$1$1.invokeSuspend(UrlPrintActivity.kt:32)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-01-31 17:17:18.074 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-01-31 17:17:18.075 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-01-31 17:17:18.075 23736-23804 System.err              com.example.test1                    W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
라는 로그만 뜨고 화면에 실행되지 않아요 ㅠㅠㅠ 해결방법알수있을까요

**Comment by dkhalanskyjb** [comment]
This is an issue tracker for the kotlinx.coroutines library, we don't answer general programming questions here. Also, here, we use English.
