### ISSUE TITLE
Avoid synchronized section in CoroutineScheduler during internal pool growth

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3652]
We had multiple freeze reports from IDEA, all with the following stacktrace:

```
	at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker(CoroutineScheduler.kt:1007)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker(CoroutineScheduler.kt:439)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker$default(CoroutineScheduler.kt:430)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.signalCpuWork(CoroutineScheduler.kt:426)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch(CoroutineScheduler.kt:398)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default(CoroutineScheduler.kt:382)
		at kotlinx.coroutines.scheduling.SchedulerCoroutineDispatcher.dispatch(Dispatcher.kt:97)
```

During the startup phase, IDEA aggressively launches hundreds of coroutines, and some of them are run from the main thread;
Due to the fact that the growing mechanism uses coarse-grained lock as the easiest way to avoid thread overprovision, that during contention might cause sub-ms pauses

**Comment by gregsh** [comment]
I see freezes of several hundreds of milliseconds in length in UI thread.

**Comment by qwwdfsad** [comment]
I was trying to figure out why on earth this synchronized section was contended up to hundreds of milliseconds.

Here is the more or less self-explanatory benchmarking result:
```
Benchmark                                         Mode  Cnt   Score   Error  Units
ChannelSinkBenchmark.allocateAndStartEmptyThread  avgt    5  48.987 ± 0.850  us/op
ChannelSinkBenchmark.allocateEmptyArray64         avgt    5   0.019 ± 0.001  us/op
ChannelSinkBenchmark.allocateEmptyThread          avgt    5   1.295 ± 0.056  us/op
```

Allocating a new thread [under lock] is a non-trivial operation that incurs a non-trivial overhead of JVM upcalls, that may consume unpredictable (when compared to "increment, TLAB-allocate and set to array" action) amount of time that may lead to an additional contention

<details>
<summary>Flame graph</summary>
<img width="615" alt="image" src="https://user-images.githubusercontent.com/2780116/226584379-19bf7561-6455-4835-8d27-1126e5a6cf90.png">

</details>
