### ISSUE TITLE
Tests for kotlinx-coroutines-debug module fail on OpenJDK 17 due to change internals

### ISSUE THREAD

**Issue by FenstonSingel** [Kotlin/kotlinx.coroutines#3700]
When running on OpenJDK 17 (and down to OpenJDK 14 according to my checks of corresponding sources), `RunningThreadStackMergeTest` fails on `testStackMergeWithContext`, `testStackMergeEscapeSuspendMethod`, and `testMergeThroughInvokeSuspend`. The reason is [a change in OpenJDK's `java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject`](https://github.com/openjdk/jdk/commit/80fe274875a084794ccafcd00696586e384255b1#diff-df601946e34ba1a4e15b5302ded3df444d459aac78dc55baa3f9716d4ecccfa8R1604). This change results in a stack dump that differs from expected one by three new frames:

```
Coroutine "coroutine#X":StandaloneCoroutine{Active}@ADDR, state: RUNNING at
java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
+NEW+ at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
+NEW+ at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
+NEW+ at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
at java.base@17.0.5/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:236)
at java.base@17.0.5/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:364)
```

(nb: line numbers most probably also differ, but that's not really that relevant)

**Comment by FenstonSingel** [comment]
At the moment this issue only becomes visible after eliminating #3701 first.
