### ISSUE TITLE
Fatal exception in coroutines machinery

### ISSUE THREAD

**Issue by hu553in** [Kotlin/kotlinx.coroutines#3705]
**Describe the bug**

I have such exception in my project:

```
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[StandardTestDispatcher[scheduler=kotlinx.coroutines.test.TestCoroutineScheduler@73a00e09], Continuation at com.example.demo.DemoApplicationKt$main$1$2.invokeSuspend(DemoApplication.kt:28)@31ddd4a4]){Cancelled}@65004ff6. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:100)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdleOr$kotlinx_coroutines_test(TestCoroutineScheduler.kt:120)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdle(TestCoroutineScheduler.kt:113)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:237)
	at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$1.invokeSuspend(TestBuilders.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest$default(TestBuilders.kt:147)
	at kotlinx.coroutines.test.TestBuildersKt.runTest$default(Unknown Source)
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:25)
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:166)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 24 more
```

Please see reproducer.
Exception seems the same for me.

Differences:
- in my project `someMethod` is being called by another chain of methods -> message to queue -> another chain of methods, not directly from test body
- in my project `someMethod` is going to Redis:
  ```kotlin
      private val redis1: ReactiveRedisTemplate<String, MyClass>
      private val redis2: ReactiveRedisTemplate<String, UUID>
  
      suspend fun someMethod(externalId: String) {
          val internalId = redis2
              .opsForValue()
              .get(buildKeyByExternald(externalId))
              .awaitSingleOrNull()
          if (internalId == null) {
              log.warn("Internal id is not found for externalId=$externalId")
              return
          }
          val internalDeleted: Long = redis1
              .delete(buildKeyByInternalId(internalId))
              .awaitSingle()
          val externalDeleted: Long = redisExternalToInternal
              .delete(buildKeyByExternalWorkId(externalId))
              .awaitSingle()
          if (internalDeleted == 0L || externalDeleted == 0L) {
              log.warn(
                  "Error in AgentWork deletion: " +
                          "internalDeleted = $internalDeleted, " +
                          "externalDeleted = $externalDeleted"
              )
          }
      }
  ```

**Provide a Reproducer**

https://github.com/hu553in/fatal-exception-in-coroutines-machinery-example

Just run `main` function.

**Comment by hu553in** [comment]
@qwwdfsad thank you, done https://github.com/mockk/mockk/issues/1078
