### ISSUE TITLE
java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.CancellableContinuationImpl

### ISSUE THREAD

**Issue by 99937272** [Kotlin/kotlinx.coroutines#374]
interface SuspendableHandler<I,O>{
    suspend fun handle(inValue: I): O
    suspend fun call(inValue: Any?): Any?{
        return handle(inValue as I)
    }
}
result = (obj as SuspendableHandler<Any?,Any?>).call(values[0]) 

 _uca.admin.demo.KotlinDemoController$fetchdetails.handle(fetchdetails.java:149)
Exception in thread "vert.x-eventloop-thread-0" java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.CancellableContinuationImpl.<init>(Lkotlin/coroutines/experimental/Continuation;I)V
	at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitEvent(VertxCoroutine.kt:457)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitResult(VertxCoroutine.kt:76)
	at uca.framework.core.AsyncHelper$Companion.awaitResult(AsyncHelper.kt:109)
	at uca.module.basis.user.model.CorporateModel$Companion.fetchEntryPage(CorporateModel.kt:79)
	at uca.admin.demo.KotlinDemoController$fetchdetails.handle(KotlinDemoController.kt:155)
	at uca.admin.demo.KotlinDemoController$fetchdetails.handle(KotlinDemoController.kt:144)
	at uca.framework.lang.SuspendableHandlerTwo$DefaultImpls.call(SuspendableHandlerTwo.kt:9)
	at uca.admin.demo.KotlinDemoController$fetchdetails.call(KotlinDemoController.kt:144)
	at uca.httpServer.Action.handle(Action.kt:429)_

**Comment by 99937272** [comment]
i am sorry but when i change the project from gradle to maven, the error disappear
