### ISSUE TITLE
NullPointerException when initializing a polymorphic SerializersModule on a base class with a self-referencing property

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.coroutines#3743]
Using `org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0`, this code compiles and runs fine with Kotlin **1.8.10**:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

@Serializable
sealed class Base(val successor: Base? = null)

@Serializable
class Derived : Base()

val jsonConfiguration = Json {
    serializersModule = SerializersModule {
        polymorphic(Any::class) {
            subclass(Derived::class)
        }
    }
}

fun main() {
    println("$jsonConfiguration")
}
```

With Kotlin **1.8.20** and **1.8.21**, it produces a `NullPointerException`:

``` 
> Task :run FAILED
2 actionable tasks: 2 executed
Exception in thread "main" java.lang.ExceptionInInitializerError
	at MainKt.getBaseSerializersModule(Main.kt:38)
	at MainKt$jsonConfiguration$1.invoke(Main.kt:23)
	at MainKt$jsonConfiguration$1.invoke(Main.kt:23)
	at kotlinx.serialization.json.JsonKt.Json(Json.kt:189)
	at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:187)
	at MainKt.<clinit>(Main.kt:23)
Caused by: java.lang.NullPointerException
	at Base$Companion.get$cachedSerializer(Main.kt:8)
	at Base$Companion.serializer(Main.kt:8)
	at Base.<clinit>(Main.kt:8)
	... 6 more
```

**Comment by OliverO2** [comment]
Sorry, picked the wrong project.
