### ISSUE TITLE
Crash when using reflection to invoke an inline-value-class-returning function that suspends

### ISSUE THREAD

**Issue by glasser** [Kotlin/kotlinx.coroutines#3761]
**Describe the bug**

I ran into this issue using graphql-kotlin. Using the `KFunction::callSuspendBy` extension from `kotlin-reflect` to invoke a function that suspends and then returns an inline value class crashes with an internal coroutines exception.

**Provide a Reproducer**

(Note: despite the name of the repro repo, this is a stripped-down reproduction that only depends on kotlin-reflect and kotlinx-coroutines-core.)

```
git clone https://github.com/glasser/graphql-kotlin-value-class-problem
cd graphql-kotlin-value-class-problem
./gradlew run
```

The file that it runs is:

```kt
package graphqlkotlinvalueclassproblem

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.yield
import kotlin.reflect.KFunction
import kotlin.reflect.full.callSuspendBy

fun main(args: Array<String>): Unit = runBlocking {
    val fnGood: KFunction<*> = ::suspendAndReturnNormalString
    println(fnGood.callSuspendBy(emptyMap()))
    val fnBad: KFunction<*> = ::suspendAndReturnValueString
    println(fnBad.callSuspendBy(emptyMap()))
}

@JvmInline
value class ValueString(val value: String) {
    override fun toString(): String = value
}

suspend fun suspendAndReturnValueString(): ValueString {
    yield()
    return ValueString("x")
}
suspend fun suspendAndReturnNormalString(): String {
    yield()
    return "x"
}
```

This prints:

```
> Task :app:run FAILED
x
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@65a15628, Continuation at graphqlkotlinvalueclassproblem.AppKt.suspendAndReturnValueString(App.kt:21)@1921ad94]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.EventLoopImplBase.shutdown(EventLoop.common.kt:225)
        at kotlinx.coroutines.EventLoop.decrementUseCount(EventLoop.common.kt:113)
        at kotlinx.coroutines.EventLoop.decrementUseCount$default(EventLoop.common.kt:107)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:91)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at graphqlkotlinvalueclassproblem.AppKt.main(App.kt:8)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [BlockingCoroutine{Cancelled}@561868a0, BlockingEventLoop@65a15628]
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:166)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:232)
        ... 10 more
Exception in thread "main" java.lang.IllegalArgumentException: argument type mismatch
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.InlineClassAwareCaller.call(InlineClassAwareCaller.kt:146)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:149)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at graphqlkotlinvalueclassproblem.AppKt$main$1.invokeSuspend(App.kt:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at graphqlkotlinvalueclassproblem.AppKt.main(App.kt:8)
```

This reproduces with Kotlin 1.8.21 and Coroutines 1.7.1, as well as some combos of older versions.

It looks like the kotlin-reflect InlineClassAwareCaller doesn't understand that the thing it is calling might be returning `COROUTINE_SUSPENDED` instead of the expected String, and tries to put that object into the box.

I don't know if there's any sort of workaround available here but would love to know if anyone knows of one.

**Comment by glasser** [comment]
I'm not sure if this is a kotlin-reflect or a kotlinx.coroutines issue; I filed it at https://youtrack.jetbrains.com/issue/KT-58887 too.

**Comment by qwwdfsad** [comment]
Thanks! This is a bug in `callSuspendBy` in the reflection itself, we'll address it there. Thanks for filing the KT-ticket as well!
