### ISSUE TITLE
CoroutinesInternalError: ClassCastException

### ISSUE THREAD

**Issue by TelephoneTan** [Kotlin/kotlinx.coroutines#3853]
**Describe the bug**

I have some code. When I run them on `JVM` they throws internal exceptions:

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[java.util.concurrent.ThreadPoolExecutor@363f9bff[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1], Continuation at ExecutorKt.callSuspend(Executor.kt:35)@3d65a7dc]){Cancelled}@3f1ef117. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:166)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 3 more
```

**Provide a Reproducer**

https://github.com/TelephoneTan/kotlinx-coroutines-bug

Just run the test case `TestBug.test` to reproduce.

https://github.com/TelephoneTan/kotlinx-coroutines-bug/blob/c1cbed9c1bd8ee62cb739f8ff18b55aeae7de361/src/test/java/TestBug.java#L10C12-L10C12

Help!🙏🙏🙏

**Comment by TelephoneTan** [comment]
Anyone?

**Comment by TelephoneTan** [comment]
@elizarov

**Comment by TelephoneTan** [comment]
@qwwdfsad

**Comment by qwwdfsad** [comment]
Please don't ping the maintainers directly; it's unlikely to speedup the process, but can lead to quite the opposite.

You are invoking coroutines from Java, which is an unstable feature as is (as it requires a precise calling convention described here: https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md).

The error indicates that the underlying continuation was resumed/completed twice under the hood; You probably have to return `COROUTINE_SUSPENDED` somewhere in your code or delegate the return value to the corresponding suspend call

**Comment by werner77** [comment]
Suffering from the same issue. Even if an application or library misuses the Coroutines API (e.g. completing it twice) it should not result in such an obscure error right? IMHO it should fail immediately at the point where the illegal call is made, not on some ClassCastException in the internal code.
