### ISSUE TITLE
Suspected race condition in DebugProbes.install w.r.t. ByteBuddy

### ISSUE THREAD

**Issue by SanjayVas** [Kotlin/kotlinx.coroutines#3865]
**Describe the bug**

Sometimes DebugProbes.install fails with the following:

```
Caused by: java.lang.IllegalStateException: The Byte Buddy agent is not installed or not accessible
        at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy.fromInstalledAgent(ClassReloadingStrategy.java:171)
        at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.attach(Attach.kt:29)
        at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:17)
        at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:15)
        at kotlinx.coroutines.debug.internal.DebugProbesImpl.install(DebugProbesImpl.kt:85)
```

```
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy.fromInstalledAgent(ClassReloadingStrategy.java:167)
        ... 11 more
Caused by: java.lang.IllegalStateException: The Byte Buddy agent is not loaded or this method is not called via the system class loader
        at kotlinx.coroutines.repackaged.net.bytebuddy.agent.Installer.getInstrumentation(Installer.java:61)
        ... 16 more
```

This occurs more frequently when running multiple tests in parallel[^1], so I suspect there's a race condition that is sensitive to load.

JDK version: Azul OpenJDK 11
kotlinx.coroutines version: 1.6.4 (originally reproduced on 1.6.2)
Kotlin release version: 1.6.21

**Provide a Reproducer**

So far I've only been able to reproduce the issue in this large test that uses TestContainers: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d0ffec21d8214116313f4c65d609bab84ad6f09/src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt

In that test `DebugProbes.install` is called via `CoroutinesTimeout`.

[^1]: See documentation for [Bazel](https://bazel.build/) for more information on how it runs tests in parallel.

**Comment by vsartiushkin** [comment]
Hi! I have reproduced the issue with the mentioned versions.
The root issue seems to be in hsperfdata file conflicts across sandboxes in Bazel that leads to ByteBuddy silent failure. See [ByteBuddy #1111(comment)](https://github.com/raphw/byte-buddy/issues/1111#issuecomment-922459025).
The issue is already fixed in Bazel since version 7.0.0 and cannot be reproduced with default settings. 
There is a [workaround](https://github.com/bazelbuild/bazel/issues/3236#issuecomment-587752609) available for Bazel versions prior to 7.0.0.

Current version of the coroutines library already includes the ByteBuddy fix for the silent failure.
