### ISSUE TITLE
NoClassDefFoundError for BufferedChannelKt but not BufferedChannel

### ISSUE THREAD

**Issue by jonalmeida** [Kotlin/kotlinx.coroutines#3882]
**Describe the bug**

In our application, we are receiving a rather odd stack trace from our Android 5 (API 21) users across a range of devices with the coroutine library 1.7.2:

```
java.lang.NoClassDefFoundError: kotlinx.coroutines.channels.BufferedChannelKt
    at kotlinx.coroutines.channels.BufferedChannel.<init>(BufferedChannel.kt:15)
    at kotlinx.coroutines.channels.ChannelKt.Channel$default(Channel.kt:46)
    at androidx.datastore.core.SimpleActor.<init>(SimpleActor.kt:18)
    at androidx.datastore.core.SingleProcessDataStore.<init>(SingleProcessDataStore.kt:68)
    at org.mozilla.fenix.components.Components$appStore$2.invoke(Components.kt:304)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
    at org.mozilla.fenix.components.Components.getAppStore(Components.kt:3)
    at org.mozilla.fenix.components.Components$useCases$2.invoke(Components.kt:59)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
    at org.mozilla.fenix.components.Components.getUseCases(Components.kt:3)
    at org.mozilla.fenix.FenixApplication.initialize(FenixApplication.kt:705)
    at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5245)
    at android.app.ActivityThread.access$1600(ActivityThread.java:181)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Source: https://crash-stats.mozilla.org/report/index/597f5939-83fe-446f-bcf0-979400230906

Our first instinct was that this may have been a proguarding issue and adding an appropriate rule would suffice. However, on closer inspection, the trace shows that we have reached the `BufferedChannel` init block, and from there the `BufferedChannelKt` class (the one which contain the static methods) is the one that's missing, which seems unlikely.

Could this be a bug in some part of the coroutine library's optimizations?

**Provide a Reproducer**

We have tried to reproduce this bug on an API 21 device and emulator but it seems to be intermittent (whether in a sample app or production).

**Comment by dkhalanskyjb** [comment]
> Could this be a bug in some part of the coroutine library's optimizations?

I don't think so. We don't do anything fancy there. Here are the proguard rules bundled with the library: https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/jvm/resources/META-INF/proguard

I would guess that this is some Android-specific problem that should be reported directly to Google's issue tracker. Since you say it's across a range of devices, it's unlikely that a particular Android vendor is at fault.

> We have tried to reproduce this bug on an API 21 device and emulator but it seems to be intermittent (whether in a sample app or production).

Did you manage to find a way to reproduce it on your own configuration, even if intermittently?

**Comment by jonalmeida** [comment]
> Did you manage to find a way to reproduce it on your own configuration, even if intermittently?

Unfortunately, no. I also do not have access to any of those API 21 devices that have also been reported.

**Comment by jonalmeida** [comment]
I'm going to close this because it doesn't seem actionable from what I've understood in my own research without more logs/details into what happened before the crash occurred.
