### ISSUE TITLE
The main looper is not available

### ISSUE THREAD

**Issue by s1ee** [Kotlin/kotlinx.coroutines#4015]
Currently running some unit tests in Android. There is a rule setup:

````
class MainDispatcherRule(
    val testDispatcher: TestDispatcher = UnconfinedTestDispatcher(),
) : TestWatcher() {
    override fun starting(description: Description) {
        Dispatchers.setMain(testDispatcher)
    }

    override fun finished(description: Description) {
        testDispatcher.cancel()
        Dispatchers.resetMain()
    }
}
````

However, I have been seeing tests fail with the error:
````
Suppressed: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[UnconfinedTestDispatcher[scheduler=kotlinx.coroutines.test.TestCoroutineScheduler@11fb8e1f], Continuation at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:57)@48720eb5]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
		at app//kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
		at app//kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:382)
		at app//kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
		at app//kotlinx.coroutines.internal.ScopeCoroutine.afterCompletion(Scopes.kt:27)
		at app//kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:940)
		at app//kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:25)
		at app//kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1159)
		at app//kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1497)
		at app//kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:325)
		at app//kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:242)
		at app//kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
		at app//kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
		at app//kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
		at app//kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
		at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at app//kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
		at app//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
		Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(514), "coroutine#514":DispatchedCoroutine{Cancelled}@548a7ae0, UnconfinedTestDispatcher[scheduler=kotlinx.coroutines.test.TestCoroutineScheduler@11fb8e1f]]
	Caused by: java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used
		at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:115)
		at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
		at kotlinx.coroutines.test.internal.TestMainDispatcher.isDispatchNeeded(TestMainDispatcher.kt:31)
		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
		at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
		... 20 more
	Caused by: java.lang.IllegalStateException: The main looper is not available
		at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:55)
		at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
		at kotlinx.coroutines.test.internal.TestMainDispatcherFactory.createDispatcher(TestMainDispatcherJvm.kt:15)
		at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
		at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
		at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
		at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:24)
		at kotlinx.coroutines.test.internal.TestMainDispatcher$Companion.getCurrentTestDispatcher$kotlinx_coroutines_test(TestMainDispatcher.kt:51)
		at kotlinx.coroutines.test.internal.TestMainDispatcher$Companion.getCurrentTestScheduler$kotlinx_coroutines_test(TestMainDispatcher.kt:54)
		at kotlinx.coroutines.test.TestCoroutineDispatchersKt.UnconfinedTestDispatcher(TestCoroutineDispatchers.kt:87)
		at kotlinx.coroutines.test.TestCoroutineDispatchersKt.UnconfinedTestDispatcher$default(TestCoroutineDispatchers.kt:83)
````

I am using version `1.7.3` for both `org.jetbrains.kotlinx:kotlinx-coroutines-core` and `org.jetbrains.kotlinx:kotlinx-coroutines-android`

**Comment by dkhalanskyjb** [comment]
Without a reproducer, it's tough to say what you're doing incorrectly. Maybe you created the rule, but are not applying it. Maybe `starting` and `finishing` don't run. Maybe you're mixing together junit4 and junit5.

* You can try following this instruction: https://developer.android.com/kotlin/coroutines/test#setting-main-dispatcher
* Try adding `println` or setting a breakpoint before `Dispatchers.setMain` and making sure it gets called. In any case, the error you're getting means that either `setMain` was not called or `resetMain` was called before the test was run.

Also, `testDispatcher.cancel()` doesn't do anything.
