### ISSUE TITLE
Missing DebugProbesImpl.isInstalled method causes test failure to be swallowed

### ISSUE THREAD

**Issue by AlexLamaison-UnlikelyAI** [Kotlin/kotlinx.coroutines#4021]
**Describe the bug**

Some tests which are failing print a stack trace about a missing `DebugProbesImpl.isInstalled` method in the `InvokeOnCancelling` completion handler instead of printing the actual test failure.  This makes tests hard to debug.

Example output
```
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCancelling@5e390fcd[job@6366e361] for "coroutine#1":TimeoutCoroutine(timeMillis=10000){Cancelling}@6366e361

	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1482)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
	at kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:662)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoSuchMethodError: 'boolean kotlinx.coroutines.debug.internal.DebugProbesImpl.isInstalled$kotlinx_coroutines_core()'
	at kotlinx.coroutines.test.TestBuildersJvmKt.dumpCoroutines(TestBuildersJvm.kt:20)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:335)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:333)
	at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	... 9 more
```

I'm using kotlinx.coutines 1.7.3 with Kotlin version 1.9.22.

**Provide a Reproducer**
This snippet reproduces the problem for me, although only intermittently causes the test case to fail.  The `CompletionHandlerException` is printed regardless.
```
package foo

import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest(classes = [ReproTest.Config::class])
@AutoConfigureWebTestClient(timeout = "1000")
class ReproTest {
  @SpringBootConfiguration class Config

  @Test fun supportsAndQueries() = runTest { Thread.sleep(10000) }
}
```

**Comment by dkhalanskyjb** [comment]
Are you using an older version of `kotlinx-coroutines-test` than `kotlinx-coroutines-core`?

**Comment by AlexLamaison-UnlikelyAI** [comment]
They both use the same property value in the POM, set to 1.7.3

**Comment by dkhalanskyjb** [comment]
Does the issue reproduce with both set to 1.8.0-RC2?

**Comment by AlexLamaison-UnlikelyAI** [comment]
Apologies, it seems I _was_ using mixed versions after all.  A parent POM pulled in a different version of Kotlin/Kotlinx.coroutines

**Comment by AlexLamaison-UnlikelyAI** [comment]
It appears fixing the parent dependency isn't enough and I also have to exclude everything that transitively imports one of the kotlinx-coroutine modules transitively.  Examples are kotest, turbine, resilience4j, mockk.  Is this expected?

**Comment by dkhalanskyjb** [comment]
I think this means that some of your transitive dependencies require a newer version of coroutines than what you've set. Without knowing the specifics of your build configuration, I can't suggest anything except to make your versions match somehow. If you're using Gradle, you can check the output of the `gradle dependencies` and/or `gradle dependencyInsight` command and determine which version is used in the end and why. Also, please look into depending on `kotlinx-coroutines-bom`: https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import

**Comment by AlexLamaison-UnlikelyAI** [comment]
Thanks, the BOM route fixed it without me having to manually exclude things throughout
