### ISSUE TITLE
UncaughtExceptionsBeforeTest: There were uncaught exceptions before the test started. 

### ISSUE THREAD

**Issue by marlonlom** [Kotlin/kotlinx.coroutines#4070]
### What happened? What should have happened instead?
When running a testcase, it fails and in the stacktrace shows the following trace:

```
kotlinx.coroutines.test.UncaughtExceptionsBeforeTest: There were uncaught exceptions before the test started. Please avoid this, as such exceptions are also reported in a platform-dependent manner so that they are not lost.
	at app//kotlinx.coroutines.test.TestScopeImpl.enter(TestScope.kt:239)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:309)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:160)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
```

**Provide a Reproducer**
Im using a class name Main

```kotlin
/* MainDispatcherRule: */
@OptIn(ExperimentalCoroutinesApi::class)
class MainDispatcherRule(
  private val testDispatcher: TestDispatcher = UnconfinedTestDispatcher()
) : TestWatcher() {
  override fun starting(description: Description) {
    Dispatchers.setMain(testDispatcher)
  }

  override fun finished(description: Description) {
    Dispatchers.resetMain()
  }
}
```

```kotlin
/* test case: */
class SettingsViewModelTest {
@get:Rule
  val mainDispatcherRule = MainDispatcherRule()

  private lateinit var viewModel: SettingsViewModel

  @MockK
  private lateinit var preferencesDataStore: DataStore<Preferences>

  @Before
  fun setup() {
    MockKAnnotations.init(this)
  }

  @Test
  fun `Should return default settings from local storage`() = runTest {
    coEvery { preferencesDataStore.data } returns flowOf(emptyPreferences())
    viewModel = SettingsViewModel(UserPreferencesRepository(preferencesDataStore))
    val uiState = viewModel.uiState.first()
    assertNotNull(uiState)
    when (uiState) {
      is SettingsUiState.Success -> {
        assertNotNull(uiState.settings)
        assertFalse(uiState.settings.useDarkTheme)
        assertTrue(uiState.settings.useDynamicColor)
        assertTrue(uiState.settings.isOnboarding)
      }

      else -> fail()
    }
  }

}
```

In this scenario, im trying to mock the DataStore<Preferences>, the testcase is configured with mockk library, and, when running the testcase using junit4, it fails woth the stacktrace showing the `UncaughtExceptionsBeforeTest` Detail.

**Comment by dkhalanskyjb** [comment]
Please look at the list of the exceptions suppressed by the `UncaughtExceptionsBeforeTest` and make sure these exceptions aren't thrown. These can also be exceptions that come from other tests but weren't caught in time, because they happened after the execution had already left their `runTest` block.

**Comment by MahmoudLkashef** [comment]
This exception happened with me you need to check stubbing data you need to check before initializing the viewmodel you are stubbing if you have something in init block 

the error may came from other tests not this test that referenced in the logcat

**Comment by ursusursus** [comment]
I'm hitting this as well.
Just so I understand - I need to go over all of test code in the whole project? That's surely not feasible.

 Isn't there a way to surface the actual issue?

**Comment by tinacious** [comment]
I ran into this as well. It requires looking pretty deep into the stack trace but I found that the exception thrown wasn't related to the failing test but another test in the package. Another test didn't have `mockk` set up correctly, which resulted in `mockk` throwing an exception related to an answer not being provided. I was able to narrow it down by running tests per package and per file in Android Studio. It's a bit annoying but possible to find it this way.

My errors were not related to suppressed exceptions but rather exceptions that weren't thrown on time from another test.

**Comment by glasser** [comment]
> Please look at the list of the exceptions suppressed by the `UncaughtExceptionsBeforeTest`

Do these actually get logged anywhere or show up in the stacktrace? When I find `UncaughtExceptionsBeforeTest` in a test log (especially in a nondeterministic way) I can't figure out where to actually look to find out what the relevant exceptions were.

**Comment by dkhalanskyjb** [comment]
They should be part of the `UncaughtExceptionsBeforeTest` stacktrace. Here's the test program I used:
```kotlin
import kotlinx.coroutines.test.*
import kotlinx.coroutines.*

fun main() {
    var job: Job? = null
    // run the first test
    runTest {
        // start a job that will fail after the test
        job = GlobalScope.launch {
            Thread.sleep(100)
            throw IllegalStateException("Hi!")
        }
    }
    // wait for the failing job to finish
    runBlocking {
        job!!.join()
    }
    println("Here, the exception should have been printed")
    // this invocation will fail
    runTest {
        delay(100)
    }
}
```

Here's the output I get:
```
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Hi!
	at MainKt$main$1$1.invokeSuspend(Main.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ea7aaf2, Dispatchers.Default]
Here, the exception should have been printed
Exception in thread "main" kotlinx.coroutines.test.UncaughtExceptionsBeforeTest: There were uncaught exceptions before the test started. Please avoid this, as such exceptions are also reported in a platform-dependent manner so that they are not lost.
	at kotlinx.coroutines.test.TestScopeImpl.enter(TestScope.kt:238)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:308)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:167)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:159)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at MainKt.main(Main.kt:20)
	at MainKt.main(Main.kt)
	Suppressed: java.lang.IllegalStateException: Hi!
		at MainKt$main$1$1.invokeSuspend(Main.kt:11)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
		Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@ea7aaf2, Dispatchers.Default]
```
The exception gets logged twice: once when it actually happens, and then, once again when `UncaughtExceptionsBeforeTest` gets thrown.
