### ISSUE TITLE
combination of produce, while(isActive), select{} causes class-cast exception

### ISSUE THREAD

**Issue by Groostav** [Kotlin/kotlinx.coroutines#448]
```kt
@Test fun `when using select in producer to merge channels should operate normally`() = runBlocking<Unit> {

    val sourceOne = produce { send(1); send(2); send(3) }

    //inlining this var causes the test to pass
    var s1: ReceiveChannel<Any>? = sourceOne

    val merged = produce<Any>{
        while(isActive){ //removing this while causes the test to pass
            val next = select<Any> {
                s1?.onReceive { it }
            }
        }
    }

    merged.receiveOrNull() //throws class-cast exception
}
```

throws 

```
java.lang.ClassCastException: kotlinx.coroutines.experimental.channels.ProducerCoroutine cannot be cast to kotlinx.coroutines.experimental.selects.SelectClause1

	at groostav.kotlinx.exec.CoroutineTests$when using select in producer to merge channels should operate normally$1$merged$1.doResume(CoroutineTests.kt:40)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by qwwdfsad** [comment]
This is a bug in the compiler: https://youtrack.jetbrains.com/issue/KT-24209

The easiest workaround is to replace `s1.on*` with hand-rolled nullcheck
