### ISSUE TITLE
Cancel all observable meet exception

### ISSUE THREAD

**Issue by CzBiX** [Kotlin/kotlinx.coroutines#450]
Old code:
```kotlin
import java.util.concurrent.TimeUnit
import rx.Observable

fun fetchFromNetwork(): Observable<String> {
    return Observable.timer(1, TimeUnit.HOURS).map { "Result from network" }
}

fun getResult(): Observable<Boolean> {
    return fetchFromNetwork().map { "network" in it }
}

val subscription = getResult().subscribe()
subscription.unsubscribe()
```

New code:
```kotlin
import kotlinx.coroutines.experimental.delay
import kotlinx.coroutines.experimental.launch
import kotlinx.coroutines.experimental.rx1.await
import kotlinx.coroutines.experimental.rx1.awaitFirst
import kotlinx.coroutines.experimental.rx1.rxObservable
import kotlinx.coroutines.experimental.rx1.rxSingle
import java.util.concurrent.TimeUnit

fun fetchFromNetwork() = rxObservable {
    delay(1, TimeUnit.HOURS)
    send("Result from network")
}

fun getResult() = rxObservable {
    val result = fetchFromNetwork().awaitFirst()
    send("network" in result)
}

val subscription = getResult().subscribe()
subscription.unsubscribe()
```

The old code will cancel job quietly, but the new code will throw an exception: 
```
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at rx.exceptions.CompositeException.getCause(CompositeException.java:129)
	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
	at java.lang.Throwable.printStackTrace(Throwable.java:667)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at kotlinx.coroutines.experimental.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:30)
	at kotlinx.coroutines.experimental.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:47)
	at kotlinx.coroutines.experimental.rx1.RxObservableCoroutine.doLockedSignalCompleted(RxObservable.kt:176)
	... 32 more
Caused by: java.util.NoSuchElementException: Sequence contains no elements
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:115)
	at rx.internal.operators.OperatorTake$1.onCompleted(OperatorTake.java:56)
	at kotlinx.coroutines.experimental.rx1.RxObservableCoroutine.doLockedSignalCompleted(RxObservable.kt:174)
	... 32 more
Caused by: java.lang.IllegalStateException: Unexpected update, state: CancelledContinuation[kotlinx.coroutines.experimental.JobCancellationException: Job was cancelled normally; job=RxObservableCoroutine{Cancelling}@73d7e407], update: CompletedExceptionally[java.util.NoSuchElementException: Sequence contains no elements]
	at kotlinx.coroutines.experimental.AbstractContinuation.resumeImpl(AbstractContinuation.kt:293)
	at kotlinx.coroutines.experimental.AbstractContinuation.resumeWithException(AbstractContinuation.kt:158)
	at kotlinx.coroutines.experimental.rx1.RxAwaitKt$awaitOne$2$1.onError(RxAwait.kt:135)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	... 35 more
```

Is my usage wrong?

**Comment by elizarov** [comment]
I cannot reproduce this issue. This is the code I'm running https://gist.github.com/elizarov/1c2d28a0feabac6814b599eb1a7cb276 and it completes without exceptions with `kotlinx.coroutines` version `0.23.4` and RxJava `1.3.6`. What versions are you using?

**Comment by CzBiX** [comment]
My environment:
```
Oracle Java 1.8.0_171
Kotlin 1.2.51
RxJava 1.3.6
coroutines 0.23.4
```

I found that JVM will not throw exception when it exit immediately.
Just add `Thread.sleep(10000)` after `unsubscribe` can reproduce issue.

**Comment by elizarov** [comment]
Confirm. Reproduces for me.

**Comment by elizarov** [comment]
I've minimized reproducer to a full single-threaded code:

```
fun fetchFromNetwork(context: CoroutineContext) = rxObservable<String>(context) {
    yield()
}

fun main(args: Array<String>) = runBlocking<Unit> {
    val job = launch(coroutineContext, CoroutineStart.UNDISPATCHED) {
        fetchFromNetwork(coroutineContext).awaitFirst()
    }
    job.cancel()
}
```

**Comment by elizarov** [comment]
Note, that related issues is also https://youtrack.jetbrains.com/issue/KT-25046
