### ISSUE TITLE
NoClassDefFoundError: kotlinx/coroutines/swing/Swing

### ISSUE THREAD

**Issue by antonKozyriatskyi** [Kotlin/kotlinx.coroutines#474]
Trying to build a plugin for IDEA with coroutines, and getting following exception at runtime:
```
kotlinx/coroutines/swing/Swing
java.lang.NoClassDefFoundError: kotlinx/coroutines/swing/Swing
	at WifiAdbConnectorWindowFactory.createToolWindowContent(WifiAdbConnectorWindowFactory.kt:52)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:571)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:403)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.contentManager(ContentTabLabel.java:265)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.canBeClosed(ContentTabLabel.java:167)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel$1.getAvailable(ContentTabLabel.java:55)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.getPreferredSize(ContentTabLabel.java:202)
	at java.awt.FlowLayout.preferredLayoutSize(FlowLayout.java:414)
	at java.awt.Container.preferredSize(Container.java:1797)
	at java.awt.Container.getPreferredSize(Container.java:1781)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1665)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.getPreferredSize(ToolWindowContentUi.java:243)
	at java.awt.FlowLayout.preferredLayoutSize(FlowLayout.java:414)
	at java.awt.Container.preferredSize(Container.java:1797)
	at java.awt.Container.getPreferredSize(Container.java:1781)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1665)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1797)
	at java.awt.Container.getPreferredSize(Container.java:1781)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1665)
	at com.intellij.openapi.wm.impl.ToolWindowHeader.getPreferredSize(ToolWindowHeader.java:425)
	at java.awt.BorderLayout.layoutContainer(BorderLayout.java:815)
	at java.awt.Container.layout(Container.java:1511)
	at java.awt.Container.doLayout(Container.java:1500)
	at java.awt.Container.validateTree(Container.java:1696)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validate(Container.java:1631)
	...
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.swing.Swing PluginClassLoader[anton.kozyriatskyi.wifi-adb, 1.0-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@4ab1bbbb
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 164 more
```

Kotlin version is `1.3-M1` (tried also `1.2.50` and `1.2.51`).
Following dependencies are included:
```groovy
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.24.0-eap13'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-common:0.24.0-eap13'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-swing:0.24.0-eap13' 
```

`kotlinx.coroutines.swing.Swing` is absolutely visible in IDE and I can jump into it's source code.

**Comment by elizarov** [comment]
The corresponding classes seem to be missing from your plugin classpath.

**Comment by antonKozyriatskyi** [comment]
@elizarov probably you're right. How to add it to classpath? I haven't found any instructions in README.

**Comment by elizarov** [comment]
@antonKozyriatskyi Franky, I don't see how that is related to `kolinx.coroutines`. That is the question to whatever Gradle plugin you are using to build IDEA plugin and how you have configured it. If you are using https://github.com/JetBrains/gradle-intellij-plugin then I'd suggest to repost the question there.
