### ISSUE TITLE
withTimeoutOrNull throw TimeoutCancellationException

### ISSUE THREAD

**Issue by kobe2000** [Kotlin/kotlinx.coroutines#498]
Hi,
I understand that ```withTimeoutOrNull``` never throw timeout exception, does it?

I will try to reproduce it.

The code sample is
```
val ch = cudChannel.openSubscription()
try {
    var lastPingTime = System.currentTimeMillis()
    while (true) {
        val cud = withTimeoutOrNull(1000) {
            ch.receive()
        }
        if (cud != null) {
            wc.writeString(cud.first)
            wc.writeBoolean(cud.second)
        } else if (System.currentTimeMillis() - lastPingTime > 6000) {
            wc.writeString("")
            wc.writeBoolean(false)
        } else {
            continue
        }
        lastPingTime = System.currentTimeMillis()
        withTimeout(30000) {
            rc.readInt()
        }
    }
} finally {
    ch.cancel()
}
```

The stacktrace is
```
kotlinx.coroutines.experimental.TimeoutCancellationException: Timed out waiting for 1000 MILLISECONDS
        at kotlinx.coroutines.experimental.ScheduledKt.TimeoutCancellationException(Scheduled.kt:202)
        at kotlinx.coroutines.experimental.TimeoutCoroutine.run(Scheduled.kt:100)
        at kotlinx.coroutines.experimental.EventLoopBase$DelayedRunnableTask.run(EventLoop.kt:322)
        at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:148)
        at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:60)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by qwwdfsad** [comment]
Hi, could you please a self-contained example?
What types are rc and wc?

**Comment by kobe2000** [comment]
rc wc are sock read channel and write channel.
This is the first time I meet the problem, I worry that the self-contained example maybe a single piece of withTimeoutOrNull API invocation code
