### ISSUE TITLE
how to handler exception while use async

### ISSUE THREAD

**Issue by miaoyongjun** [Kotlin/kotlinx.coroutines#543]
```
val handler = CoroutineExceptionHandler { _, exception ->
            println("Caught $exception")
        }
        val deferred = async(handler) {
            throw ArithmeticException() // Nothing will be printed, relying on user to call deferred.await()
        }
        deferred.await()
```
Error:
```
Test$main$deferred$1.doResume(Test.kt:15)
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

if change async to launch , it is work

**Comment by qwwdfsad** [comment]
Yes, it's because `async` requires follow-up `await` call which either returns computed result or throws an exception if coroutine failed.

I think we can improve our guide to be more precise about async/await difference
