### ISSUE TITLE
[ERRATA]In coroutines-guide, the section about description of the automatical exception handler is not as expected.

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#578]
> Coroutine builders come in two flavors: propagating exceptions automatically (launch and actor) or exposing them to users (async and produce). The former treat exceptions as unhandled, similar to Java's Thread.uncaughExceptionHandler, while the latter are relying on the user to consume the final exception, for example via await or receive (produce and receive are covered later in Channels section).

I find, the automatical handler is only for GlobalScope coroutine. This section should be corrected.

Example here:

```
fun main() {exceptionAutomatically()}

fun exceptionAutomatically() = runBlocking {
    val request = GlobalScope.launch { <------ The output of GlobalScope and without GlobalScope as child of runBlocking is different.
        delay(5000)
        val y = 1 / 0
        println("result: $y")
    }
    println("Sent request")
    request.join()//Waiting for the result.
    println("Done")
}
``` 

**with GlobalScope is as expected: I see Done at last line. The program can be processed.** 
```
Sent request
Exception in thread "ForkJoinPool.commonPool-worker-2 @coroutine#2" java.lang.ArithmeticException: / by zero
	at MainKt$exceptionAutomatically$1$request$1.invokeSuspend(main.kt:457)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:146)
	at kotlinx.coroutines.AbstractContinuation.run(AbstractContinuation.kt:19)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1409)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

Done
```

**without GlobalScope is not, no Done in the output. The program can't be processed.**
```
Sent request
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at MainKt$exceptionAutomatically$1$request$1.invokeSuspend(main.kt:457)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:67)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:178)
	at kotlinx.coroutines.AbstractContinuation.dispatchResume(AbstractContinuation.kt:191)
	at kotlinx.coroutines.AbstractContinuation.completeStateUpdate(AbstractContinuation.kt:343)
	at kotlinx.coroutines.AbstractContinuation.updateStateToFinal(AbstractContinuation.kt:315)
	at kotlinx.coroutines.AbstractContinuation.resumeImpl(AbstractContinuation.kt:273)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuation.kt:313)
	at kotlinx.coroutines.EventLoopBase$DelayedResumeTask.run(EventLoop.kt:309)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:140)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:70)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.exceptionAutomatically(main.kt:452)
	at MainKt.main(main.kt:45)
```

**Comment by qwwdfsad** [comment]
`GlobalScope` handles exception by itself, so failing `luanch` prints `ArithmeticException` into the console.

Without global scope `launch` inherits context from the `runBlocking` scope and `runBlocking` handles the exception by rethrowing it, there is not bug.

Though I will think about how we can improve our guide, thank you.
