### ISSUE TITLE
compilation failure with 0.26.1-eap13

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.coroutines#591]
I cannot compile a project with kotlinx.coroutines `0.26.1-eap13` and kotlin `1.3-M2`.

Compilation succeed with `0.26.0-eap13` so it is definitely a regression introduced in `0.26.1-eap13`

Repoducible examples:
* `0.26.0-eap13` (successful): https://github.com/jcornaz/miop/tree/8a1f0451f2b21f23a6cd1f84d3453ca7362f7e3f
* `0.26.1-eap13` (failure): https://github.com/jcornaz/miop/tree/2d9ff0478345b0869353daf25a3783e60a2f35be

Difference between the two examples: https://github.com/jcornaz/miop/commit/2d9ff0478345b0869353daf25a3783e60a2f35be

Abstract of the error:
```
Cause: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
Element is unknownThe root cause was thrown at: KotlinTypeMapper.java:116
File being compiled at position: (15,5) in /home/slimaku/Workspace/miop/internal/test/common/src/main/kotlin/com/github/jcornaz/miop/test/ManualTimer.kt
The root cause was thrown at: TransformationMethodVisitor.java:88
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:1033)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:449)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:266)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:183)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:154)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:196)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:155)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:75)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:128)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:161)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	... 43 more
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
await (ILkotlin/coroutines/Continuation;)Ljava/lang/Object;:
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
    TRYCATCHBLOCK L0 L1 L2 null
    TRYCATCHBLOCK L2 L3 L2 null
   L4
   L5
   L6

[...] 

Cause: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
Element is unknownThe root cause was thrown at: KotlinTypeMapper.java:116
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:88)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:1021)
	... 57 more
Caused by: java.lang.IllegalStateException: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$1.processErrorType(KotlinTypeMapper.java:116)
	at org.jetbrains.kotlin.load.kotlin.TypeSignatureMappingKt.mapType(typeSignatureMapping.kt:91)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:512)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameterType(KotlinTypeMapper.java:1518)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameter(KotlinTypeMapper.java:1488)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameter(KotlinTypeMapper.java:1477)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.lambda$mapSignatureWithCustomParameters$4(KotlinTypeMapper.java:1295)
```

**Comment by jcornaz** [comment]
Ok, thanks @qwwdfsad
