### ISSUE TITLE
Warnings while using Android Studio 3.3 R8 Shrinking

### ISSUE THREAD

**Issue by wezley98** [Kotlin/kotlinx.coroutines#758]
Getting the following warnings when using R8 in AS 3.3, everything works as expected with the app, just wondering if this is expected behaviour? 

```
   implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.30.2"
   implementation "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:0.30.2"
   implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:0.30.2"
```

The following proguard rules don't help:
```
# Coroutines
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
# Keep Coroutine class names. See https://github.com/Kotlin/kotlinx.coroutines/issues/657.
# This should be removed when bug is fixed.
-keepnames class kotlinx.** { *; }

-dontwarn org.jetbrains.annotations.**
-keep class kotlin.Metadata { *; }
```

```
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$toCollection$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterNotTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$groupByTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$indexOf$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$groupByTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterNotTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$lastIndexOf$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$associateByTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$associateByTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.rx2.RxObservableCoroutine$sendSuspend$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$toMap$2\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$toChannel$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.reactive.PublisherCoroutine$sendSuspend$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$associateTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$3\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$fold$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$mapTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$foldIndexed$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Unexpected error while reading kotlinx.coroutines.experimental.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$1\u0027s kotlin.Metadata: null","sources":[{}],"tool":"D8"}
```

**Comment by qwwdfsad** [comment]
Hi, is this problem still reproducible with version 1.0.0?
Also, could you please provide a sample project? `androidx` changes too fast with every minor version, so it's hard to tell whether it's not specific jettifier version bug or not without a reproducer

**Comment by wezley98** [comment]
@qwwdfsad Seems ok now, no errors with AS 3.3.0-Beta3 and coroutines v1.0.0

**Comment by kimcy929** [comment]
App crash when **android.enableR8 = true,** before I set **android.enableR8.fullMode=true**, it hadn't the problem, but maybe android.enableR8.fullMode=true don't shrinker APK.

Crashlytics highlighted this line
**kotlin.coroutines.jvm.internal.DebugMetadataKt.getDebugMetadataAnnotation(DebugMetadata.kt:1)**

```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find kotlin.c.b.a.f.i
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
       at java.lang.Class.getAnnotation(Class.java:343)
       at kotlin.coroutines.jvm.internal.DebugMetadataKt.getDebugMetadataAnnotation(DebugMetadata.kt:1)
       at kotlin.coroutines.jvm.internal.DebugMetadataKt.getStackTraceElement(DebugMetadata.kt:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.getStackTraceElement(ContinuationImpl.kt:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.toString(ContinuationImpl.kt:1)
       at kotlin.coroutines.jvm.internal.SuspendLambda.toString(ContinuationImpl.kt:3)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at kotlinx.coroutines.DebugKt.toDebugString(Debug.kt:3)
       at kotlinx.coroutines.DispatchedContinuation.toString(Dispatched.kt:1)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5550)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```

**Comment by kimcy929** [comment]
Oh I saw note in the blog
https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html
**R8 also has full mode that is not directly compatible with Proguard**

**Comment by jrcacd** [comment]
Android Studio 3.4 Canary 8
Coroutines 1.1.0-alpha

Generate obfuscated bundle.

Results:
```
15:07:53.393 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$1's kotlin.Metadata: null
15:07:53.400 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$1's kotlin.Metadata: null
15:07:53.477 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$3's kotlin.Metadata: null
15:07:53.485 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$3's kotlin.Metadata: null
15:07:53.558 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$3's kotlin.Metadata: null
15:07:53.569 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$fold$1's kotlin.Metadata: null
15:07:53.637 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$1's kotlin.Metadata: null
15:07:53.705 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toChannel$1's kotlin.Metadata: null
15:07:53.811 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$3's kotlin.Metadata: null
15:07:53.814 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$indexOf$1's kotlin.Metadata: null
15:07:53.819 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$foldIndexed$1's kotlin.Metadata: null
15:07:54.016 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$1's kotlin.Metadata: null
15:07:54.070 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toCollection$1's kotlin.Metadata: null
15:07:54.087 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$lastIndexOf$1's kotlin.Metadata: null
15:07:54.428 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$1's kotlin.Metadata: null
15:07:54.431 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$1's kotlin.Metadata: null
15:07:54.440 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$3's kotlin.Metadata: null
15:07:54.461 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$1's kotlin.Metadata: null
15:07:54.514 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$3's kotlin.Metadata: null
15:07:54.699 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateTo$1's kotlin.Metadata: null
15:07:54.702 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$3's kotlin.Metadata: null
15:07:54.704 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$1's kotlin.Metadata: null
15:07:54.707 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$1's kotlin.Metadata: null
15:07:54.717 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$3's kotlin.Metadata: null
15:07:54.718 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$3's kotlin.Metadata: null
15:07:54.724 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$3's kotlin.Metadata: null
15:07:54.727 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toMap$2's kotlin.Metadata: null
15:07:54.727 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$1's kotlin.Metadata: null
...
15:09:13.994 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException (no error message)

```
