### ISSUE TITLE
IllegalStateException: Module with the Main dispatcher is missing

### ISSUE THREAD

**Issue by trashkalmar** [Kotlin/kotlinx.coroutines#799]
Our user with Xiaomi Redmi Note 4 device (Android 7.1.2) suddenly started to experience crash that had to be fixed with #657.
We're unable to reproduce it on our side. Here is reproducer app with the same lib dependencies as our main application: https://www.dropbox.com/s/eay696h9qmxjl5e/sample.zip?dl=1

AndroidX AppCompat: 1.0.0
Kotlin: 1.3.0
Coroutines: 1.0.0
Gradle wrapper: 4.10.2-bin

```
Caused by java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
       at kotlinx.coroutines.MissingMainCoroutineDispatcher.missing(Dispatchers.kt:123)
       at kotlinx.coroutines.MissingMainCoroutineDispatcher.dispatch(Dispatchers.kt:116)
       at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:279)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:23)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
       at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
       at our.app.ui.base.BaseActivity.startAsync(BaseActivity.kt:229)
       at our.app.ui.main.MainActivity.refreshServerConfig(MainActivity.kt:63)
       at our.app.ui.main.MainActivity.onCreate(MainActivity.kt:134)
       at android.app.Activity.performCreate(Activity.java:6738)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by trashkalmar** [comment]
UPD: We also use jetifier processor:
```
classpath "com.android.tools.build.jetifier:jetifier-processor:1.0.0-alpha10"
```
Newer version (1.0.0-beta02) is not compatible with databinding.

**Comment by Arayldan** [comment]
Uncomment the last two lines in your sample's proguard-rules.pro

**Comment by evgentset** [comment]
I has same issue and fixed it by adding options from [coroutines.pro](https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-core/resources/META-INF/proguard/coroutines.pro) to proguard. Hope it helps somebody.

**Comment by marlboro3420** [comment]
@evgentset thanks,it's works for me. coroutines version 1.0.1

**Comment by GGreenwood** [comment]
Seconding @evgentset's fix! Worked for me on coroutines 1.1.1

**Comment by dendrocyte** [comment]
I have the same issue. but the link is not available now. Could  @evgentset provide again? please

**Comment by marlboro3420** [comment]
[coroutines.pro](https://github.com/marlboro3420/KotlinDemo/blob/master/coroutines.pro) @dendrocyte a copy from @evgentset

**Comment by kimcy929** [comment]
@dendrocyte if you are having options for Kotlin in build.gradle packageOptions you can remove them. It will work again without need adding the proguard rule. In my case, I could export file APK but it had the RunTimeException when opening the app so I removed all packageOptions for kotlin and it worked fine with Kotlin 1.3.31 and coroutine 1.2.1

**Comment by endru-kargo** [comment]
In our case, we put `signingConfigs` in the gradle file, then use the `Generate Signed Bundle / APK` to create the bundle. :D
Removing the `signingConfigs` solves the problem.

**Comment by dendrocyte** [comment]
@endru-kargo I will try your solution later. thank you!!!

**Comment by elizarov** [comment]
Did it help?

**Comment by kimcy929** [comment]
@elizarov My way can't cover any devices as when I used the version 1.2.0. I not sure, this problem related to Android ROM. Because of almost devices from China producers.

![image](https://user-images.githubusercontent.com/4311848/57821883-68f5b180-77bc-11e9-88b9-fe4f8aa45933.png)

![image](https://user-images.githubusercontent.com/4311848/57821897-79a62780-77bc-11e9-8811-8af0bedb34f5.png)

![image](https://user-images.githubusercontent.com/4311848/57821922-95113280-77bc-11e9-88e9-7d1312506cd7.png)

![image](https://user-images.githubusercontent.com/4311848/57821951-abb78980-77bc-11e9-9e7e-57b629c46a45.png)

![image](https://user-images.githubusercontent.com/4311848/57821979-c5f16780-77bc-11e9-8092-99147916284d.png)

**Comment by dendrocyte** [comment]
my client phone are Samsung and Sharp which are hit this error.
At the end, I upgrade your lib to 1.2.1, and make the error hit 
Job as CompletableJob. 
Then it fix!

**Comment by RahulSDeshpande** [comment]
> I has same issue and fixed it by adding options from [coroutines.pro](https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-core/resources/META-INF/proguard/coroutines.pro) to proguard. Hope it helps somebody.

Correcting the git link '[coroutines.pro](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro)'.

**Comment by igorwojda** [comment]
For me updating Koltin to `1.3.50` and coroutines to `1.3.2` (having AGP `3.5.1`) fixed the issue (I guess that it was initially broken by APG update or Dexguard update)

**Comment by jmamath** [comment]
It was also discussed in issue [#1532.](https://github.com/Kotlin/kotlinx.coroutines/issues/1532) Turning kotlin [1.3.50 -> 1.3.61], coroutines [1.3.1 -> 1.3.3] did the work for me.
