### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.coroutines.jvm.internal.Boxing.boxİnt(I)Ljava/lang/Integer

### ISSUE THREAD

**Issue by gmetekorkmaz** [Kotlin/kotlinx.coroutines#852]
Why am I getting such an error?

> CODE

```
import kotlinx.coroutines.*

suspend fun getir(): Int {
    delay(1000)
    return 10
}

fun main(args: Array<String>) {
    runBlocking {
        async {
            getir()
        }.await()

    }
}
```

> build.gradle

```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.10'
}

group 'haha'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.1'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

buildscript {
    ext.kotlin_version = '1.3.0'
}
```

> Surprise

```
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.coroutines.jvm.internal.Boxing.boxİnt(I)Ljava/lang/Integer;
	at AppKt.getir(app.kt:5)
	at AppKt$getir$1.invokeSuspend(app.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:67)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:275)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:264)
	at kotlinx.coroutines.AbstractContinuation.dispatchResume(AbstractContinuation.kt:182)
	at kotlinx.coroutines.AbstractContinuation.completeStateUpdate(AbstractContinuation.kt:250)
	at kotlinx.coroutines.AbstractContinuation.updateStateToFinal(AbstractContinuation.kt:222)
	at kotlinx.coroutines.AbstractContinuation.resumeImpl(AbstractContinuation.kt:195)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuation.kt:264)
	at kotlinx.coroutines.EventLoopBase$DelayedResumeTask.run(EventLoop.kt:307)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at AppKt.main(app.kt:10)

Process finished with exit code 1
```

**Comment by qwwdfsad** [comment]
Did it happen after a project update to 1.3+1.0?
Have you tried to clean IDEA/Android Studio caches and rebuild a project from scratch?

**Comment by gmetekorkmaz** [comment]
I've cleared the all cache but it doesn't work.
this error only gives async and repeat method

**Comment by gmetekorkmaz** [comment]
if I'm using x variable type gives error? okay but why ?

> Error

```
suspend fun getir(): Int {
    delay(1000)
    return 10
}

```

> Working

```
suspend fun getir(): Long {
    delay(1000)
    return 10
}

```

**Comment by qwwdfsad** [comment]
What version of Kotlin plugin is installed into your IDEA?
Such error can happen only due to Kotlin versions clash.
