### ISSUE TITLE
IllegalStateException crash: call to 'resume' before 'invoke' with coroutine

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#864]
After debugging my coroutines a bit, I've experienced weird crash. This is the shortest example I've been able to come up with:

```
fun main() {
    TestScope().doTheCrash()

    // Just wait for long time to allow above coroutine to run
    runBlocking { delay(100000) }
}

class TestScope : CoroutineScope {
    private val job = SupervisorJob()

    override val coroutineContext: CoroutineContext
        get() = job

    fun doTheCrash() {
        inlineLaunch {
            GlobalScope.launch {
                delay(500)
                println("Children of the job: [${job.children.joinToString()}]")
            }
        }
    }

    private inline fun inlineLaunch(
            crossinline block: suspend CoroutineScope.() -> Unit
    ) {
        launch {
            block()
        }
    }
}
```

Running above code will crash with

```
Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: call to 'resume' before 'invoke' with coroutine
	at TestScope$doTheCrash$$inlined$inlineLaunch$1$lambda$1.invokeSuspend(Test.kt:31)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Reproduced on Kotlin 1.3.10 and coroutines-core 1.0.1.

**Comment by qwwdfsad** [comment]
It is a complier bug: https://youtrack.jetbrains.com/issue/KT-25893
Will be fixed in 1.3.20
