### ISSUE TITLE
IllegalStateException occurs when deleting META-INF and re-signing the APK file

### ISSUE THREAD

**Issue by solmin719** [Kotlin/kotlinx.coroutines#958]
Coroutine crash when we removed META-INF directory from APK file and re-sign it.
We don't use proguard.
Coroutine version is 1.1.1.

Can we avoid the crash with re-signing? or do you have a plan for fix this?

- steps
1. Remove META-INF directory from APK file (unzip and remove it and re-zip)
2. Re-sign the APK file by using apk-signer
3. Align and verify the APK file by using apk-signer
4. Install the APK file into a device

`
2019-01-28 11:15:18.088 7809-8178/com.example.app E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
    Process: com.example.app, PID: 7809
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.MissingMainCoroutineDispatcher.missing(Dispatchers.kt:123)
        at kotlinx.coroutines.MissingMainCoroutineDispatcher.dispatch(Dispatchers.kt:116)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:282)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:23)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.example.app.core.util.CoroutineHelperKt.uiCoroutine(CoroutineHelper.kt:19)
        at com.example.app.core.util.CoroutineHelperKt.uiCoroutine$default(CoroutineHelper.kt:18)
        at com.example.app.aaa.view.icon.MyIcon$applyLimit$1.invoke(MyIcon.kt:115)
        at com.example.app.aaa.view.icon.MyIcon$applyLimit$1.invoke(MyIcon.kt:25)
        at com.example.app.core.util.CoroutineHelperKt$workerCoroutine$1.invokeSuspend(CoroutineHelper.kt:36)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
`

**Comment by qwwdfsad** [comment]
It is because coroutines library relies on `META-INF` folder in order to load `Main` dispatcher with `ServiceLoader`.

The only solution is not to remove `META-INF` directory (at least `META-INF/services`)

**Comment by solmin719** [comment]
@qwwdfsad 
Thank you for responding. :+1:
