### ISSUE TITLE
IllegalStateException: Job StandaloneCoroutine{Completed}@f96bd2f is already complete or completing

### ISSUE THREAD

**Issue by dmytrodanylyk** [Kotlin/kotlinx.coroutines#964]
Kotlin version: 1.0.0 - 1.1.1

Code to reproduce the crash

```kotlin
CoroutineScope(Dispatchers.Main).launch { // can be other dispatcher
    doWork()
}

private suspend fun doWork() = also {
    delay(1000)
}
```

Crash
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dmytrodanylyk, PID: 23571
    kotlinx.coroutines.DispatchException: Unexpected exception running DispatchedContinuation[Main, Continuation at com/dmytrodanylyk/MyActivity$onCreate$2.invokeSuspend(MyActivity.kt:77)@a4a8e79]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:237)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Job StandaloneCoroutine{Completed}@51fa672 is already complete or completing, but is being completed with CompletedExceptionally[kotlinx.coroutines.JobCancellationException: Job has completed normally; job=StandaloneCoroutine{Completed}@51fa672]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:743)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285)
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: kotlinx.coroutines.JobCancellationException: Job has completed normally; job=StandaloneCoroutine{Completed}@51fa672
```

**Comment by qwwdfsad** [comment]
Could you please specify Kotlin and coroutines version?
And `also` should have a receiver in your example

**Comment by dmytrodanylyk** [comment]
@qwwdfsad I have added Kotlin version. As for the receiver, in my case, I run the above code in Android Activity.

**Comment by qwwdfsad** [comment]
Thanks for the report. It is a bug in the compiler itself: https://youtrack.jetbrains.com/issue/KT-27819
As a temporal workaround try to avoid `also` or tail-calls, e.g. with a dummy function:

```

private suspend fun doWork() = also {
    delay(1000)
    dummy()
}

private inline fun dummy() {}
```
