### ISSUE TITLE
AnalyserException: cannot pop operand off an empty stack.

### ISSUE THREAD

**Issue by renatoathaydes** [Kotlin/kotlinx.coroutines#98]
Hi, I am trying to use Kotlin coroutines in a test project, but I got this error:

```
Cause: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 316: Cannot pop operand off an empty stack.
Element is unknownThe root cause was thrown at: MethodTransformer.java:34
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:86)
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:83)
        ... 87 more
Caused by: java.lang.RuntimeException: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 316: Cannot pop operand off an empty stack.
        at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:34)
        at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.analyze(MethodTransformer.java:44)
        at org.jetbrains.kotlin.codegen.optimization.captured.CapturedVarsOptimizationMethodTransformer$Transformer.analyze(CapturedVarsOptimizationMethodTransformer.kt:150)
        at org.jetbrains.kotlin.codegen.optimization.captured.CapturedVarsOptimizationMethodTransformer$Transformer.run(CapturedVarsOptimizationMethodTransformer.kt:93)
        at org.jetbrains.kotlin.codegen.optimization.captured.CapturedVarsOptimizationMethodTransformer.transform(CapturedVarsOptimizationMethodTransformer.kt:36)
        at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.java:67)
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:63)
        ... 88 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 316: Cannot pop operand off an empty stack.
        at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:298)
        at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:31)
        ... 94 more
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:221)
        at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:615)
        at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:200)
        ... 95 more
```

Here's the code I used:

```kotlin
private fun run(file: File, keyIndex: Int, valueIndex: Int) = runBlocking {
    val maxFieldIndex = maxOf(keyIndex, valueIndex)

    val partition1 = RandomAccessFile(file, "r")
    val partition2 = RandomAccessFile(file, "r")

    val fileLength = file.length()
    var secondPartitionStartIndex = fileLength / 2L

    partition2.seek(secondPartitionStartIndex)

    while (true) {
        val byte = partition2.read()
        secondPartitionStartIndex++
        if (byte < 0 || byte.toChar() == '\n') {
            break
        }
    }

    val firstPartitionMaxEntry = async(CommonPool) {
        maxOfPartition(partition1, keyIndex, valueIndex, maxFieldIndex, secondPartitionStartIndex.toInt())
    }

    val secondPartitionMaxEntry = async(CommonPool) {
        maxOfPartition(partition2, keyIndex, valueIndex, maxFieldIndex, fileLength.toInt())
    }

    val maxEntry = listOf(firstPartitionMaxEntry, secondPartitionMaxEntry)
            .map { it.await() }
            .maxBy { it.component2().int }

    if (maxEntry == null || maxEntry.first.isEmpty()) {
        println("No entries")
    } else {
        val (key, value) = maxEntry
        println("max_key: $key, sum: $value")
    }
}
```

Where `maxOfPartition` has signature:

```kotlin
private suspend fun maxOfPartition(partition: RandomAccessFile,
                                   keyIndex: Int,
                                   valueIndex: Int,
                                   maxFieldIndex: Int,
                                   lastByteIndex: Int): Pair<String, IntBox>
```

I will post this code on gitHub soon, so if you need it let me know.

**Comment by elizarov** [comment]
This looks like a bug in Kotlin compiler. It would be great if you post it to http://kotl.in/issues

**Comment by renatoathaydes** [comment]
Hm.. ok, [submitted](https://youtrack.jetbrains.com/issue/KT-19475).

**Comment by elizarov** [comment]
Thanks a lot!
