### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;

### ISSUE THREAD

**Issue by kateile** [Kotlin/kotlinx.coroutines#989]
Just after adding coroutines dependency in gradle my app crushes everytime I click button which opens opens this [library](https://github.com/akshay2211/PixImagePicker) activity. I havent even write a singe code which relies on coroutines.

The complete error log is as follows:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.something.app, PID: 7811
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:39)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:34)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48)
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:190)
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:179)
        at com.fxn.pix.Pix.initialize(Pix.java:373)
        at com.fxn.pix.Pix.onCreate(Pix.java:325)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.CompletableDeferredKt" on path: DexPathList[[zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/base.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_resources_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48) 
        at io.fotoapparat.hardware.Device.<init>(Device.kt:39) 
        at io.fotoapparat.hardware.Device.<init>(Device.kt:34) 
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55) 
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48) 
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:190) 
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:179) 
        at com.fxn.pix.Pix.initialize(Pix.java:373) 
        at com.fxn.pix.Pix.onCreate(Pix.java:325) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.something.app-73H3sp1_Eiq1YeynLyQBFA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
E/AndroidRuntime:     at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        		... 6 more`

**Comment by qwwdfsad** [comment]
You are using an old version of `Fotoapparat` that transitively depends on experimental coroutines.
After adding newer coroutines, that are no longer experimental, you have version clash between experimental and non-experimental coroutines.
In order to resolve it, just update `Fotoapparat` to the newer version. I've verified they are using non-experimental coroutines in the latest release.
